### ISSUE TITLE
record_suffix: linux/windows file name mismatch

### ISSUE THREAD

**Issue by szhansen** [arut/nginx-rtmp-module#1010]
I use bellow configure for recorder:

`    application rtmp {
      live on;
	  recorder rec1 {
		  record video manual;
		  record_path /var/www/generov/videos;
		  record_suffix -%F-%T.flv;
		  record_unique on;
	  }

    }`
after record finish,i broser the file name in linux system is : 
`root@raspberrypi:/var/www/videos# ls -l                                                                                                                                                                                         
-rw-r--r-- 1  live-1492655074-2017-04-20-02:24:34.flv   

-rw-r--r-- 1  live-1492655210-2017-04-20-02:26:50.flv                                            
root@raspberrypi:/var/www/videos#  `

but when i browse this file from windows by samba, the file name is : 
`LB0O9U~I.FLV

LX06HV~2.FLV`

anybody who can tell me why and how to solve this problem?
thank you so much.

**Comment by fredleger** [comment]
this is something related to your shortnames settings on samba. Try to set this in your samba config files : 

[global] 
mangled names = no

**Comment by szhansen** [comment]
solved,windows file name can't contain ":",

**Comment by fredleger** [comment]
make sense ...
