### ISSUE TITLE
Dynamically add or remove RTMP url without modifying nginx.conf

### ISSUE THREAD

**Issue by wkdwls1029** [arut/nginx-rtmp-module#1041]
Hello all,

I want to dynamically manage the RTMP URL through api call while nginx is running state.

Is it possible to add or remove RTMP url in dynamically either using ngx_control_module or any other way without modifying nginx.conf?
```c++
application pull {
    live on;
}
```
Thanks.

**Comment by arnaudroulee** [comment]
Did you find a solution ?

bash script with on_publish to check stream name entry and use ffmpeg to push ?
