### ISSUE TITLE
Pull feature consumes about 2gb  of memory? 

### ISSUE THREAD

**Issue by evjenios** [arut/nginx-rtmp-module#1042]
Hi guys!

I've noticed strange problem: pull feature of the nginx-rtmp module consumes about 2gb memory pages per 1 stream. Is this ok for this module?

nginx version is 1.11.13

Thanks

**Comment by evjenios** [comment]
Issue present in nginx 1.13 and rtmp 1.1.11 and trunk.

**Comment by evjenios** [comment]
malloc(2147483665) failed (12: Cannot allocate memory) - in error.log

**Comment by evjenios** [comment]
I've definitely determined the source of this issue.

My rtmp server sends wrong chunk_size (2147483647) and nginx-rtmp doesn't check it.

        case NGX_RTMP_MSG_CHUNK_SIZE:
            /* set chunk size =val */
            ngx_rtmp_set_chunk_size(s, val);
            break;

Valid sizes are 1 to 2147483647 (0x7FFFFFFF) inclusive; however, all sizes greater than 16777215 (0xFFFFFF) are equivalent since no chunk is larger than one message, and no message is larger than 16777215 bytes.

I've modified code:
----
            if(val>16777215) val = 16777215;
            ngx_rtmp_set_chunk_size(s, val);
----

This string solved extra memory consumption.

Any side effects?

**Comment by arut** [comment]
Thanks for reporting this. I'll commit fix soon.

**Comment by arut** [comment]
Committed.
