### ISSUE TITLE
[emerg] invalid port in url "http://xxx.xx.xx.xx/xx" in /usr/local/nginx/conf/nginx.conf:16

### ISSUE THREAD

**Issue by catalitico** [arut/nginx-rtmp-module#1053]
This is my conf file and i have no idea :( i am pulling http encoding for testing purposes and it worked with a different installation in a vps. Migrated to dedicated and can't get this to run...

--
worker_processes  auto;
events {
    worker_connections  1024;
}

# RTMP configuration
rtmp {
    server {
        listen 1935; # Listen on standard RTMP port
        chunk_size 4000;

        application show {
            live on;

pull http://XXx/xx name=xx live=1 name=xx;

                   # Turn on HLS
            hls on;
            hls_path /tmp/hls/;
            hls_fragment 3;
            hls_playlist_length 60;
            # disable consuming the stream from nginx as rtmp
            deny play all;
        }
    }
}
http {
    sendfile off;
    tcp_nopush on;
    aio on;
    directio 512;
    default_type application/octet-stream;

    server {
        listen 8080;

        location / {
            # Disable cache
            add_header 'Cache-Control' 'no-cache';

            # CORS setup
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
add_header 'Access-Control-Allow-Headers' 'Range';

            # allow CORS preflight requests
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Headers' 'Range';
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain charset=UTF-8';
                add_header 'Content-Length' 0;
                return 204;
            }

            types {
                application/dash+xml mpd;
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }

            root /tmp/;
# rtmp statistics
        location /stat {
            rtmp_stat all;
            rtmp_stat_stylesheet stat.xsl;
        }

        location /stat.xsl {
            # you can move stat.xsl to a different location
            # under linux you could use /var/user/www for example
            root html;
        }

        }
    }
}

**Comment by notstevek** [comment]
try changing `pull http://XXx/xx name=xx live=1 name=xx;`
to `pull 'http://XXx/xx name=xx live=1 name=xx';`
to adjust for spaces, per the [wiki](https://github.com/arut/nginx-rtmp-module/wiki/Directives#pull).

**Comment by catalitico** [comment]
Thanks will format it now
