### ISSUE TITLE
can't stream audio only with flv/rtmp (ffmpeg, AAC)

### ISSUE THREAD

**Issue by csurf** [arut/nginx-rtmp-module#1077]
I'm trying to stream an 'audio-only' rtmp stream into the nginx rtmp module, but it seems to be failing. The audio is coming from a FM radio USB dongle (ADS InstantFM). 

Here's a snippet of my ffmpeg command.
/usr/local/bin/ffmpeg -f alsa -ar 96000 -ac 2 -i hw:$HW,0 \
 -vcodec libx264 -vprofile baseline -g 30 -acodec aac -strict -2 \
-ar 44100 -ab 128k \
-f flv  \
tcp://localhost:1935/show/stream

Any ideas what's going wrong? Is there a limitation with the nginx-rtmp module that prevents it from handling audio-only streams (i.e., with no embedded x264 video) ??? Or, should this be able to work?

edit:
nevermind, think I found the problem. Needed to use rtmp:// url into ffmpeg.

**Comment by HuHeng** [comment]
i have the same problem with "interleave off".
