### ISSUE TITLE
stat module doesn't show running streams and clients

### ISSUE THREAD

**Issue by xueyihan** [arut/nginx-rtmp-module#1086]
At first I can /stat show the running streams, but after few minutes, /stat show no running streams while there is a stream exactly.

**Comment by xueyihan** [comment]
http {
    server {
        listen    8081;
        server_name   localhost;

        location /stat {
            rtmp_stat all;
            rtmp_stat_stylesheet stat.xsl;
        }
        location /stat.xsl {
            root html;
        }
    }
}

rtmp {
    server {
        listen 1935;
        application live {
            live on;
        }
    }
}

**Comment by bjuri** [comment]
Hi @xueyihan , 
How much workers in nginx.conf do you have ?
Currently nginx-rtmp-module correctly works only in the **1 worker configuration**. What does it means:
Each tcp connection to the nginx always balancing between nginx-workers, that affects rtmp and http(s) connections. So your **nginx-worker 1** can receive rtmp connection, but your .../stat request will be processed by **nginx-worker 2-n** and as result your **2-n worker** doesn't know nothing about first rtmp connection.
You can try to achieve multi-worker configuration by reading article from @arut blog's https://rarut.wordpress.com/2013/06/18/multi-worker-statistics-and-control-with-nginx-per-worker-listener-patch/

**Comment by xueyihan** [comment]
Thanks! @bjuri
