### ISSUE TITLE
exec not working!

### ISSUE THREAD

**Issue by zameelpichen** [arut/nginx-rtmp-module#1102]
please tell why exec is not working.
https://github.com/arut/nginx-rtmp-module/issues/1100

exec is not at all executing ffmpeg. also, ffmpeg alone is working on the terminal.!

this is a strange situation. please help me.

**Comment by potsky** [comment]
Hi @zameelpichen, do you use events like `on_publish` in the `server` scope of the `rtmp` parameter ?

**Comment by RookieZhou94** [comment]
I also meet this question and use on_publish,on_play,on_done in the app  @scope of the rtmp @potsky

**Comment by potsky** [comment]
On my configuration, putting these settings in the server scope fails. In the ingress app, it works. This is normal because using exec with ffmpeg to redirect the initial app to another app will generate infinite events.

**Comment by lookapanda** [comment]
@potsky and what is a solution for that?

**Comment by lzqdename** [comment]
exec_static /usr/bin/sh   shelll_script_file_name;    It works, I have test it!
