### ISSUE TITLE
No support for HTTP VOD

### ISSUE THREAD

**Issue by lungati** [arut/nginx-rtmp-module#1160]
Just watched this video https://youtu.be/t8ebB9Pxb2s?t=817 talking about how to enable HTTP VOD.. Think its a useful video for those trying the same.

**Comment by UKNickyD** [comment]
You could use ffmpeg to split the video in to chunks... But may I ask why you want / need it played over hls? If it's just for the html5 video it'd probably be easier just to reference the file directly and cut out nginx-rtmp all together... Securing the file from unwanted direct downloads can be solved using php etc.
