### ISSUE TITLE
"unexpected "}"" / Windows RTMP issue

### ISSUE THREAD

**Issue by silverkx2000** [arut/nginx-rtmp-module#1177]
So I followed this guide on YouTube here: https://www.youtube.com/watch?v=rA_06zRKE4c
to try and set up an RTMP relay on a Windows server (I'm a noob at linux).

Before I was getting: "unknown directive "rtmp"" in the error logs whenever I followed that particular guide as nginx was not recognizing the rtmp module for some weird reason. 

Finally I caved and went with another YouTube guide that gave a premade config file and I got the server running! SUCCESS!! However I ran into another issue when trying to initiate the "push" application as Nginx returned the follow error:

`unexpected "}" in C:\Users\Administrator\Desktop\nginx5/conf/nginx.conf:21`

I've literally done everything I can think of and I just can't get the push command to work and I'm confused. If I go with a newer version of Nginx, it simply tells me that rtmp is an unknown directive.  

Any help would be greatly appreciated!
here is my config file with the unexpected brace.

`#user				nobody;
worker_processes	1;
 
error_log			logs/rtmp_error.log debug;
pid				logs/nginx.pid;
 
events {
	worker_connections	1024;
}
 
rtmp {
	server {
		listen 1935;
		chunk_size 8192;
		
		application live{
			live on;
			record off;
			push rtmp://live-sfo.twitch.tv/app/live_MYSTREAMKEY
			
		} 
	}
}

http {
	allow all;
	deny all;
 
	access_log		logs/rtmp_access.log;
	include			mime.types;
	default_type		application/octet-stream;
	sendfile		on;
	keepalive_timeout	65;
 
	server {
		listen		80;
		server_name	localhost;
		
		# rtmp stat
		location /stat {
			rtmp_stat all;
			rtmp_stat_stylesheet stat.xsl;
		}
		
		location /stat.xsl {
			# you can move stat.xsl to a different location
			root html;
		}
 
		error_page   500 502 503 504  /50x.html;
		location = /50x.html {
			root   html;
		}
	}

}`

thank you in advanced!

**Comment by silverkx2000** [comment]
update: cleaner look at the code: https://pastebin.com/4ctFTYwq

**Comment by MTRNord** [comment]
You missed a `;` in 19. If you add it at the end of the line it should not fail with that error anymore

**Comment by MTRNord** [comment]
*line 19

**Comment by silverkx2000** [comment]
I JUST SAW THAT lol. 
but now the Nginx server won't show up. I guess ill figure that out later. 
but now the server refuses to connect. 

Ill restart my server and try again.

**Comment by silverkx2000** [comment]
Thank you @MTRNord for the help!

**Comment by MTRNord** [comment]
You're welcome :)
