### ISSUE TITLE
15 second delay in live stream

### ISSUE THREAD

**Issue by alecgorge** [arut/nginx-rtmp-module#119]
I am experiencing a 15 second delay between the input and the output of a live RTMP stream.

Is there any way to decrease this?

I have fiddled with the `chunk_size` directive by moving it from `4096` to `128` and up to `10240`, but nothing has really changed it.

**Comment by KrisRoofe** [comment]
You can use ffplayer with nobuffer to test the latency, refer to this [answer](https://stackoverflow.com/a/45370210/6521116)
