### ISSUE TITLE
pushing to facebook howto?

### ISSUE THREAD

**Issue by Timoffey** [arut/nginx-rtmp-module#1190]
for youtube and twitch everything is OK:
push rtmp://live-fra.twitch.tv/app/live_1224_some_other_symbols;

but for FB and VK this don't work:
push rtmp://rtmp-api.facebook.com/rtmp/95here82?s_ps=1&a=ATthereb9;

But if I paste this into OBS separate for address and key – everything is OK.
address: rtmp://rtmp-api.facebook.com/rtmp/
key: 95here82?s_ps=1&a=ATthereb9

Maybe "/" is not good idea? Or what the problem? Help me plz!

**Comment by Timoffey** [comment]
In config structure is 
aliases in server section:
server{
push rtmp://localhost/youtube;
            push rtmp://localhost/twitch;
            push rtmp://localhost/facebook;
            push rtmp://localhost/vkontakte;}

and configuration in application section:

application youtube {
            live on;
            record off;

            push rtmp://a.rtmp.youtube.com/live2/<key>;
        }
I did not have aliases for FB and VK. Now i Fix it.

**Comment by kkrishnan90** [comment]
Hey @Timoffey  I have the same config too. However, I would like to key to be dynamic as the front end client handles the youtube login and getting the stream key through YouTube API request/response. Could you please tell me how to have the key to be dynamic and pass as a dynamic parameter ?

**Comment by Brandonza** [comment]
Hi

Have you managed to use a dynamic key?
