### ISSUE TITLE
transcoding not running well on multiple cores

### ISSUE THREAD

**Issue by nclr** [arut/nginx-rtmp-module#1194]
I'm trying to transcode into multiple bitrates (2 lower bitrates and source) 6 720p streams but when I start nginx, it only sucessfully transcodes about 2-3 streams (RANDOMLY) and the server is only at ~20-25% load. Other streams show no video but you can hear the audio.

My server is a Xeon VPS 8 cores (with no noisy neighbours currently). Yes maybe 6 streams are too many but shouldn't I expect at least maxing the cpus? Also tried different cloud providers, still exactly the same thing happens.

Here is my config. Am I missing something?

user www-data;
worker_processes  20; # had this one at 1 (same problem) and auto (failed - no transcoding any stream)
pid logs/nginx.pid;
events {
    worker_connections  1024;
}
rtmp_auto_push on; #introduced this along with the 20 workers

# RTMP configuration
rtmp {
    server {
        listen 1935; # Listen on standard RTMP port
        chunk_size 4000;
        max_streams 82; # possible fix? but didn't do it

	application all {
	live on;

	application myChannel {
	live on;
		exec_push /usr/bin/ffmpeg -i rtmp://localhost/$app/$name
                        -c:v libx264 -c:a libfdk_aac -b:v 256k -b:a 32k -vf "scale=320:trunc(ow/a/2)*2" -preset veryfast -crf 23 -f flv rtmp://localhost/show/$name_low
                        -c:v libx264 -c:a libfdk_aac -b:v 512k -b:a 96k -vf "scale=480:trunc(ow/a/2)*2" -preset veryfast -crf 23 -f flv rtmp://localhost/show/$name_mid
                        #-c:v libx264 -c:a libfdk_aac -b:v 768k -b:a 128k -vf "scale=576:trunc(ow/a/2)*2" -preset veryfast -crf 23 -f flv rtmp://localhost/show/$name_high
			-c copy -f flv rtmp://localhost/show/$name_src;
	}

        application show {
            live on;
            # Turn on HLS
            hls on;
            hls_path /mnt/thehls;
            hls_fragment 6s;
            hls_playlist_length 20s;
            hls_variant _low BANDWIDTH=288000;
	    hls_variant _mid BANDWIDTH=448000; # Medium bitrate, SD resolution
            hls_variant _src BANDWIDTH=1152000; # Source bitrate, source resolution
 

           # disable consuming the stream from nginx as rtmp
            deny play all;
        }
}

Thank you all for reading this.

**Comment by djevo1** [comment]
Stupid question but did you try removing the comment symbol in the ffmpeg line as Nginx may be treating every line after the # but before the ; as a comment. That could be the only reason you see two streams. What version of ffmpeg are you running?

**Comment by hoodsy** [comment]
@nclr any resolution to this issue for you?

**Comment by nclr** [comment]
@hoodsy @djevo1  This error was caused by VMWare ESXi that the server was running. After changing to bare metal all these error stopped.
