### ISSUE TITLE
hls_variant cannot adapt dynamically after client playing

### ISSUE THREAD

**Issue by vincentcheng62** [arut/nginx-rtmp-module#1197]
I follow everything in the wiki about the usage of the directive 'his_variant' and
the streaming is successful.

However, I found out that only the clients' bandwidth at the beginning will determine
which streams it points to. When I try to reduce the clients' bandwidth afterwards (by using
NetLimiter in Windows), the streaming video resolution has no changes at all.

P.S. I use ffplay at the client side to stream video, my client is win7 PC.

**Comment by mrfrieza** [comment]
Hello!

I'm just a user like you, and I'm pretty new to this but I think it's not how it works.. 

Sure, the beginning determines what's the quality of the 1rst set of .ts, but check the access log, the m3u8 updates itself and is re-checked pretty often (every 30 - 45 seconds) so, to my opinion, it adapts the quality at these times. 

This is only my opinion though, and I believe that except by this procedure, you won't be able to adapt the quality in a better way (except if you succeed at getting this vars into the .ts themselves).

MrFrieza

**Comment by vincentcheng62** [comment]
Not only the server side needs to create a master playlist with multiple bitrate, 
the hls client also needs to support adaptive bitrate streaming.
As far as I know, safari browser, exoplayer in android and hls.js support adaptive bitrate streaming.
