### ISSUE TITLE
How to liveStream Camera and document at the same time use nginx-rtmp-module

### ISSUE THREAD

**Issue by NguyenTungs** [arut/nginx-rtmp-module#1211]
Hi Guys!
I see on the Youtube, they can liveStream Camera and document. But i just know live Camera or Document if single thread. So anybody can help me or give me an advice or a suggest about this problem.

Sample stream camera on mac to server: 
`ffmpeg -f avfoundation -r 30 -i “0:0” -deinterlace -vcodec libx264 -pix_fmt yuv420p -preset medium -g 60 -b:v 2500k -acodec libmp3lame -ar 44100 -threads 6 -qscale 3 -b:a 712000 -bufsize 512k -f flv rtmp://localhost/live/tungns`

Stream from a file to server:
`fmpeg -re -i file.pdf -c:v libx264 -preset veryfast -maxrate 3000k -bufsize 6000k -pix_fmt yuv420p -g 50 -c:a aac -b:a 160k -ac 2 -ar 44100 -f flv rtmp://localhost/live/tungns`.

So  I need  How to liveStream Camera and document at the same time use nginx-rtmp-module. Thanks a lot!

**Comment by djevo1** [comment]
Have you tried using `-threads 2` in ffmpeg with a filter complex as per this [thread](https://stackoverflow.com/questions/35269387/ffmpeg-overlay-one-video-onto-another-video)?

**Comment by NguyenTungs** [comment]
Works perfectly - thanks! @djevo1

**Comment by djevo1** [comment]
@NguyenTungs No problem, I think you can close this ticket.
