### ISSUE TITLE
Just an information.. Please ?

### ISSUE THREAD

**Issue by mrfrieza** [arut/nginx-rtmp-module#1215]
Hello to all of you,

Just one question !

Is it possible to stream multiple inputs (multiple obs instances) to a single nginx instance, so that it would create multiple hls and dash streams ?

Thanks !!

**Comment by RocFang** [comment]
Of course it is possible.

**Comment by mrfrieza** [comment]
Thank you for your answer RocFang !

My assumption is that I don't need to add multiple applications but only one with different stream key (obs). 

For example (with an application called "live) : 

Input 1 : rtmp://192.168.x.x/live / stream key : abc ==> creates a "abc.m3u8" and "abc.mpd" playlist
Input 2 : rtmp://192.168.x.x/live / stream key : def ==> creates a "def.m3u8" and "def.mpd" playlist
Input 3 : rtmp://192.168.x.x/live / stream key : ghi ==> creates a "ghi.m3u8" and "ghi.mpd" playlist 

Is this assumption correct ? 

Just thought of this... I was wondering how to add multiple "application" directives, and thought that only the name had to change, not the settings... ^^"

If this is true, my issue would be solved ! Thanks again !

**Comment by misiek08** [comment]
Yes, if you don't need specific configuration for each of such "channel",
then it will solve your case.

W dniu niedz., 25.02.2018 o 15:15 MrFrieza <notifications@github.com>
napisał(a):

**Comment by RocFang** [comment]
@mrfrieza  you can push different streams to the same application, otherwise there is no meaning of existing for a rtmp server.:)

**Comment by mrfrieza** [comment]
Thanks then, this problem is solved (even if I got many more lol)
