### ISSUE TITLE
Invalid port in url

### ISSUE THREAD

**Issue by worellana** [arut/nginx-rtmp-module#1240]
I had troubles when I try to configure Mixer stream because the URL has a port number 
`rtpm://ingest-dal.mixer.com:1935/beam/ `
the module always throws an error, it's there any way to configure Mixer?

**Comment by wlami** [comment]
Port numbers are no problem. I'm using such a configuration myself. Which error do you get and how does your configuration look like?

**Comment by worellana** [comment]
The errror is the following

``nginx: [emerg] invalid port in url "rtpm://ingest-dal.mixer.com:1935/beam/xxxxxxxxxxxxxxxxxx" in C:\nginx/conf/nginx.conf:214

My config file is
``rtmp {
    server {
        listen 1935;
        chunk_size 4096;
 
        application live {
            live on;
            record off;
            push rtmp://live-ams.twitch.tv/app/xxxxxxxxxxxx;
            push rtmp://a.rtmp.youtube.com/live2/xxxxxxxxxxxxx;
            push rtmp://srs-us-dev-lb.omlet.me/omlet/xxxxxxxxxxxxxxxx;
            push rtmp://live-api.facebook.com:80/rtmp/xxxxxxxxxx;
            push rtmp://live.mobcrush.net/stream/xxxxxxxxxxxxxx;
            push rtpm://ingest-dal.mixer.com:1935/beam/xxxxxxxxxxxxxxxxxx;
        }
    }
}

**Comment by misiek08** [comment]
You didn't even read your own configuration file....

You have "rtpm" instead of "rtmp" in last address.

>

**Comment by wlami** [comment]
@worellana Please be so kind and close this issue.
