### ISSUE TITLE
exec_record_done not firing for bash script

### ISSUE THREAD

**Issue by hoodsy** [arut/nginx-rtmp-module#1260]
For some reason, `exec_record_done` works when triggering `ffmpeg`, for example: 
`exec_record_done ffmpeg -y -i $path -acodec libmp3lame -ar 44100 -ac 1 -vcodec libx264 $dirname/$basename.mp4;`

But when trying to execute any other script, `exec_record_done` doesn't seem to be triggered:
`exec_record_done bash -c "nodejs /static/scripts/vod-test.js $path $dirname $basename";`

I've enabled debug, and there doesn't seem to be anything relevant in the debug log. Here are the 
(seemingly) relevant lines: 
```
2018/05/07 17:12:58 [debug] 6#0: *1 record: stop
2018/05/07 17:12:58 [debug] 6#0: *1 write: 12, 00007FFE0D2E527F, 1, 4
2018/05/07 17:12:58 [debug] 6#0: *1 record:  closed
2018/05/07 17:12:58 [debug] 6#0: *1 record:  path: '/data/hls/test.flv'
2018/05/07 17:12:58 [debug] 6#0: *1 exec: record_done 1 unmanaged command(s)
2018/05/07 17:12:58 [info] 6#0: *1 exec: starting unmanaged child 'bash', client: 172.17.0.1, server: 0.0.0.0:1935
2018/05/07 17:12:58 [debug] 6#0: *1 exec: child 'bash' started pid=30
2018/05/07 17:12:58 [debug] 6#0: *1 recv: fd:10 0 of 4114
2018/05/07 17:12:58 [debug] 6#0: *1 finalize session
2018/05/07 17:12:58 [debug] 6#0: *1 post event 0000000000E9B640
2018/05/07 17:12:58 [debug] 6#0: timer delta: 16
2018/05/07 17:12:58 [debug] 6#0: posted event 0000000000E9B640
2018/05/07 17:12:58 [debug] 6#0: *1 delete posted event 0000000000E9B640
2018/05/07 17:12:58 [debug] 6#0: *1 close session
2018/05/07 17:12:58 [info] 6#0: *1 disconnect, client: 172.17.0.1, server: 0.0.0.0:1935
2018/05/07 17:12:58 [info] 6#0: *1 deleteStream, client: 172.17.0.1, server: 0.0.0.0:1935
2018/05/07 17:12:58 [debug] 6#0: *1 exec: delete 1 push command(s)
2018/05/07 17:12:58 [debug] 6#0: *1 live: not joined
2018/05/07 17:12:58 [debug] 6#0: *1 record: close_stream
2018/05/07 17:12:58 [debug] 6#0: *1 record: stop
```

Why might this be happening? I've tested my `bash` and `node` scripts, and I can execute the same commands manually without error. To me, it seems that these commands aren't being run by `exec_record_done`

**Comment by qhchen2** [comment]
Have you tried using exec instead? because that can run a bash script in my setup. If that doesnt work either then it may or maynot be an issue in the module. But I don't know why exec_record_done doesnt work in your case.

**Comment by hoodsy** [comment]
I ended up getting it working with `exec_record_done` – it was tricky to trace errors from my bash script

**Comment by rubensben** [comment]
hi, where was the solution ? I'm facing the same issue ^^

**Comment by rubensben** [comment]
Found the solution : don't create your scripts on windows but on the terminal !

**Comment by haythembenkhlifa** [comment]
hi,
I did create a file addtodatabase.sh with nano and i add the following code :

the path for the file  /home/addtodatabase.sh

#!/bin/bash
echo "INSERT INTO comments (comment,owner,live_id) VALUES ('test, '2', '9');" | mysql -uUSER-pPASS DB_NAME;

if I execute it in the command line it works 100% fine.

and on the nginx.conf i did try 

exec_record_done bash -c "/home/addtodatabase.sh"; 

but it does not work is there some can help me with it Thank You.

**Comment by solariz** [comment]
> 
> 
> I ended up getting it working with `exec_record_done` – it was tricky to trace errors from my bash script

Just something for the Future - if you found a solution to a problem it would be nice to share it to others. Stuck at exactly the same, starting debugging now.

**Comment by patrikrask** [comment]
I have the same problem. Any solution?

**Comment by muthu-tm** [comment]
Facing the same issue.. any solution for this?

**Comment by Cpt-Ramirez** [comment]
Hi, first time answering to anything on github.

I do:

exec_record_done bash /usr/local/nginx/scripts/recordAndClean.sh $path $basename;

and before I added the line, I gave permissions to the bash file with chmod 0755 /path/to/file.sh

My bash file:
----------------------------------------------------------------------------------------------
#!/bin/bash

filePath=$1
baseName=$2

/usr/bin/ffmpeg -i $filePath -acodec copy -vcodec copy /var/vod/$baseName.mp4 && rm $filePath
----------------------------------------------------------------------------------------------

So the "&&" after the ffmpeg command runs another command after the prior was finished successfully. 

Hope this helps (even if too late for many)

**Comment by yousefalsatouf** [comment]
Thanks, it worked for me :-)

**Comment by meanii** [comment]
> I ended up getting it working with `exec_record_done` – it was tricky to trace errors from my bash script

how you did?
