### ISSUE TITLE
rtmp-moduld push format error

### ISSUE THREAD

**Issue by MikiraSora** [arut/nginx-rtmp-module#1304]
(char '?'or'x' mean litter/digit for private protection)
I have a rtmp address and key like these: 
![image](https://user-images.githubusercontent.com/7549173/43817253-0d04a946-9b0b-11e8-8314-3ae182bd0f25.png)
```
stream rtmp addr: rtmp://js.live-send.acg.tv/live-js/
stream key: ?streamname=live_455??????????50078&key=5bf4e6f01f?????????????aa031d0c58e
```
I want to redirect stream and nginx.conf write:
```
rtmp {
    server {
        listen 1935;

        application stream {
            live on;
            push rtmp://live-hkg.twitch.tv/app/live_143306366_BteadX5euzxxxxxxxxxxxxNGngW4sJo;
            push rtmp://js.live-send.acg.tv/live-js?streamname=live_45xxxxxxxx078&key=5bf4e6f01f65xxxxxxxxxxxxxa031d0c58e;
        }
    }
}
```
But nginx told me there is error:
```
PS C:\Users\MikiraSora> docker exec -it sad_kare /opt/nginx/sbin/nginx -s reload
nginx: [emerg] unexpected end of file, expecting ";" or "}" in /opt/nginx/nginx.conf:77
```
the document dosent told method about which provide query string directly without path.
What should I do?

**Comment by MikiraSora** [comment]
right, Multi Stream Pushing must request "live" not "stream".

**Comment by C74K** [comment]
push rtmp://js.live-send.acg.tv/live-js**/**?streamname=live_45xxxxxxxx078&key=5bf4e6f01f65xxxxxxxxxxxxxa031d0c58e;
