### ISSUE TITLE
Rotate rtmp 

### ISSUE THREAD

**Issue by alinasrin** [arut/nginx-rtmp-module#1308]
Hi
I want to rotate rtmp and publish to another rtmp but i cant with this code:
exec ffmpeg -y -i rtmp://x.x.x.x/li/$name?$args -vf transpose=2 -codec copy -f flv rtmp://x.x.x.x/li1/$name?$args;

Does anyone have a solution?

**Comment by cptrodgers** [comment]
FFmpeg exec simple will make exec_push command, not support $args. Only support 
```
$name - stream name
$app - application name
$addr - client address
$flashver - client flash version
$swfurl - client swf url
$tcurl - client tc url
$pageurl - client page url
```

Use can use $tcurl for it: `rtmp://104.215.193.71:1935/live?token=abcxyz`
