### ISSUE TITLE
Suggestion: Stream Key Whitelist

### ISSUE THREAD

**Issue by zhiyan114** [arut/nginx-rtmp-module#1310]
Hey, so I saw you can limit IP from streaming but is it possible to do it with certain stream key instead of IP?

Like u need to have the stream key to stream on a application instead of whitelisted by IP

**Comment by zhiyan114** [comment]
Sorry for delay reply so I can use that to whitelist stream key.
So I sow this option and if an IP do not match that then ill reject stream: `allow publish 127.0.0.1;` but instead of this, i can do something like `allow publish [Stream Key];` instead

**Comment by joaquinm003** [comment]
I need same
