### ISSUE TITLE
./configure: error: C compiler gcc is not found

### ISSUE THREAD

**Issue by DancinDirk** [arut/nginx-rtmp-module#132]
we are trying to install HLS module on Debian/nginx machine using the instructions here:

https://github.com/arut/nginx-rtmp-module/wiki/Building-nginx-rtmp-with-HLS-support

this command

./configure   --add-module=../nginx-rtmp-module-master --add-module=../nginx-rtmp-module-master/hls --add-module=../ngx_cache_purge-master  --with-http_stub_status_module --with-http_ssl_module --with-http_sub_module --with-md5=/usr/lib --with-sha1=/usr/lib --with-http_gzip_static_module

on /usr/local/src/nginx/nginx.1.3.12

we got the message

./configure: error: C compiler gcc is not found

Something seems to be wrong with that configure script.  There is no doubt that gcc is working properly.  build-essentials is installed and up to date.

I see that the instructions reference nginx 1.2.4 and we have nginx 1.3.12

Any thoughts?

Thanks in advance!

**Comment by webhacking** [comment]
how to fix C compiler errors?
