### ISSUE TITLE
RTMP Push then Pull and translate to HLS

### ISSUE THREAD

**Issue by Ericarthurc** [arut/nginx-rtmp-module#1324]
Hey I am trying to push my rtmp stream to youtube and facebook etc.. and that part works great! But I also want to ability to embed my own stream in a website in HTML5. And I can't seem to get HLS working...  I have searched the other issues top and bottom and can't find a solution.

Here is my config:
http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
	}
	location /stat {
	    rtmp_stat all;
            rtmp_stat_stylesheet stat.xsl;
	}
	location /stat.xsl {
	    root /usr/local/nginx/html;
	}
	location /hls {
	    root /tmp;
	    types {
		application/vnd.apple.mpegurl m3u8;
	}		
	}

rtmp {
	server {
		listen 1935;
		chunk_size 4096;

		application live {
			live on;
			record off;
			allow publish all;
			allow play all;

		#push requests for sending rtmp stream to other streaming servers: format: push [rtmp server]/[key];

		push rtmp://a.rtmp.youtube.com/live2/KEYHERE;
		push rtmp://live-api-s.facebook.com:80/rtmp/KEYHERE;
		}
		application hls {
			live on;
			hls on;
			hls_path /tmp/hls;
			hls_fragment 10s;
                        #from OBS
			pull rtmp://192.168.1.242/live/KEYHERE;
		}
	}
}

So I don't even know if this is possible or if my format is correct; but I tried to "pull" my local stream from OBS then translate it to HLS

**Comment by Lax** [comment]
you can merge live/hls then to use only one application.

```
	application live {
		live on;
		record off;
		allow publish all;
		allow play all;


	push rtmp://a.rtmp.youtube.com/live2/KEYHERE;
	push rtmp://live-api-s.facebook.com:80/rtmp/KEYHERE;

		hls on;
		hls_path /tmp/hls;
		hls_fragment 10s;
	}
```

Make sure nginx user have the write permission to `/tmp/hls`.

**Comment by Ericarthurc** [comment]
> you can merge live/hls then to use only one application.
> 
> ```
> 	application live {
> 		live on;
> 		record off;
> 		allow publish all;
> 		allow play all;
> 
> 
> 	push rtmp://a.rtmp.youtube.com/live2/KEYHERE;
> 	push rtmp://live-api-s.facebook.com:80/rtmp/KEYHERE;
> 
> 		hls on;
> 		hls_path /tmp/hls;
> 		hls_fragment 10s;
> 	}
> ```
> Make sure nginx user have the write permission to `/tmp/hls`.

Yeah that worked, combining it all under /live; thank you.
I ended up seeing that there was a permissions issue on /tmp/hls. So I just make a new directory and set the correct permissions for that folder. 

Thanks

**Comment by zhoufanshou** [comment]
> KEYHERE

use what to replace to make sure it difference
