### ISSUE TITLE
Any way to increase 'RTMP Stat' 'bw_video' interval?

### ISSUE THREAD

**Issue by b3ck** [arut/nginx-rtmp-module#1344]
Just wanted to know if there was a way to increase the RTMP Stat: 'bw_video' update interval to every second.

**Comment by b3ck** [comment]
nevermind, found it in: ngx_rtmp_bandwidth.h

**Comment by AsadTalha** [comment]
Is there a way of changing the value of NGX_RTMP_BANDWIDTH_INTERVAL after the installation?
I'm guessing I have to change the value in ngx_rtmp_bandwidth.h before make and install.

**Comment by b3ck** [comment]
> Is there a way of changing the value of NGX_RTMP_BANDWIDTH_INTERVAL after the installation?
> I'm guessing I have to change the value in ngx_rtmp_bandwidth.h before make and install.

Yes, but be careful, I found the lower the interval the less accurate it is.  I believe when I was using it I stayed with 11 seconds as it was the most accurate, and figured that was the reason why it is what it is.. although that might have changed since 2019, so it doesn't hurt to experiment =)

**Comment by AsadTalha** [comment]
Thank you for the help :)
I'll test the accuracy with different intervals.
