### ISSUE TITLE
High Load on Edge Server

### ISSUE THREAD

**Issue by menetas** [arut/nginx-rtmp-module#1347]
Hi, I have this setup and something's very weird and I would take any suggestion to try:
My setup:
I have three high capacity servers exact the same each..
Intel Xeon E5-2640 64 Bits @ 2.4 Ghz
94 GB Ram
SSD 320 GB Storage

One of them it's the Main streaming Server "Main"
And two Edges "Edge1" and "Edge2"

So basically I have configured "Main" to listen rtmp streams 1935.
Some of them are pushed to the server some of them I push them locally using ffmpg -f rtmp://localhost:1935/..

All those streams (about 300-350 streams) are pushed via 
push rtmp://edge1-ip/hls
push rtmp://edge2-ip/hls

Then on each edge server I serve to final users using HLS + Secure Token.
Compiled nginx with nginx-rtmp-module, http_secure_link_module, threads, etc..

Both Edge1 and Edge2 has the very same configuration, exact same hardware, same internet hosting provider, but Edge2 works awful...  

As soon as he starts receiving rtmp streams, Edege2 raises CPU usage load to 10, 20, 30 and then it crashes..
Edge1 is receiving the exact same amount of streams, but it keeps the load as low as 1.0 or 2.0 (Out of 40 Cores)..

I have doble checked both nginx.conf, sysctl variables, file descriptors, everything looks exactly the same in both servers, but Edge2 is simply not working...

I have left working only Edge2 (and Main) and still something's wrong with the server..

What I have noticed is that on Edge2 on "top" or "htop" all process workers shows a lot of "D"state prcess (in red) which, apparently it's a I/O problem.. as I read somewhere.. 

Before I change the whole chasis, I would like to know if someone has experienced this and what pointers can I use to solve it...

Here's the main nginx.conf

```
worker_processes 16;
error_log  logs/error.log;

events {
worker_connections 1024;
}

# RTMP configuration
rtmp {
    server {
        listen 1935; # Listen on standard RTMP port
        chunk_size 4000;

        application hls {
            live on;

            #push to edge1 & edge2
            push rtmp://ip-edge1/hls;
            push rtmp://ip-edge2/hls;

            # disable consuming the stream from nginx as rtmp
            deny play all;
        }

        application hls2 {
            live on;

            #push to edge1
            push rtmp://ip-edge1/hls;

            # disable consuming the stream from nginx as rtmp
            deny play all;
        }

        application hls3 {
            live on;

            #push to edge2
			push rtmp://ip-edge2/hls;
            # disable consuming the stream from nginx as rtmp
            deny play all;
        }
    }
}

http {

    sendfile on;
    default_type application/octet-stream;

server {
    listen       8080;
    root /usr/local/nginx/www;
    index index.php;


            secure_link $arg_st,$arg_e;
            secure_link_md5 secretword$uri$arg_e;

            if ($secure_link = "") { return 403; }
            if ($secure_link = "0") { return 410; }

    location ~ \.php$ {
                try_files $uri =404;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass 127.0.0.1:9000;
                fastcgi_index index.php;

        fastcgi_param  SCRIPT_FILENAME   $document_root$fastcgi_script_name;
        fastcgi_param  MOD_X_ACCEL_REDIRECT_ENABLED on;
        include        fastcgi_params;

                      }
        }      
}

```

Here's my Edge 1 & 2 Configs (both the same)

```
worker_processes 16;
error_log  logs/error.log;

events {
worker_connections 1024;
}


# RTMP configuration
rtmp {
    server {
        listen 1935; # Listen on standard RTMP port
        chunk_size 4000;

        application hls {
            live on;
            # Turn on HLS
            hls on;
            hls_path /tmp/hls/;
            hls_fragment 4;
            hls_playlist_length 60;
            # Setup AES encryption
            hls_keys on;
            hls_key_path /tmp/hls/keys;
            hls_key_url keys/;
            hls_fragments_per_key 10;
            # disable consuming the stream from nginx as rtmp
            deny play all;
        }
    }
}

http {

#reset_timedout_connection on;
    sendfile on;
    #tcp_nopush on;
    #directio 512;
    default_type application/octet-stream;


server {
    listen       8080;
    root /usr/local/nginx/www;
    index index.php;
	access_log off;

    location ~ \.php$ {
                try_files $uri =404;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass 127.0.0.1:9000;
                fastcgi_index index.php;
				
        fastcgi_param  SCRIPT_FILENAME   $document_root$fastcgi_script_name;
        fastcgi_param  MOD_X_ACCEL_REDIRECT_ENABLED on;
        include        fastcgi_params;


        }
 }

# proxy
proxy_cache_path /home/hls use_temp_path=off keys_zone=hls:10m max_size=20g inactive=10m;
proxy_cache hls;
proxy_ignore_headers Cache-Control;

    server {
        listen 80;
        root /tmp/;
        # Disable cache
        #add_header 'Cache-Control' 'no-cache';
        index index.html;
        default_type "text/html";

        types {
            application/dash+xml mpd;
            application/vnd.apple.mpegurl m3u8;
            video/mp2t ts;
            plain/text key;
        }


        location /hls {

            secure_link $arg_st,$arg_e;
            secure_link_md5 secretword$uri$arg_e;

            if ($secure_link = "") { return 403; }
            if ($secure_link = "0") { return 410; }

            location ~* \.(ts)$ {
                        expires -1;
                }


            # Serve HLS fragments
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            root /tmp;

        add_header Cache-Control no-cache;
        add_header Access-Control-Allow-Origin *;

        }
        # Serve HLS keys securely here
        location /hls/keys {
            root /tmp;
        }
    }
}


```

**Comment by theraw** [comment]
i've been using nginx with those configs for years never had a problem with cpu you may try

```bash
user                 nginx;
worker_processes     auto;
worker_rlimit_nofile 65535;
# ====================================================================
error_log         /var/log/nginx/error.log notice;
pid               /var/run/nginx.pid;
# ====================================================================

events {
    worker_connections 65535;
    multi_accept on;
    use epoll;
}
    sendfile                       on;
    server_names_hash_bucket_size  6969;
    server_names_hash_max_size     6969;
    resolver                       1.1.1.1 8.8.8.8;
    client_body_buffer_size        128k;
    client_header_buffer_size      5M;
    client_max_body_size           1024M;
    client_body_timeout            30s;
    client_header_timeout          30s;
    keepalive_timeout              30s;
    open_file_cache                max=200000 inactive=30s;
    open_file_cache_errors         on;
    open_file_cache_min_uses       2;
    open_file_cache_valid          30s;
    reset_timedout_connection      on;
    send_timeout                   30s;
    port_in_redirect               off;
    server_name_in_redirect        off;
    server_tokens                  off;
    tcp_nodelay                    on;
    tcp_nopush                     on;
    types_hash_max_size            2048;
    real_ip_header                 X-Forwarded-For;
    real_ip_recursive              on;
    set_real_ip_from               127.0.0.1;
```

Nginx is not fully created for streaming reason which mean there is not a strict optimize for streaming in other part is still a web server, in a webserver if you don't set timouts connections will be active for more time based on nginx default timeout config and that's one of reasons that makes nginx better then apache a strict timeout config which normally closes requests and keeps server working normally if there is no timeout and requests will be open for more time it means more server resources used :)

But i hope this config helps in some way also a wrong `worker_processes` number can cause high load on cpu that's why i always use `auto` .

**Comment by misiek08** [comment]
This is not a problem with values in configuration, but in architecture. You proxy all streams from origin to edges and you transcode it twice on every edge. So every stream coming to origin server is just passed to edges and they make the hard work for every stream. (each edge does the same work, because both have to transcode rtmp to hls).

**Comment by menetas** [comment]
Yes, you are correct, mostly it is a problem from stream origins.. 
But we've figured out what was the problem specifically for this issue.
It was a faulty SSD, after provider changed the SSDs array, we had no troubles with the exact same configuration..  
Thanks for sharing all those config tips, I will make use of some of them for a better experience..

Thanks again!
