### ISSUE TITLE
exec_record_done ffmpeg -report

### ISSUE THREAD

**Issue by WJdenghuo** [arut/nginx-rtmp-module#1416]
exec_record_done ffmpeg -y -i $path -acodec libmp3lame -ar 44100 -ac 1 -vcodec libx264 $dirname/$basename.mp4 -report;

ffmpeg work error

need ffmpeg logs hava other way

**Comment by Lax** [comment]
what error message?

**Comment by WJdenghuo** [comment]
problem solved  

truncating output >file
appending output >>file
descriptor redirects like 1>&2
input <file
