### ISSUE TITLE
Some alternatives to RTMP?

### ISSUE THREAD

**Issue by SonataIX** [arut/nginx-rtmp-module#1446]
Hi, thank you for creating such a powerful module!

It has been working well for me over 2 years. But when I updated my Chrome to the newest version, I found that FP was disabled by default. Then I googled some news about FP and found the following one:

[Flash & The Future of Interactive Content](https://theblog.adobe.com/adobe-flash-update)

So I planned to find some alternatives to FP. Chrome + [hls.js](https://github.com/video-dev/hls.js) seemed to work well with the module. But its high latency is unacceptable however I changed parameters, 5s or less is OK for me.

Any advice for reducing the latency or some other alternatives? Thanks in advance.

**Comment by HeyJupiter** [comment]
If you don't use Safari, you can use [nginx-http-flv-module](https://github.com/winshining/nginx-http-flv-module) as the server and [flv.js](https://github.com/bilibili/flv.js) as the player. nginx-http-flv-module transforms RTMP streams to FLV streams over HTTP, flv.js transforms the FLV streams over HTTP to MP4 segments (fMP4) and feeds them into the HTML5 <video> element through [MSE](https://w3c.github.io/media-source) API, then browser can play the segments. Thus FP is not needed any more. The latency is about 1s ~ 3s, which meets your need.
But note you will be fucked up if you will use Safari, for it doesn't support MSE!

**Comment by SonataIX** [comment]
@HeyJupiter Awesome!
Apologize for taking so long to respond to this issue. I've tried the projects you've posted and it has worked fine. I will take some more time to test it. We won't use Safari in the near future.
Thanks very much!
