### ISSUE TITLE
Where am i doing wrong? Exec_pull not working.

### ISSUE THREAD

**Issue by inat-tv** [arut/nginx-rtmp-module#1458]
**my nginx conf** 
↓↓↓
`user  nginx;  
worker_processes  auto;  
pid /var/run/nginx.pid;

events {  
    worker_connections  1024;
}

http {  
    include      mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    sendfile        on;

    server {

        listen       80;
        server_name  localhost;

        location / {
           root   html;
           index  index.html index.htm;
           }

        location /hls {
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            root /tmp;
            add_header Cache-Control no-cache;
        }

    }
}

rtmp {  
   server {
       listen 1935;

	application mytv2 {
           live on;
           hls on;
           hls_path /tmp/hls;

	exec_pull ffmpeg -i https://canlimacbet.com/fox-com.php -c:v copy 
                     -c:a libfaac -ar 44100 -ac 1 
                     -f flv rtmp://51.158.101.157:1935/mytv2/mytv2;
       }
   }
}`

**Comment by theraw** [comment]
are you sure nginx can pull from `https://canlimacbet.com/fox-com.php`

**Comment by inat-tv** [comment]
> are you sure nginx can pull from `https://canlimacbet.com/fox-com.php`

Works with ffmpeg.

**Comment by theraw** [comment]
is this `https://canlimacbet.com/fox-com.php` part of your project? if not can you try to pull directly 
`https://foxtv-live-ad.ercdn.net/foxtv/foxtv_360p.m3u8?e=1574476077&st=LT1KXdJwUf-Bo8xi8QiYtw`

if doesn't work afaik this repo doesn't work to pull and re'stream from `.m3u8` that's why i asked you if you are sure that this repo can pull from that link because that link doesn't provide the stream directly!

**Comment by inat-tv** [comment]
> is this `https://canlimacbet.com/fox-com.php` part of your project? if not can you try to pull directly
> `https://foxtv-live-ad.ercdn.net/foxtv/foxtv_720p.m3u8?e=1574476077&st=LT1KXdJwUf-Bo8xi8QiYtw`
> 
> if doesn't work afaik this repo doesn't work to pull and re'stream from `.m3u8` that's why i asked you if you are sure that this repo can pull from that link because that link doesn't provide the stream directly!

I did the test and ffmpeg is running it. I tried m3u8 with nginx, it didn't happen again.

**Comment by inat-tv** [comment]
Solution: Install FFmpeg properly. And use exec static for such files.
