### ISSUE TITLE
exec_push ffmpeg ... srt:// >> not working

### ISSUE THREAD

**Issue by AbdulHadiParsdorfer** [arut/nginx-rtmp-module#1473]
Hi,

I tried following setup:
```
rtmp {
        server {
                listen 1935;
                chunk_size 4096;

                application live {
                        live on;
                        record off;
                        exec_push ffmpeg -i rtmp://localhost/live/$name -c copy -f mpegts srt://192.168.0.24:10000;
                }
        }
}
```
But nothing is pushed to the target. If I run the same command outside from nginx it's working fine:
`ffmpeg -i rtmp://localhost/live/test -c copy -f mpegts srt://192.168.0.24:10000`

Why is it not working?
Thank you.

**Comment by AbdulHadiParsdorfer** [comment]
Nginx could not find the ffmpeg executable. After providing the path in the nginx.conf it worked.

`exec_push /usr/local/Cellar/ffmpeg/4.2.2-with-options/bin/ffmpeg -i rtmp://localhost/live/$name -c copy -f mpegts srt://localhost:10000`

**Comment by xiafeiyue** [comment]
@AbdulHadiParsdorfer 
I tried the method you said and still cannot execute the exec_push command
exec_push /usr/local/ffmpeg4.2.2/bin/ffmpeg -nostdin -loglevel 8 -re -i rtmp://ip:1936/myapp/test -acodec copy -c:v libx264 -preset veryfast -profile:v baseline -vsync cfr -s 480x360 -b:v 400k -bufsize 400k -threads 0 -r 30 -f flv rtmp://ip:1936/myapp/test1;
