### ISSUE TITLE
[Question]do this module work with nginx prebuilt ?

### ISSUE THREAD

**Issue by maidmeow4** [arut/nginx-rtmp-module#1489]
I'm using `nginx-full` installed from `apt-get`
after installed this module using `apt-get install libnginx-mod-rtmp`, I applied my config file and nginx gives me error
```
nginx: [emerg] unknown directive "rtmp" in /etc/nginx/conf.d/rtmp.conf:1
```
do I have to compile nginx from source and add this module or I just not loading this module correctly?

**Comment by Lax** [comment]
you can build dynamic module with `--add-dynamic-module=nginx-rtmp-module` instead of static module, then add `load_module modules/ngx_rtmp_module.so` add the first line of `nginx.conf`

**Comment by jwaldmann** [comment]
I tried to build the module as describe and use it with nginx binary that comes with Fedora. I get
```
module "/usr/lib64/nginx/modules/ngx_rtmp_module.so" is not binary compatible
```
I downloaded nginx-1.16.1 sources (that's the version that Fedora uses), then this repo here, then 
```
./configure --prefix=/usr --with-http_ssl_module --add-dynamic-module=../nginx-rtmp-module
```
then `make` and copied `objs/ngx_rtmp_module.so` to the location that I wrote in the `load_module` directive.

**Comment by Lax** [comment]
> I downloaded nginx-1.16.1 sources (that's the version that Fedora uses

What is the output of `nginx -V`. 
I prefer to use the exactly same parameters as prebuilt nginx.

**Comment by jwaldmann** [comment]
Thanks,  didn't know about `nginx -V`. When I use their config, I get
```
checking for --with-ld-opt="-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-E" ... not found
```
I will try to use the standard linker and hope that it works - or I need to set up more of Fedora's dev tools. But then it's not far from actually making this (nginx-rtmp) into an rpm?

**Comment by maidmeow4** [comment]
Thanks for all the reply, I found out that I just not correctly loading this module with `nginx`.
And the `rtmp { ... }` section should be placed inside `nginx.conf`, not elsewhere.
