### ISSUE TITLE
Intermittent ffmpeg starting conversion

### ISSUE THREAD

**Issue by wd69** [arut/nginx-rtmp-module#1495]
For 3 years I have had success with NGINX-RTMP converting my 70 channels to medium and low quality via NGINX-RMP when a source stream starts and gets sent to NGINX.

Lately this has become very unreliable.  Sometimes the conversion starts, sometimes it does not. FFMPEG hangs.

I can restart the source stream and it *might* start ffmpeg conversion, it might not. I can retry this a few times and eventually it will work.  

ffmpeg log: 

 /bin/ffmpeg -i rtmp://localhost:1935/source/channel1 -c:v libx264 -vf scale=568:324,setdar=dar=16/9 -maxrate 900k -bufsize 900k -preset veryfast -profile:v baseline -level 3.1 -r 25 -g 50 -c:a libfdk_aac -b:a 64k  -f flv rtmp://127.0.0.1:1936/tvmed?rtmpauth=user:pass/channel1
ffmpeg version N-96256-gd111a41 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-39)
  configuration: --prefix=/root/ffmpeg_build --extra-cflags=-I/root/ffmpeg_build/include --extra-ldflags='-L/root/ffmpeg_build/lib -ldl' --bindir=/root/bin --pkg-config-flags=--static --enable-gpl --enable-nonfree --enable-libfdk_aac --enable-libx264
  libavutil      56. 38.100 / 56. 38.100
  libavcodec     58. 65.102 / 58. 65.102
  libavformat    58. 35.101 / 58. 35.101
  libavdevice    58.  9.102 / 58.  9.102
  libavfilter     7. 70.101 /  7. 70.101
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100

Please do you have any idea what might be stopping ffmpeg from getting the stream from NGINX sometimes? The server has lots of free resources. 

Thank you

**Comment by wd69** [comment]
Never mind. After a reboot everything is working fine. 
Bit scary, reliability shouldn't deteriorate like this. unsure why ffmpeg would only work once in a while until I had rebooted. Very strange.

**Comment by Hauham** [comment]
Hi

**Comment by Hauham** [comment]
Hi @wd69 
It seems to be same issue occur to me.
My hls stream work fine but sometime it's not (self-lost video)
I try to restart nginx and everything back to the way it was.
I don't know what the happen?

Have you have any way to fix it ? 
please help me if you can.
