### ISSUE TITLE
Count HLS viewers

### ISSUE THREAD

**Issue by svprdga** [arut/nginx-rtmp-module#1524]
I am trying to fetch the actual number of HLS viewers, I have tried [this](https://github.com/arut/nginx-rtmp-module/wiki/Getting-number-of-subscribers) solution but it is not giving me the real number. 

Is there any 'good' way to achieve that? Thanks.

**Comment by TheRealMattLear** [comment]
The stats only reports RTMP connections and not HLS connections.

**Comment by svprdga** [comment]
I want the current number of HLS connections in order to limit the viewer number, is there any other way to achieve that?

**Comment by waster** [comment]
You can implement some logic this with openresty and redis for example, it should be based on some ids for clients.

**Comment by svprdga** [comment]
Yes, I found that the only way to count viewers (and to manage them) is via a custom proxy server.
