### ISSUE TITLE
Redirected stream name - notify push error

### ISSUE THREAD

**Issue by 0xARK** [arut/nginx-rtmp-module#1544]
HI !

I want to change the name of my stream by doing a redirection to my stream server with php, like this :
```
header("Location: rtmp://127.0.0.1:1936/app/newName");
```
However, when the redirection is done, I get this as an error :
```
2020/07/18 20:38:23 [error] 9463#9463: *129 notify: push 'oldName' to 'rtmp://127.0.0.1:1936/app/newName', client: 127.0.0.1, server: 0.0.0.0:1935
```

The redirection works, because i can play the stream provided by the stream server, but i want to fix this error on the logs. Please, anyone can help me ?
Thank you in advance !

Regards, 
Mateo

**Comment by winshining** [comment]
You can find it on line 1054 in ngx_rtmp_notify_module.c.
By the way, log level on line 1071 should be NGX_LOG_ERR.

**Comment by 0xARK** [comment]
You advise me to make this error no longer appear in the logs by modifying the file if I understand correctly ? 

I just wanted to fix this error in a normal way, because if it appears, there's a reason, isn't there ? Unless it's not an error but only an information ?

**Comment by winshining** [comment]
You are right. It's not an error.

**Comment by 0xARK** [comment]
Oh okay thanks.

So I have to change what to remove this info from the logs ?

**Comment by winshining** [comment]
Change NGX_LOG_ERR to NGX_LOG_INFO or NGX_LOG_DEBUG_RTMP.
