### ISSUE TITLE
hls_path not working on secondary drive

### ISSUE THREAD

**Issue by akhilleusuggo** [arut/nginx-rtmp-module#1554]
I'm setting the `hls_path /mnt/MYSSD/HLS/live;` , the ts files are generated , but the player can not read them . Error 404 
When I get back the to `/HLS/live` ( on primary drive it works )

I'm not sure if it's a permission issue . I've tried `chmod 777 -R * on /mnt/MYSSD` , and `chown www-data:www-data -R *` , but no luck . Any tip ? 

Appreciate it !

**Comment by techiespace** [comment]
@akhilleusuggo can you please share how did you fix this? I'm facing a similar issue. The ts files are generated but I get 404 while trying to play the m3u8 url in VLC.

**Comment by akhilleusuggo** [comment]
Hello , this happened like a year ago. Can remember exactly how but ;

- Make sure that apache and nginx can access to the folder ; Permissions
- Make sure to change the directive on the plugin, to where you have mounted the drive.
- Make sure to change that directive on nginx.conf configuration file.

If I recall correctly, this fixed the issue.
