### ISSUE TITLE
A way to set 'push' origin IP address

### ISSUE THREAD

**Issue by dalvlex** [arut/nginx-rtmp-module#1567]
Is there a way to set push origin IP address? Something similar to proxy_bind

For example I have three public IP's on a streaming server, say 192.168.1.5, 192.168.1.9 and 192.168.1.13 (I'm going to use NAT IPs just as an example).

The default eth0 is 192.168.1.5
What I would like to do is have nginx+rtmp module receive OBS data on 192.168.1.9 and push it to an external server from the same origin IP 192.168.1.9.
And do the same thing with 192.168.1.13, receive rtmp ON it, and push to an external server FROM it.

Right now I am receiving the OBS stream on 192.168.1.9:12002, but when pushing to rtmp://some-stream-consumer.com/live/my-key the stream goes out through the source IP 192.168.1.5
```
rtmp {
        server {
                listen 192.168.1.9:12002;
                chunk_size 4096;

                application bob {
                        live on;
                        record off;
                        deny play all;
                        meta copy;
                        on_publish http://192.168.1.5:80/rtmp_authentication.php;
                        push rtmp://some-stream-consumer.com/live/my-key
                }
        }
}
```

I have no trouble doing a curl `curl --interface 192.168.1.9 http://example.com/`, this works, there is no routing issue or something like that. Just that this option is not available in NginX or RTMP module.

Does anybody have an idea about this?

LE: why do I want to do this? Currently I have a small pool of IPv4 addresses and each stream has it's own source (requirements of the streaming consumer service), and now instead of using multiple OBS and or splitter in the streaming PCs, I want to receive a single OBS stream per PC into a streaming box with all these IPs and push it to it's corresponding external service.

**Comment by teh-random-name** [comment]
I'm not sure if this module can bind to an interface like you want but if you have build Nginx `--with-stream` you can use [ngx_stream_proxy_module](http://nginx.org/en/docs/stream/ngx_stream_proxy_module.html) with the [proxy_bind](http://nginx.org/en/docs/stream/ngx_stream_proxy_module.html#proxy_bind) directive to achieve that.

The config would be something like this
```
stream {
  server {
    listen 127.0.0.1:9000;
    proxy_bind 192.168.1.9;
    proxy_pass rtmp://some-stream-consumer.com/live/my-key;
  }
}

<snip>

rtmp {
  server {
    listen 192.168.1.9:12002;
    chunk_size 4096;

    application bob {
      live on;
      record off;
      deny play all;
      meta copy;
      on_publish http://192.168.1.5:80/rtmp_authentication.php;
      push rtmp://127.0.0.1:9000;
    }
  }
}
```

**Comment by dalvlex** [comment]
@teh-random-name this is the tested example of what you recommended, and it works with very little changes! Thank you very much!

Yes, a recompile --with-stream was needed

```
stream {
  server {
    listen 127.0.0.1:9000;
    proxy_bind 192.168.1.9;
    proxy_pass external-stream-consumer.com:1935;
  }
}

rtmp {
  server {
    listen 192.168.1.9:12002;
    chunk_size 4096;

    application bob {
      live on;
      record off;
      deny play all;
      meta copy;
      on_publish http://192.168.1.5:80/rtmp_authentication.php;
      push rtmp://127.0.0.1:9000/stream-app/my-key;
    }
  }
}
```

Where 192.168.1.5 is the default IP address of the server, which in this case handles some RTMP authentication too.
And 192.168.1.9 is the secondary IP used for IN/OUT RTMP streaming.
