### ISSUE TITLE
local ffmpeg = Input/output error

### ISSUE THREAD

**Issue by aleb71** [arut/nginx-rtmp-module#158]
Ubuntu 10.04 LTS
nginx-1.2.7
./configure --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --pid-path=/var/run/nginx.pid --add-module=../nginx-rtmp-module --with-debug

nginx.conf
# user  nobody;

worker_processes  1;
error_log  /var/log/nginx/error.log;
events {
    worker_connections  1024;
}
rtmp_auto_push on;
rtmp {
    server {
        listen 1935;
        access_log  /var/log/nginx/access.log;
        chunk_size 4000;
        # TV mode: one publisher, many subscribers
        application mytv {
            # enable live streaming
            live on;
            allow publish all;
            allow play all;  
        }

ffmpeg create as described in https://ffmpeg.org/trac/ffmpeg/wiki/UbuntuCompilationGuideLucid

Strange problem:
If I am try stream from any different (non-local) server - all ok.
ffmpeg -i udp:233.163.114.53:5106 -s 512x288 -aspect 16:9 -profile baseline -b 500k -vcodec libx264 -acodec libmp3lame -ar 44100 -ab 64k -ac 2 -deinterlace -coder 0 -f flv 'rtmp://ip_of_nginx:1935/mytv/ flashver=FMLE/3.0\20(compatible;\20FMSc/1.0) live=true playpath=live_test' 

[libx264 @ 0x2585d80] 264 - core 125 r2 d9d2288 - H.264/MPEG-4 AVC codec - Copyleft 2003-2012 - http://www.videolan.org/x264.html - options: cabac=0 ref=3 deblock=1:0:0 analyse=0x1:0x111 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=24 lookahead_threads=4 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=500 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, flv, to 'rtmp://***:1935/mytv/ flashver=FMLE/3.0\20(compatible;\20FMSc/1.0) live=true playpath=live_test':
  Metadata:
    encoder         : Lavf54.21.100
    Stream #0:0: Video: h264 ([7][0][0][0] / 0x0007), yuv420p, 512x288 [SAR 1:1 DAR 16:9], q=-1--1, 500 kb/s, 1k tbn, 25 tbc
    Stream #0:1: Audio: mp3 ([2][0][0][0] / 0x0002), 44100 Hz, stereo, s16, 64 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg2video -> libx264)
  Stream #0:1 -> #0:1 (mp2 -> libmp3lame)
Press [q] to stop, [?] for help
frame=  179 fps= 67 q=32766.0 Lsize=     507kB time=00:00:07.65 bitrate= 542.6kbits/s  
video:439kB audio:60kB subtitle:0 global headers:0kB muxing overhead 1.697551%

If I am try stream to any server (wowza) from local server (nginx server) all ok.

ffmpeg -i udp:233.163.114.53:5106 -s 512x288 -aspect 16:9 -profile baseline -b 500k -vcodec libx264 -acodec libmp3lame -ar 44100 -ab 64k -ac 2 -deinterlace -coder 0 -f flv 'rt/ip_of_wowza:1935/live/ flashver=FMLE/3.0\20(compatible;\20FMSc/1.0) live=true playpath=live_test'  

[libx264 @ 0x29e8ce0] 264 - core 130 r2 c832fe9 - H.264/MPEG-4 AVC codec - Copyleft 2003-2013 - http://www.videolan.org/x264.html - options: cabac=0 ref=3 deblock=1:0:0 analyse=0x1:0x111 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=500 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, flv, to 'rtmp://****:1935/live/ flashver=FMLE/3.0\20(compatible;\20FMSc/1.0) live=true playpath=live_test':
  Metadata:
    encoder         : Lavf55.0.100
    Stream #0:0: Video: h264 ([7][0][0][0] / 0x0007), yuv420p, 512x288 [SAR 1:1 DAR 16:9], q=-1--1, 500 kb/s, 1k tbn, 25 tbc
    Stream #0:1: Audio: mp3 ([2][0][0][0] / 0x0002), 44100 Hz, stereo, s16p, 64 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg2video -> libx264)
  Stream #0:1 -> #0:1 (mp2 -> libmp3lame)
Press [q] to stop, [?] for help
Failed to update header with correct duration.e=00:00:06.79 bitrate= 351.1kbits/s  
[flv @ 0x2a7e7c0] Failed to update header with correct filesize.
frame=  149 fps= 79 q=-2.0 Lsize=     419kB time=00:00:07.52 bitrate= 456.8kbits/s  
video:356kB audio:55kB subtitle:0 global headers:0kB muxing overhead 1.821196%

But. 
If I am try stream from local server to local nginx:

ffmpeg -i udp:233.163.114.53:5106 -s 512x288 -aspect 16:9 -profile baseline -b 500k -vcodec libx264 -acodec libmp3lame -ar 44100 -ab 64k -ac 2 -deinterlace -coder 0 -f flv 'rtmp://127.0.0.1:1935/mytv/ flashver=FMLE/3.0\20(compatible;\20FMSc/1.0) live=true playpath=live_test'

ffmpeg version git-2013-03-23-785b849 Copyright (c) 2000-2013 the FFmpeg developers
  built on Mar 23 2013 18:44:11 with gcc 4.4.3 (Ubuntu 4.4.3-4ubuntu5.1)
  configuration: --enable-gpl --enable-libfaac --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-nonfree --enable-version3
  libavutil      52. 22.101 / 52. 22.101
  libavcodec     55.  1.100 / 55.  1.100
  libavformat    55.  0.100 / 55.  0.100
  libavdevice    55.  0.100 / 55.  0.100
  libavfilter     3. 48.100 /  3. 48.100
  libswscale      2.  2.100 /  2.  2.100
  libswresample   0. 17.102 /  0. 17.102
  libpostproc    52.  2.100 / 52.  2.100
[mpegts @ 0x33ca360] Unable to seek back to the start
[mpeg2video @ 0x33f0e20] Invalid frame dimensions 0x0.
    Last message repeated 26 times
[mpegts @ 0x33ca360] max_analyze_duration 5000000 reached at 5016000 microseconds
[mpegts @ 0x33ca360] Estimating duration from bitrate, this may be inaccurate
Input #0, mpegts, from 'udp:233.163.114.53:5106':
  Duration: N/A, start: 61190.166156, bitrate: 192 kb/s
  Program 5300 
    Metadata:
      service_name    : ?KHL
      service_provider: ?N3
    Stream #0:0[0x141]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p, 720x576 [SAR 64:45 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1[0x191]: Audio: mp2 ([4][0][0][0] / 0x0004), 48000 Hz, stereo, s16p, 192 kb/s
Please use -profile:a or -profile:v, -profile is ambiguous
Please use -b:a or -b:v, -b is ambiguous
rtmp://127.0.0.1:1935/mytv/ flashver=FMLE/3.0\20(compatible;\20FMSc/1.0) live=true playpath=live_test: Input/output error

nginx   29461   root    7u  IPv4 186593      0t0  TCP *:1935 (LISTEN)
nginx   29461   root    8u  IPv4 186594      0t0  TCP *:http-alt (LISTEN)
nginx   29462 nobody    7u  IPv4 186593      0t0  TCP *:1935 (LISTEN)
nginx   29462 nobody    8u  IPv4 186594      0t0  TCP *:http-alt (LISTEN)

iptables -L -n -v
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Howto troubleshoot this problem.
Thanks.

**Comment by rahul1001knp** [comment]
I am getting input/output error when I am using FFmpeg. Ngnix is working fine status come ok for NGINX and snapped code is below please help me out

./stream1.sh

ffmpeg -re -i sample.mp4 -vcodec copy -loop -1 -c:a aac -b:a 160k -ar 44100 -strict -2 -f flv rtmp:198.168.0.0/live/1234567890
ffmpeg version 2.8.15 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-36)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' --extra-ldflags='-Wl,-z,relro ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-gnutls --enable-ladspa --enable-libass --enable-libcdio --enable-libdc1394 --enable-libfdk-aac --enable-nonfree --disable-indev=jack --enable-libfreetype --enable-libgsm --enable-libmp3lame --enable-openal --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libx264 --enable-libx265 --enable-libxvid --enable-x11grab --enable-avfilter --enable-avresample --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-runtime-cpudetect
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'sample.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.40.101
  Duration: 00:45:30.48, start: 0.000000, bitrate: 525 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 391 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler

    rtmp:198.168.0.0/live/1234567890: Input/output error
