### ISSUE TITLE
Some one please explain these variables

### ISSUE THREAD

**Issue by jengajenga** [arut/nginx-rtmp-module#1583]
$name - stream name
$app - application name
$addr - client address
$flashver - client flash version
$swfurl - client swf url
$tcurl - client tc url
$pageurl - client page url

Is the client address the IP address of the streamer from the computer he is using to stream?

**Comment by jengajenga** [comment]
no one cares??

**Comment by cmnajs** [comment]
What are you trying to achieve? You can read more about rtmp protocol on wiki. If you want to stream using something like FFmpeg then a command like following can work.

`ffmpeg -re -i file.flv -acodec copy -vcodec copy -f flv rtmp://localhost/live/test`

**Comment by jengajenga** [comment]
> What are you trying to achieve? You can read more about rtmp protocol on wiki. If you want to stream using something like FFmpeg then a command like following can work.
> 
> `ffmpeg -re -i file.flv -acodec copy -vcodec copy -f flv rtmp://localhost/live/test`

i already know how to do this. I want to know what $clientaddr is. Is it the ip address of the server? is it the ip of the computer sending the stream? is it even an ip address or is it something else?

**Comment by cmnajs** [comment]
I dumped these variables on `on_play` using docker setup. It is the client IP sending the stream.

```
Array
(
    [app] => live
    [flashver] => LNX 9,0,124,2
    [swfurl] => 
    [tcurl] => rtmp://localhost:1935/live
    [pageurl] => 
    [addr] => 172.17.0.1
    [clientid] => 11
    [call] => play
    [name] => test
    [start] => 4294965296
    [duration] => 0
    [reset] => 0
)
```

**Comment by jengajenga** [comment]
> I dumped these variables on `on_play` using docker setup. It is the client IP sending the stream.
> 
> ```
> Array
> (
>     [app] => live
>     [flashver] => LNX 9,0,124,2
>     [swfurl] => 
>     [tcurl] => rtmp://localhost:1935/live
>     [pageurl] => 
>     [addr] => 172.17.0.1
>     [clientid] => 11
>     [call] => play
>     [name] => test
>     [start] => 4294965296
>     [duration] => 0
>     [reset] => 0
> )
> ```

Brother, thank you very much for your assistance. This is exactly what I needed to know. Thumbs up!!
