### ISSUE TITLE
exec_push/exec ffmpeg Invalid execution command

### ISSUE THREAD

**Issue by xiafeiyue** [arut/nginx-rtmp-module#1589]
linux environment：
My ffmpeg path is /usr/local/ffmpeg-4.2.2
My nginx path is /usr/local/nginx-1.18.0
When I execute the following command, nginx does not execute it.
exec_push /usr/local/ffmpeg -nostdin -loglevel 8 -re -i rtmp://ip:1936/myapp/$name -acodec copy -c:v libx264 -preset veryfast -profile:v baseline -vsync cfr -s 480x360 -b:v 400k -bufsize 400k -threads 0 -r 30 -f flv rtmp://ip:1936/myapp/test;

**Comment by gy2331314** [comment]
Hi，man!
There is a problem with the path in your configuration file.
Your ffmpeg path is /usr/local/ffmpeg-4.2.2.
But exec_push /usr/local/ffmpeg is wrong.
So，there are two ways to solve your problem. Either, you need to add ffmpeg to the system environment variable. Or, you need to modify  your configuration file after exec_push.
