### ISSUE TITLE
RTMPS support for Facebook Live API's Requirement

### ISSUE THREAD

**Issue by C74K** [arut/nginx-rtmp-module#1605]
Facebook is using RTMPS Only From far time.

we need suport for RTMPS by module

**Comment by timololipop** [comment]
Just use Stunnel^^

**Comment by C74K** [comment]
i try but dont work

**Comment by timowevel03** [comment]
Can you send your NGINX and Stunnel config here?

**Comment by C74K** [comment]
i removed it from my vps to hard to setup.

**Comment by venuzestiot** [comment]
Hi 
timowevel1,

i am trying to setup RTMPS live stream from edge device, but i am failing on that.
i am using nginx and rtmp but it is working but rtmps is not working for me
