### ISSUE TITLE
Access stats through file system?

### ISSUE THREAD

**Issue by Rakinare** [arut/nginx-rtmp-module#1607]
I am trying to parse from the XML file for /stat in a C# application hosted on the same machine as the nginx server. 
My problem is that I am getting a connection refused exception in my application.
Do you happen to know if there is a way to get access to the stat.xml from a C# application or if the stat.xml is located anywhere so I could access it normally through the file system?

Using Windows 10

Regards,
Rakinare

**Comment by Itsindigo** [comment]
Hey @Rakinare -- did you find a solution to this?

**Comment by Rakinare** [comment]
Heyho @Itsindigo  , yup I found one! Just been parsing the html, I found the correct one but would have to look for how I did it, since I haven't been working with it in ages.
