### ISSUE TITLE
Why console print "rtmp" directive is not allowed?

### ISSUE THREAD

**Issue by yidezhangfei** [arut/nginx-rtmp-module#1610]
How to soled this issue?  Thanks all!

OS: Centos 7
configure arguments: --prefix=/usr/local/nginx --modules-path=/usr/local/libexec/nginx --add-module=../nginx-rtmp-module --with-http_ssl_module.

compile and install has no errors

**Comment by Bingqiang-Jing** [comment]
Maybe the "rtmp" directvie's location is not right,  it must locate in root context of the config file.

**Comment by yidezhangfei** [comment]
> Maybe the "rtmp" directvie's location is not right, it must locate in root context of the config file.
> relevant source code from ngx_conf_file.c as below:
> 
> ```
> if (found) {
>         ngx_conf_log_error(NGX_LOG_EMERG, cf, 0,
>                            "\"%s\" directive is not allowed here", name->data);
> 
>         return NGX_ERROR;
> }
> ```

wow! Thank you very much, it works!
