### ISSUE TITLE
Reloading stats-webpage sometimes returns no stream-data.

### ISSUE THREAD

**Issue by DigibitDK** [arut/nginx-rtmp-module#1626]
Sometimes when I load the RTMP stats-page, it returns with a webpage with no stream-data. All applications is there, and everything 'seems' as it should be. But even if there are streams using the server, it doesn't show. If I reload it might show correctly. 

Its easy to reproduce by reloading the stats-page like 1-3 times a second, with a stream running. From time to time, you will see no active streams :/

NGINX: 1.21.1
RTMP: 1.2.2

**Comment by DigibitDK** [comment]
My mistake (Nginx-config thing ...)

**Comment by edinsof** [comment]
how to solve? i have same problem
