### ISSUE TITLE
Обрыв соединения

### ISSUE THREAD

**Issue by edusgroup** [arut/nginx-rtmp-module#164]
Добрый день Роман!

Долго искал баг, но нашёл. В целом nginx обрывает соединение после n количества времени.
Исходные данные
Публикую поток с помощью FMLE
конфиг nginx 1.2.7

<pre lang="javascript"><code>
rtmp {
    server {
        listen 1935;

        application live {
            live on;
            on_play http://xxxxxxx.ru:8483/?action=play;
            on_play_done http://xxxxxx.ru:8483/?action=play_end;
        }
    }
}
</code></pre>

Первое что бросилось в глаза, это то, что в статистике иногда исчезают символы
![nginx-error](https://f.cloud.github.com/assets/1720851/325630/e803e260-9b10-11e2-9783-b59734e15c1c.png)

Далее было, сложно но выловил баг, после n количества минут, nginx уничтожает поток, при этом не закрывает соединение, т.е. nginx держит соединение, но не публикует

статистика
![nginx_log](https://f.cloud.github.com/assets/1720851/325646/3b8d9f16-9b11-11e2-8941-c35b55032a60.png)

лог fmle
![nginx_fms](https://f.cloud.github.com/assets/1720851/325650/49d1393e-9b11-11e2-8af3-485ab9e70668.png)

в error.log попадает следующее

<pre lang="javascript"><code>
2013/04/02 01:02:54 [info] 17224#0: *823 client connected 'xxx.xx.xxx.xxx'
2013/04/02 01:02:54 [info] 17224#0: *823 connect: app='live' args='' flashver='FMLE/3.0 (compatible; FMSc/1.0)' swf_url='rtmp://xxx.xxx.xxx.xxx/live' tc_url='rtmp://xxx.xxx.xxx.xxx/live' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: xxx.xxx.xxx.xxx, server: 0.0.0.0:1935
2013/04/02 01:02:54 [info] 17224#0: *823 createStream, client: xxx.xxx.xxx.xxx, server: 0.0.0.0:1935
2013/04/02 01:02:54 [info] 17224#0: *823 publish: name='test' args='videoKeyframeFrequency=5&totalDatarate=564' type=live silent=0, client: xxx.xxx.xxx.xxx, server: 0.0.0.0:1935
2013/04/02 01:04:41 [info] 17224#0: *823 recv() failed (104: Connection reset by peer), client: xxx.xxx.xxx.xxx, server: 0.0.0.0:1935
2013/04/02 01:04:41 [info] 17224#0: *823 disconnect, client: xxx.xxx.xxx.xxx, server: 0.0.0.0:1935
2013/04/02 01:04:41 [info] 17224#0: *823 deleteStream, client: xxx.xxx.xxx.xxx, server: 0.0.0.0:1935
</code></pre>

Если вам будет удобно, могу дать ssh доступ на сервер

**Comment by boburrr** [comment]
Как вы решили это проблема, сейчас у нас тоже Обрыв соединения но не могу решить. Сервер Service package: Config 54 / HP G9 / Intel 1xE5-2630v4 / 32GB RAM DDR3 / 2x2­40GB SSD / HW RAID / 1x10GE Port /
