### ISSUE TITLE
HLS: generates u3u8 files "on fly"?

### ISSUE THREAD

**Issue by WinterSilence** [arut/nginx-rtmp-module#1670]
If steam `rtmp://stream.site.ru/hls/streamKey-0.ts`(`/tmp/hls`), then what's URL `streamKey.m3u8`?

**Comment by Vanadiom** [comment]
Actually, the streamKey.m3u8 is the 'lexicon'
You want to send that, that is the stream.
`rtmp://stream.site.ru/hls/streamKey.m3u8`
The .ts files are smaller parts of the stream.

**Comment by NMSAzulX** [comment]
@Vanadiom Hello! Do you know how to solve cross-domain problems? I'm using HLS live. 
![image](https://user-images.githubusercontent.com/16236903/197388997-1a172428-9b48-4d4b-8c7f-09a14a8854a9.png)

**Comment by Vanadiom** [comment]
> @Vanadiom Hello! Do you know how to solve cross-domain problems? I'm using HLS live. 
> 
> ![image](https://user-images.githubusercontent.com/16236903/197388997-1a172428-9b48-4d4b-8c7f-09a14a8854a9.png)
> 

Nope sorry, my knowledge is a puddle, it's there, but it's not very deep (:

**Comment by NMSAzulX** [comment]
@Vanadiom Thank you for your reply. It looks like I need to launch an issue, which is a headache.

**Comment by NMSAzulX** [comment]
@Vanadiom  I soved this problem. Just use http protocol url...
