### ISSUE TITLE
HLS Authorization  allow/deny Dynamic ip?

### ISSUE THREAD

**Issue by Liltech2** [arut/nginx-rtmp-module#1674]
How can I do authorization on my streams? Like pay per view? I see there's allow/deny for an ip address. How can I do this for for different ip's? Would it be the user flow:
user pays to access stream
user is added to subnet  to view stream

**Comment by moerradi** [comment]
for HLS output you can use NGINX authentication to allow or deny users playing your livestream, you can create a route in your API that parses the cookie you are using i assume for your user authentication and responds with either 200 if he is allowed to play the video or a  (4xx) code example : (401) to not allow the user to play, using only IP restriction is not the optimal approach for authorization cookies are.
you can refer to this link for further info about nginx auth : 
https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-subrequest-authentication/

**Comment by Liltech2** [comment]
Thank you!! That added alot of clarity for me.
