### ISSUE TITLE
Nginx Open source dynamic stream links

### ISSUE THREAD

**Issue by dangolbeeker** [arut/nginx-rtmp-module#1675]
Is it possible to create stream links dynamically? Such as a planned webinar a user within my app creates?
Or should I just  a bunch of rtmp links and assign them  when the user  creates a webinar.

**Comment by moerradi** [comment]
It seems like the on publish directive is what you are looking for, you can set up a callback api using a language of your choice : node+express, python+flask....
The method should be post, you are hoing to receive the stream key of the person who is trying to stream under request->body->name you can then check the database if the name is valid and authenticate based on the response, if you want to let the person stream return 200, if not return a 40x code

**Comment by dangolbeeker** [comment]
Thanks!!
