### ISSUE TITLE
Problems receiving live stream

### ISSUE THREAD

**Issue by streamer45** [arut/nginx-rtmp-module#17]
Hello, 

I'm having problems when connecting to a live stream I'm publishing on live app.
The log: http://paste.ubuntu.com/1051170/
I have an ffmpeg instance which gets the stream and pushes it elsewhere and then I have a flashplayer which connects to the app to watch the live stream.
Well, after some time if I try to reconnect I get no video at all and those errors.
Any idea? Thanks :)

**Comment by trinity0091** [comment]
ffmpeg running in terminal (using nginx as rtmp server), 
But it is not running in nginx exec ffmpeg command.

--- Actually i am a beginner, Please help me how can execute ffmpeg within the nginx server (tried config provided in README).
