### ISSUE TITLE
./configure: error: no /usr/build/ngnix-rtmp-module/config was found

### ISSUE THREAD

**Issue by Abner-0311** [arut/nginx-rtmp-module#185]
Hi,
  I met the problem when building nginx on my Mac Pro.
The nginx version I got is 1.4.1, and the ngnix-rtmp-module is  the latest from git.
Please kindly remind me what I may miss in the build steps.

Thanks
# ./configure --add-module=/usr/build/ngnix-rtmp-module --with-http_ssl_module

adding module in /usr/build/ngnix-rtmp-module
./configure: error: no /usr/build/ngnix-rtmp-module/config was found

**Comment by mrsuh** [comment]
check permissions of file "config"

**Comment by terbooter** [comment]
I am using docker container for that
https://github.com/terbooter/LVK-server/blob/master/Dockerfile

**Comment by Onyx808** [comment]
Perhaps you not seeing the full path, go inside the module folder and to "readlink -f config" without the "" that should give you the full path to the config file, make sure you don't add config when adding the module just the path to the folder.

**Comment by hellomahao** [comment]
You need add the prefix path where you installed. such as --prefix=/usr/local/nginx 
I solved the same problem by doing this.
