### ISSUE TITLE
NAL AUD bug in HLS - with solution

### ISSUE THREAD

**Issue by jettoblack** [arut/nginx-rtmp-module#201]
Hello, I think I found a small bug.  The effect of this bug is that CEA-608 closed captions in the source video (sent as NAL type 0x6, SEI message type 0x4 data) do not work on iOS players, although they do work in VLC.

H264 NAL AUD (NAL type 0x9) should be the first NAL in a packet.  If the source packet contains SEI messages (NAL type 0x6) then nginx-rtmp-module is inserting the AUD after the NAL SEI message instead of before.

E.g.
Correct NAL sequence:
00 00 00 01 09 f0 00 
00 00 01 27 4d 40 29 a9 18 0a 00 b7 60 0d 40 40 40 6d b0 ad 7b df 01 00 
00 00 01 28 de 09 c8 
00 00 01 06 00 07 82 22 e0 00 00 03 00 40 80 
00 00 01 06 05 11 03 87 f4 4e cd 0a 4b dc a1 94 3a c3 d4 9b 17 1f 00 80 
00 00 01 06 04 11 b5 00 31 47 41 39 34 03 c2 ff fc 80 80 fc 80 80 ff 80 
00 00 01 25 b8 20 20 21 5f ff f8 7a 28 00 08 a2 fb ef be fb ef be fb ef ...

Sequence generated by nginx-rtmp-module:
00 00 00 01 06 00 07 82 22 e0 00 00 03 00 40 80 
00 00 01 06 05 11 03 87 f4 4e cd 0a 4b dc a1 94 3a c3 d4 9b 17 1f 00 80 
00 00 01 06 04 11 b5 00 31 47 41 39 34 03 c2 ff fc 80 80 fc 80 80 ff 80 
*00 00 00 01 09 f0 00 
00 00 01 27 4d 40 29 a9 18 0a 00 b7 60 0d 40 40 40 6d b0 ad 7b df 01 00 
00 00 01 28 de 09 c8 
00 00 01 25 b8 20 20 21 5f ff f8 7a 28 00 08 a2 fb ef be fb ef be fb ef ...

Note that although all the NAL data is the same, the order is different.  AUD (type 0x9) occurs in the middle of the packet instead of the beginning, causing some decoders to ignore the SEI message data that was sent before the AUD.

Solution:

Simply fix this case statement in ngx_rtmp_hls_video() at line 1522:

```
    if (!aud_sent) {
        switch (nal_type) {
            case 1:
            case 5:
            case 6:
                if (ngx_rtmp_hls_append_aud(s, &out) != NGX_OK) {
                    ngx_log_error(NGX_LOG_ERR, s->connection->log, 0,
                                  "hls: error appending AUD NAL");
                }
            case 9:
                aud_sent = 1;
                break;
        }
    }
```

Note the case for NAL type 6 (SEI message) was added so that AUD is inserted before rather than after.

Please let me know if you have any questions or comments, thanks.

**Comment by avbagno** [comment]
Hi!
I have currently the same problem and I run rtmp module with this fix. I would be really appreciate if you could tell me what I'm doing wrong.
I use next ffmpeg command:
-  fmpeg25 -i rtmp://my_server_ip/my_stream -codec: copy -f flv -bsf:a aac_adtstoasc rtmp://localhost:1935/myapp/wowza
I open link  http://my_ip:8888/hls/wowza.m3u8 in safari and I can't see closed captions. With VLC it's all ok with captions.
(I've also checked ios settings : General > Accessibility > Subtitles & Captioning, and they turned on).
Thanks.
