### ISSUE TITLE
On_publish only one parameter is passed

### ISSUE THREAD

**Issue by SkeLLLa** [arut/nginx-rtmp-module#212]
I have nginx 1.4.1 with rtmp module 0.9.20. Publish is configured in such way:

```
application show {
    live on;

    allow publish all;
    on_publish http://backend:80/show/onpublish.ashx;

    hls on;
    hls_path /var/tmp/nginx-show;
    hls_fragment 10s;
}
```

On test page I use sample RTMP publisher that is configured to pass some needed vars to backend server:

```
      var flashVars = {
            streamer: 'rtmp://example.com/show',
            file: 'test?t=c333f88e2c99539a8a005040f779b99aa76cac1c&s=1e39497d-c6a3-4400-be12-7c8e2d0c3731&u=0'
        };
        swfobject.embedSWF("../swf/publisher.swf", "rtmp-publisher", "500", "400", "9.0.0", null, flashVars);
```

And in onpublish.ashx page I receive only first argument. In example above I receive only `t` param and `s` param will be empty. If I change them (`s` goes first) I receive only `s`.

In server logs there is also only one param in `args` variable.

**Comment by heguangze** [comment]
Can The maximum length of RTMP not exceed 286 characters?
