### ISSUE TITLE
Secure links nginx with rtmp not working Input/output error

### ISSUE THREAD

**Issue by Dilipparmar** [arut/nginx-rtmp-module#221]
i am trying to play flash video via rtmp nginx secure link
http://nginx-rtmp.blogspot.in/2013/06/secure-links-in-nginx-rtmp.html?q=secure

but not working can you please help me to solve this
all flash video in /var/video path

my nginx -V output
nginx version: nginx/1.2.4
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-3) (GCC)
TLS SNI support enabled
configure arguments: --add-module=/home/rtmp/nginx-rtmp-module --with-http_secure_link_module

my nginx.conf
# user  nobody;

worker_processes  1;

error_log  logs/error.log debug;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

```
sendfile        on;
keepalive_timeout  65;

server {
    listen       8081;
    server_name  localhost;
    root /var/video;

    # sample handlers
    location /on_play {
        # set connection secure link
        secure_link $arg_st,$arg_e;
        secure_link_md5 mysecretkey$arg_app/$arg_name$arg_e;

        # bad hash
        if ($secure_link = "") {
            return 501;
        }

        # link expired
        if ($secure_link = "0") {
            return 502;
        }

        return 200;
    }
    #location /on_publish {
    #    return 201;
    #}

    #location /vod {
    #    alias /var/videos;
    #}

    # rtmp stat
    location /stat {
        rtmp_stat all;
        rtmp_stat_stylesheet stat.xsl;
    }
    location /stat.xsl {
        # you can move stat.xsl to a different location
        root /usr/build/nginx-rtmp-module;
    }

    # rtmp control
    location /control {
        rtmp_control all;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   html;
    }
}
```

}

rtmp {
    server {
        listen 1935;
        #ping 30s;
        #notify_method get;

```
    # protected application
    application myapp {
        live on;
        on_play http://localhost:8081/on_play;
    }

    #application myapp {
     #   live on;

        # sample play/publish handlers
        #on_play http://localhost:8080/on_play;
        #on_publish http://localhost:8080/on_publish;

        # sample recorder
        #recorder rec1 {
        #    record all;
        #    record_interval 30s;
        #    record_path /tmp;
        #    record_unique on;
        #}

        # sample HLS
        #hls on;
        #hls_path /tmp/hls;
        #hls_sync 100ms;
    #}

    # Video on demand
    #application vod {
      #live on;  
    #  play /var/videos;
    #}

    # Video on demand over HTTP
    #application vod_http {
    #    play http://localhost:8080/vod/;
    #}
}
```

}

ffplay Debug is

configuration: --prefix=/usr --enable-static --enable-shared --enable-gpl --enable-nonfree --enable-postproc --enable-avfilter --enable-pthreads -$
  libavutil      52. 40.100 / 52. 40.100
  libavcodec     55. 19.100 / 55. 19.100
  libavformat    55. 12.102 / 55. 12.102
  libavdevice    55.  3.100 / 55.  3.100
  libavfilter     3. 81.103 /  3. 81.103
  libswscale      2.  4.100 /  2.  4.100
  libswresample   0. 17.103 /  0. 17.103
  libpostproc    52.  3.100 / 52.  3.100
socket(): Address family not supported by protocol
socket(): Address family not supported by protocol
ALSA lib pulse.c:229:(pulse_connect) PulseAudio: Unable to connect: Connection refused

[rtmp @ 0x7fad000013e0] Handshaking... vq=    0KB sq=    0B f=0/0
[rtmp @ 0x7fad000013e0] Type answer 3
[rtmp @ 0x7fad000013e0] Server version 13.14.10.13
[rtmp @ 0x7fad000013e0] Proto = rtmp, path = /myapp/517872191_2?e=1374942450&st=UxfdmJrsCc8sbD9KHOjbuA, app = myapp, fname = 517872191_2?e=1374942$
[rtmp @ 0x7fad000013e0] Server bandwidth = 5000000sq=    0B f=0/0
[rtmp @ 0x7fad000013e0] Client bandwidth = 5000000sq=    0B f=0/0
[rtmp @ 0x7fad000013e0] New incoming chunk size = 4096
[rtmp @ 0x7fad000013e0] Creating stream...
    Last message repeated 1 times  0KB vq=    0KB sq=    0B f=0/0
[rtmp @ 0x7fad000013e0] Sending play command for '517872191_2?e=1374942450&st=UxfdmJrsCc8sbD9KHOjbuA'
rtmp://localhost:1935/myapp/517872191_2?e=1374942450&st=UxfdmJrsCc8sbD9KHOjbuA: Input/output error

**Comment by gdulli111** [comment]
hi arut how are you ? just came across this threat need help with nginx rtmp   my server is up an running i want to secure so that the streams play only on my website so please dont steal my streams any help much appreciate
