### ISSUE TITLE
simpe exec ffmpeg doesn't work on debian and os x 

### ISSUE THREAD

**Issue by sulphur** [arut/nginx-rtmp-module#237]
Hi, 

I have a strange problem with exec ... 

```
exec ffmpeg >/tmp/out.txt 2>&1;
```

doesn't work 

however this : 

```
exec which ffmpeg >/tmp/out.txt 2>&1;
```

works fine and outputs a good path to my ffmpeg in /usr/local/bin/ffmpeg

I was looking through the issues but i didn't found any that is resolves my problem. I updated the nginx to 1.5.3 today and also made a git pull of nginx-rtmp module 2 hours ago. 

I have the same problem on os x as well as on debian

**Comment by SanteR1** [comment]
@sulphur 
hi, how you fix it?

**Comment by almoghzn** [comment]
Hi @SanteR1 ,  @sulphur 

I'm expirience the same issue.
My ffmpeg command:
exec ffmpeg -i rtmp://localhost/$app/$name -c:a libfdk_aac -b:a 64k -c:v libx264 -preset fast -profile:v baseline -vsync cfr -s 320x180 -b:v 256K -bufsize 256k -f flv rtmp://localhost/dash/$name;

And nginx's error.log:
2018/03/14 09:48:09 [info] 32429#0: *2 client connected '82.80.138.81'
2018/03/14 09:48:09 [info] 32429#0: *2 connect: app='ingest' args='' flashver='' swf_url='' tc_url='rtmp://52.59.187$
2018/03/14 09:48:09 [info] 32429#0: *2 createStream, client: 82.80.138.81, server: 0.0.0.0:1935
2018/03/14 09:48:09 [info] 32429#0: *2 publish: name='streamname_low' args='' type=live silent=0, client: 82.80.138.$
2018/03/14 09:48:09 [info] 32429#0: *2 exec: starting managed child 'ffmpeg', client: 82.80.138.81, server: 0.0.0.0:$
2018/03/14 09:48:09 [info] 32429#0: *3 client connected '127.0.0.1'
2018/03/14 09:48:09 [info] 32429#0: *3 connect: app='ingest' args='' flashver='' swf_url='' tc_url='rtmp://localhost$
2018/03/14 09:48:09 [info] 32429#0: *3 createStream, client: 127.0.0.1, server: 0.0.0.0:1935
2018/03/14 09:48:09 [info] 32429#0: *3 play: name='streamname_low' args='' start=0 duration=0 reset=0 silent=0, clie$
2018/03/14 09:48:09 [info] 32429#0: *2 relay: got metadata from @setDataFrame invocation from publisher., client: 82$
**2018/03/14 09:48:10 [notice] 32429#0: signal 17 (SIGCHLD) received
2018/03/14 09:48:10 [notice] 32429#0: unknown process 32469 exited with code 1**
2018/03/14 09:48:10 [info] 32429#0: *3 deleteStream, client: 127.0.0.1, server: 0.0.0.0:1935
2018/03/14 09:48:10 [info] 32429#0: *3 send() failed (32: Broken pipe), client: 127.0.0.1, server: 0.0.0.0:1935
2018/03/14 09:48:10 [info] 32429#0: *2 exec: child 32469 exited; ignoring, client: 82.80.138.81, server: 0.0.0.0:1935
2018/03/14 09:48:10 [info] 32429#0: *2 exec: terminating child 32469, client: 82.80.138.81, server: 0.0.0.0:1935
2018/03/14 09:48:10 [info] 32429#0: *3 disconnect, client: 127.0.0.1, server: 0.0.0.0:1935
2018/03/14 09:48:10 [info] 32429#0: *3 deleteStream, client: 127.0.0.1, server: 0.0.0.0:1935
2018/03/14 09:48:15 [info] 32429#0: *2 exec: starting managed child 'ffmpeg', client: 82.80.138.81, server: 0.0.0.0:$
2018/03/14 09:48:15 [info] 32429#0: *4 client connected '127.0.0.1'
2018/03/14 09:48:15 [info] 32429#0: *4 connect: app='ingest' args='' flashver='' swf_url='' tc_url='rtmp://localhost$
2018/03/14 09:48:15 [info] 32429#0: *4 createStream, client: 127.0.0.1, server: 0.0.0.0:1935
2018/03/14 09:48:15 [info] 32429#0: *4 play: name='streamname_low' args='' start=0 duration=0 reset=0 silent=0, clie$
2018/03/14 09:48:16 [info] 32429#0: *4 deleteStream, client: 127.0.0.1, server: 0.0.0.0:1935
2018/03/14 09:48:16 [info] 32429#0: *4 recv() failed (104: Connection reset by peer), client: 127.0.0.1, server: 0.0$
2018/03/14 09:48:16 [info] 32429#0: *4 disconnect, client: 127.0.0.1, server: 0.0.0.0:1935
2018/03/14 09:48:16 [info] 32429#0: *4 deleteStream, client: 127.0.0.1, server: 0.0.0.0:1935
2018/03/14 09:48:16 [info] 32429#0: *2 exec: child 32471 exited; ignoring, client: 82.80.138.81, server: 0.0.0.0:1935
2018/03/14 09:48:16 [info] 32429#0: *2 exec: terminating child 32471, client: 82.80.138.81, server: 0.0.0.0:1935
2018/03/14 09:48:16 [notice] 32429#0: signal 17 (SIGCHLD) received
2018/03/14 09:48:16 [notice] 32429#0: unknown process 32471 exited with code 1
2018/03/14 09:48:16 [info] 32429#0: epoll_wait() failed (4: Interrupted system call)
2018/03/14 09:48:21 [info] 32429#0: *2 exec: starting managed child 'ffmpeg', client: 82.80.138.81, server: 0.0.0.0:$
2018/03/14 09:48:21 [info] 32429#0: *5 client connected '127.0.0.1'
2018/03/14 09:48:21 [info] 32429#0: *5 connect: app='ingest' args='' flashver='' swf_url='' tc_url='rtmp://localhost$
2018/03/14 09:48:21 [info] 32429#0: *5 createStream, client: 127.0.0.1, server: 0.0.0.0:1935
2018/03/14 09:48:21 [info] 32429#0: *5 play: name='streamname_low' args='' start=0 duration=0 reset=0 silent=0, clie$
2018/03/14 09:48:22 [info] 32429#0: *5 deleteStream, client: 127.0.0.1, server: 0.0.0.0:1935
2018/03/14 09:48:22 [info] 32429#0: *5 recv() failed (104: Connection reset by peer), client: 127.0.0.1, server: 0.0$
2018/03/14 09:48:22 [info] 32429#0: *5 disconnect, client: 127.0.0.1, server: 0.0.0.0:1935
2018/03/14 09:48:22 [info] 32429#0: *5 deleteStream, client: 127.0.0.1, server: 0.0.0.0:1935


How did you fix it?

**Comment by sulphur** [comment]
I don't remember :( Is your stream is a `rtmp` received from flash plugin in browser ? I think it was related to flash plugin and the corrupted/malformed `rtmp` stream that caused ffmpeg tu quit

**Comment by almoghzn** [comment]
Hi @sulphur 

I managed to resolve my issue (there were lot of them :( )

First my nginx service ran under nobody user and I changed it to run under root.
Second. I had couple of ffmpeg errors, I was able to identified them by adding ">output.txt1>&2" to the end of the ffmpeg command.
