### ISSUE TITLE
RTMP chunk stream too big: 45 >= 32

### ISSUE THREAD

**Issue by sulphur** [arut/nginx-rtmp-module#241]
We found what was causing it, when we put `interleave on;`

we have the following message that appears in error.log and stream disconects and reconects...

and with `interleave off;` everything seems to work fine

edit.

to reproduce it you need the video resolution > 320x240

**Comment by wangcheng911** [comment]
Does the directive publish_time_fix still can be used? I can not find it in wiki.

**Comment by wangcheng911** [comment]
Does the directive publish_time_fix still exist? I can not find it in wiki.

**Comment by winshining** [comment]
@wangcheng911 Yes, you can find it in file ngx_rtmp_core_module.c, it can be specified in the rtmp or server or application block, as follows:
publish_time_fix on;

**Comment by wangcheng911** [comment]
@winshining Thank you very much! I will try it.

**Comment by rayj00** [comment]
Can you fix this please!   It is critical for me and the task I am working on:

2018/06/08 14:40:42 [info] 8776#0: *1 client connected '192.168.0.5'
2018/06/08 14:40:42 [info] 8776#0: *1 connect: app='LPC1' args='' flashver='FMLE/3.0 (compatible; FMSc/1.0)' swf_url='rtmp://192.168.0.47/LPC1' tc_url='rtmp://192.168.0.47/LPC1' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 192.168.0.5, server: 0.0.0.0:1935
2018/06/08 14:40:42 [info] 8776#0: *1 createStream, client: 192.168.0.5, server: 0.0.0.0:1935
2018/06/08 14:40:42 [info] 8776#0: *1 publish: name='' args='' type=live silent=0, client: 192.168.0.5, server: 0.0.0.0:1935
2018/06/08 14:40:42 [info] 8776#0: *1 relay: create push name='' app='' playpath='' url='10.57.215.214:1935/movie', client: 192.168.0.5, server: 0.0.0.0:1935
2018/06/08 14:40:42 [alert] 8776#0: *2 too big RTMP chunk size:134217728, client: 10.57.215.214:1935/movie, server: ngx-relay
2018/06/08 14:40:42 [info] 8776#0: *2 too big message: 1048576, client: 10.57.215.214:1935/movie, server: ngx-relay
2018/06/08 14:40:42 [info] 8776#0: *2 disconnect, client: 10.57.215.214:1935/movie, server: ngx-relay
2018/06/08 14:40:42 [info] 8776#0: *2 deleteStream, client: 10.57.215.214:1935/movie, server: ngx-relay
