### ISSUE TITLE
[Control module] Add ability to drop client connections by netmask

### ISSUE THREAD

**Issue by maxromanovsky** [arut/nginx-rtmp-module#259]
It would be very helpful to drop client connections by netmask, e.g.:

```
http://streaming.example.com/control/drop/client?app=mypull&name=test.stream&addr=192.168.0.0/24
```

It would decrease HTTP traffic to control module and could help to drop tons of connections at once.

**Comment by buaalinux** [comment]
it does‘t work

**Comment by maxromanovsky** [comment]
@buaalinux Yes, because it's just a feature request :)
