### ISSUE TITLE
HLS cleanup not working

### ISSUE THREAD

**Issue by hpms1972** [arut/nginx-rtmp-module#265]
Hi,

i have the problem that hls_cleanup is not working at all, nginx does not delete anything, the path with the fragments is getting bigger and bigger until the is no space left on the disk
Here is my config:

```
        hls on;
        hls_path /tmp/hls;
        hls_fragment 10s;
        hls_playlist_length 10s;
        hls_cleanup on;
```

I used different settings for hls_fragment and hls_playlist_length but that does not change anything. Even with the above settings in a short time i get easily over 100 fragments without one of them is getting deleted.

Nginx is running on an RaspberryPi with an Arch-Linux.
Any ideas?

Thanks,
hpms1972

**Comment by jhanvi22** [comment]
I have the same issue.
I have set             hls_cleanup on; in nginx conf file.
Still it is not removing old hls segments. How did you fix it?

**Comment by Krautmaster** [comment]
why closed?
