### ISSUE TITLE
signal 17 (SIGCHLD) received

### ISSUE THREAD

**Issue by sulphur** [arut/nginx-rtmp-module#274]
Hi,

I have this message in my log :

```
2013/10/14 11:14:04 [info] 7380#0: *39 createStream, client: 127.0.0.1, server: 0.0.0.0:1935
2013/10/14 11:14:04 [info] 7380#0: *39 play: name='879' args='' start=0 duration=0 reset=0 silent=0, client: 127.0.0.1, server: 0.0.0.0:1935
2013/10/14 11:14:04 [info] 7380#0: *39 notify: play 'staging.myserver.com/nginx/play', client: 127.0.0.1, server: 0.0.0.0:1935
2013/10/14 11:14:08 [info] 7380#0: *39 deleteStream, client: 127.0.0.1, server: 0.0.0.0:1935
2013/10/14 11:14:08 [info] 7380#0: *39 notify: play_done 'staging.myserver.com/nginx/play_done', client: 127.0.0.1, server: 0.0.0.0:1935
2013/10/14 11:14:08 [info] 7380#0: *39 notify: done 'staging.myserver.com/nginx/done', client: 127.0.0.1, server: 0.0.0.0:1935
2013/10/14 11:14:08 [info] 7380#0: *39 send() failed (104: Connection reset by peer), client: 127.0.0.1, server: 0.0.0.0:1935
2013/10/14 11:14:08 [info] 7380#0: *39 disconnect, client: 127.0.0.1, server: 0.0.0.0:1935
2013/10/14 11:14:08 [info] 7380#0: *39 deleteStream, client: 127.0.0.1, server: 0.0.0.0:1935
2013/10/14 11:14:08 [notice] 7380#0: signal 17 (SIGCHLD) received
2013/10/14 11:14:08 [notice] 7380#0: unknown process 7533 exited with code 1
```

Basically i do exec to transcode and push a stream to another server. The transcoding and video are fine everything works. When i lunch my exec from command line i have no errors at all. That is why i don't understand why this message is repeating all the time in my log.

**Comment by johnboiles** [comment]
FYI for others encountering a similar issue, you might want to make sure that the `nobody` user has access to the device or file you're trying to read with ffmpeg. Try out your ffmpeg command with `sudo -u nobody ffmpeg ARGS` and see if it works first

**Comment by mkrn** [comment]
Had the same issue.  renaming exec => exec_push in nginx.conf helped. Works in nginx 1.15.1

**Comment by bundyfx** [comment]
Had this also, from the command line you are probably using '\' to separate long commands over many lines, you need to remove those before copying the command line command into your nginx.conf

**Comment by corneliusweiss** [comment]
> Had the same issue. renaming exec => exec_push in nginx.conf helped. Works in nginx 1.15.1

you saved my day man!
