### ISSUE TITLE
RTMPT

### ISSUE THREAD

**Issue by scohen28** [arut/nginx-rtmp-module#279]
I have a corporate user trying to stream video to our nginx server with the rtmp module (works for most all users) - but this user''s coroprate network is using proxies - my understanding is that there's no way for the player to route plain RTMP traffic through the browser proxy. By default, RTMP traffic is sent through port 1935, but browser proxies won't re-route non-HTTP traffic. This is is what the RTMPT variant does, it's traffic is routed over HTTP, and so the browser has the opportunity to route it through a proxy.

Is rtmpt supported (or future supported) by this module, or is that a client side piece?

**Comment by lockie** [comment]
@arut , would you (in theory) accept patch providing RTMPT support?

**Comment by misiek08** [comment]
Theres a fork, maintained by someone else and you can make pull request
there.

W dniu niedziela, 19 lipca 2015 Andrew Kravchuk <notifications@github.com>
napisał(a):

**Comment by lavvy** [comment]
Please @misiek which fork

**Comment by radius314** [comment]
@lavvy did you ever submit the RTMPT pull request?  which fork was the one?

**Comment by lavvy** [comment]
No.  I'm actually looking for an nginx rtmp fork that is being maintained

**Comment by krombel** [comment]
@lavvy This fork seems to be maintained currently:
https://github.com/sergey-dryabzhinsky/nginx-rtmp-module

**Comment by lavvy** [comment]
Thanks so much,  I appreciate that

**Comment by krish0005** [comment]
hi, is there any plan to support RTMPT in nginx-rtmp-module ?
any workaround suggested ?
