### ISSUE TITLE
How to pull a stream from a crtmpserver

### ISSUE THREAD

**Issue by yukl** [arut/nginx-rtmp-module#292]
I have a crtmpserver and a nginx-rtmp.
Now I want to pull a stream from crtmpserver. Then show it on VLC media player.
How the Pull Directive should be?
Here the nginx.conf 

worker_processes  1;

error_log  logs/error.log debug;

events {
    worker_connections  1024;
}

rtmp {
    server {
        listen 1935;

```
    application live {
        live on;
        hls on;
        hls_path /tmp/video;
        hls_fragment 15s;
    }
}
```

}

http {
    server {
        listen      80;
        location /video {
            alias /tmp/video;
        }
}

for your help. Please.

**Comment by wdjwxh** [comment]
as above, is there any plan to implement it?

**Comment by arut** [comment]
I have plans, but currently I don't have time.

**Comment by wdjwxh** [comment]
Thanks for reply.

**Comment by LancCJ** [comment]
> If you only need rtmp stream then just add this part to standard (http) nginx.conf
> 
> ```
> rtmp {
>      server {
>          listen 1935;
>          application myapp {
>              live on;
>              pull rtmp://remote.server.com/app/name name=mystream;
>          }
>     }
> }
> ```
> 
> play url is `rtmp://local.server.com/myapp/mystream`
> 
> If you want to have HLS locally then you need static pulling, just add `static` keyword to the end of pull directive line.

hi,sir

my config file like this to config,but i  cant not get Stream,do you known why?

my nginx config is 

`


#user  nobody;
worker_processes  1;

error_log  logs/error.log debug;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}



http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    }


    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}


    # HTTPS server
    #
    #server {
    #    listen       443 ssl;
    #    server_name  localhost;

    #    ssl_certificate      cert.pem;
    #    ssl_certificate_key  cert.key;

    #    ssl_session_cache    shared:SSL:1m;
    #    ssl_session_timeout  5m;

    #    ssl_ciphers  HIGH:!aNULL:!MD5;
    #    ssl_prefer_server_ciphers  on;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}

}

# stream {

#     upstream proxy_name {
#          server 10.67.89.191:19041;#需要代理的端口
#     }

#     server {  
#         listen 1935;  
#         proxy_pass proxy_name;
#     } 

# }


rtmp_auto_push on;

rtmp {

    server {

        listen 1935;
        chunk_size 4096;

        application mypull {
            live on;
            pull rtmp://10.67.89.191:19041/live/0/32057100001127007720 name=test;
        }

    }

}


`

and the error

`
2021/12/15 13:56:58 [info] 4528#19092: *140694538682371 client connected '192.168.41.172'
2021/12/15 13:56:58 [info] 4528#19092: *3 connect: app='mypull' args='' flashver='LNX 9,0,124,2' swf_url='' tc_url='rtmp://192.168.41.172:1935/mypull' page_url='' acodecs=4071 vcodecs=252 object_encoding=0, client: 192.168.41.172, server: 0.0.0.0:1935
2021/12/15 13:56:58 [info] 4528#19092: *3 createStream, client: 192.168.41.172, server: 0.0.0.0:1935
2021/12/15 13:56:58 [info] 4528#19092: *3 play: name='test' args='' start=-2000 duration=0 reset=0 silent=0, client: 192.168.41.172, server: 0.0.0.0:1935
2021/12/15 13:56:58 [info] 4528#19092: *3 relay: create pull name='test' app='' playpath='' url='10.67.89.191:19041/live/0/32057100001127007720', client: 192.168.41.172, server: 0.0.0.0:1935
2021/12/15 13:57:09 [info] 4528#19092: *3 disconnect, client: 192.168.41.172, server: 0.0.0.0:1935
2021/12/15 13:57:09 [info] 4528#19092: *3 deleteStream, client: 192.168.41.172, server: 0.0.0.0:1935
2021/12/15 13:57:09 [info] 4528#19092: *4 disconnect, client: 10.67.89.191:19041/live/0/32057100001127007720, server: ngx-relay
2021/12/15 13:57:09 [info] 4528#19092: *4 deleteStream, client: 10.67.89.191:19041/live/0/32057100001127007720, server: ngx-relay
`


do you known why,make sure url :rtmp://10.67.89.191:19041/live/0/32057100001127007720 is right,i use vlc player can play
