### ISSUE TITLE
Multi Bitrate Support

### ISSUE THREAD

**Issue by ReneVolution** [arut/nginx-rtmp-module#295]
Hi again,

i'm very interested in creating Multi Bitrate DASH streams and maybe also supporting multiple angle's. Would you mind pointing me into a direction where to implement this feature?

My suggestion related to Manifest generation would be to create multi bitrate groups based on the streamname. A general approach could be a naming convention like 'channel_angle_bitrate'. The trick would be to listen for connection starts and closings to update the "Master"-Manifest.

On the other side all segments would need to be synced. Here is where i really don't know to start. Maybe there would be a requirement for an input stream buffer for synchronization by RTMP Timestamps? Do you have any idea where i/we could start?

Thanks and bests,
René

**Comment by jsardas** [comment]
Hi @ReneVolution , I've been looking for the exact same feature for a long time, as described in the following issue from a different fork of nginx-rtmp:
https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/issues/195

Would you mind sharing a link to the pull request you mentioned with this feature?

Thank you!

**Comment by redgrasss** [comment]
I would also like to know more about the pull request/feature request since I coudln't successfully stream 3 streams (multibitrate) with FMLE.
