### ISSUE TITLE
Exec on Windows

### ISSUE THREAD

**Issue by iongion** [arut/nginx-rtmp-module#303]
For development purposes, isn't it possible to have a functional exec in a cygwin or msys environment ?

Everything compiles fine in cygwin, when exec is called

[debug] 3644#0: *1 select add event fd:9 ev:1
[alert] 3644#0: *1 select event fd:9 ev:1 is already set, client: 10.3.10.101, server: 10.3.10.101:1935

And nothing gets executed.
I know it is specified that exec & family are not working on Windows, but maybe there is hope, at least in Cygwin.

**Comment by cmdremily** [comment]
I'm potentially interested in making a patch, @arut did you attempt to port it and ran into difficulties or did you just `#ifdef` it out to get the module working on Windows (totally fair thing to do btw)? Do you have any thoughts on what the cleanest way of doing this would be?
