### ISSUE TITLE
Record doesn't work...

### ISSUE THREAD

**Issue by bezzha** [arut/nginx-rtmp-module#332]
I have no idea why my configuration doesn't record stream... Live and HLS work great!
This is my config:

rtmp {
    server {
        listen 8080;
        ping 30s;
        notify_method get;

```
    application videolive {
        live on;
        sync 10ms;

        hls on;
        hls_path /tmp/hls;

        dash on;
        dash_path /tmp/dash;

        record all;
        record_path /tmp;
        record_suffix _recorded.flv;
    }
}
```

}

**Comment by maksymlaptiev** [comment]
hello @arut 
I set RTMP on window server and record doesn't work.
How can I record streaming video?
