### ISSUE TITLE
hls: max fragment length reached

### ISSUE THREAD

**Issue by stanma** [arut/nginx-rtmp-module#346]
Hello

I saw another ticket with such a problem and I can say that it remains for us too. Probably I can say more details about it.

Source is fetched with pull, like this:

```
    application streams {
        live on;
        pull rtmp://server:1936/stream/channel name=mychannel static;
    }
```

From the start it works just fine but after a few hours it starts filling log with such error.

The main problem is what nginx rtmp module starts writing all information to the same segment and it grows until fills all available space on file system. Meanwhile manifest file  (index.m3u8) is deleted. Of course we created tmpfs and hls_path follows to it.

We tested on different rtmp sources and problem remains after some time. Probably it is some case of bug with reconnecting feature or something. And I can't say those sources were unstable or something like that. 

Is there anything can be done about this?

Thank you.

**Comment by dburianov** [comment]
I comment in post my problem and solutions [https://github.com/arut/nginx-rtmp-module/issues/568](url)
