### ISSUE TITLE
Unable to Relay Push to ustream.tv

### ISSUE THREAD

**Issue by kientran** [arut/nginx-rtmp-module#348]
I have been trying to relay my feed over to ustream.tv but have not been able to.

The push directive is as follows.
push rtmp://#.#######.fme.ustream.tv/ustreamVideo/#######/STREAMKEY

I attempted to add in 'flashver=FME/2.5\20(compatible;\20FMSc\201.0)' as suggested by various forums (and various version of it with and without escaped spaces) but have not had any luck.

Has anyone been able to relay a feed to ustream in this way?  I had no problems with justin.tv

**Comment by C74K** [comment]
any update ?
