### ISSUE TITLE
RTMP Publish stops after receiving 3.954GB

### ISSUE THREAD

**Issue by d3ed3e** [arut/nginx-rtmp-module#354]
Hi Guys,

I am currently having a problem with publishing from FMLE to nginx-rtmp.
I am using FMLE x64 in a Win7x64 machine and publishing to nginx-rtmp server using ubuntu 13.10 x64 server running nginx 1.5.10 w/ nginx-rtmp-module 1.1.2

I currently have a livestream from a tv capture on FMLE publishing to nginx and playing the livestream through jwplayer which is being broadcasted onto multiple screens via a digital signage solution on a local network.

I am not sure as to what is going on but I am finding once the stream reaches 3.954 GB from FMLE, the stream stops for roughly 30-45 mins then continues again.

Here is a sample logs from FMLE showing the following:

Tue Feb 25 2014 00:17:31 : Session Started
Tue Feb 25 2014 00:17:31 : AutoAdjust feature is enabled
Tue Feb 25 2014 00:17:31 : Audio Encoding Started 
Tue Feb 25 2014 00:17:31 : Video Encoding Started 
Tue Feb 25 2014 01:26:22 : Auto Adjust : Video bitrate set to 5911 Kbps
Tue Feb 25 2014 01:39:11 : Primary - More than 50 % of the specified threshold values (Max buffer size 512000 KB or Max buffer duration 3600 sec) of RTMP buffer reached. Current network conditions are unfavorable to publish data at the specified bitrate. RTMP buffer will be flushed and streams will be re-published when the threshold value is reached. 
Tue Feb 25 2014 01:44:21 : Primary - More than 70 % of the specified threshold values (Max buffer size 512000 KB or Max buffer duration 3600 sec) of RTMP buffer reached. Current network conditions are unfavorable to publish data at the specified bitrate. RTMP buffer will be flushed and streams will be re-published when the threshold value is reached. 
Tue Feb 25 2014 01:49:31 : Primary - More than 90 % of the specified threshold values (Max buffer size 512000 KB or Max buffer duration 3600 sec) of RTMP buffer reached. Current network conditions are unfavorable to publish data at the specified bitrate. RTMP buffer will be flushed and streams will be re-published when the threshold value is reached. 
Tue Feb 25 2014 01:52:11 : Primary - RTMP buffer exceeded the specified threshold values (Max buffer size 512000 KB or Max buffer duration 3600 sec). Flushing the RTMP buffer  and re-publishing the streams.
Tue Feb 25 2014 01:52:16 : Primary - Network Status: NetConnection.Connect.Closed status
Tue Feb 25 2014 01:52:16 : Primary - Disconnected
Tue Feb 25 2014 01:52:16 : Primary - Connected to FMS/3,0,1,123
Tue Feb 25 2014 01:52:16 : Primary - Stream[livestream] Status: Success
Tue Feb 25 2014 01:52:16 : Primary - Stream[livestream] Status: NetStream.Publish.Start
Tue Feb 25 2014 01:52:31 : Auto Adjust : Video bitrate set to 7319 Kbps
Tue Feb 25 2014 01:52:36 : Auto Adjust : Video bitrate set to 8728 Kbps
Tue Feb 25 2014 01:52:46 : Auto Adjust : Video bitrate set to 10137 Kbps
Tue Feb 25 2014 01:52:56 : Auto Adjust : Video bitrate set to 11546 Kbps
Tue Feb 25 2014 01:53:06 : Auto Adjust : Video bitrate set to 12955 Kbps
Tue Feb 25 2014 01:53:16 : Auto Adjust : Video bitrate set to 14364 Kbps
Tue Feb 25 2014 01:53:26 : Auto Adjust : Video bitrate set to 15773 Kbps
Tue Feb 25 2014 01:53:36 : Auto Adjust : Video bitrate set to 17182 Kbps
Tue Feb 25 2014 01:53:46 : Auto Adjust : Video bitrate set to 18591 Kbps
Tue Feb 25 2014 01:53:56 : Auto Adjust : Video bitrate set to 20000 Kbps

I feel the issue is similar to this logged issue - https://groups.google.com/forum/#!searchin/nginx-rtmp/fmle/nginx-rtmp/rF_6Yv9NRIQ/5U7fPytrzqgJ

but was not quite sure on how to apply the fmle fix or if the branch had been implemented into the current nginx-rtmp-module (excuse my technical understanding on the matter as im quite limited in my unix knowledge) 

My nginx.conf configuration is as follows:

rtmp {

```
    server {

            listen 1935;
            publish_time_fix off;
            #ping 1m;
            #ping_timeout 30s;
            chunk_size 128;


            # Transcoding
            application tv {

                    live on;
```
# record first 1K of stream

```
                    # record all;
                    # record_path /usr/local/nginx/html/video;
                    # record_max_size 1K;

                    # append current timestamp to each flv
                    # record_unique on;
```

}

I have turned debugging on but have a logfile which is over 3G in size and am not sure if its of any use.

here is my informational log though

2014/02/25 11:16:15 [notice] 6173#0: using the "epoll" event method
2014/02/25 11:16:15 [notice] 6173#0: nginx/1.5.10
2014/02/25 11:16:15 [notice] 6173#0: built by gcc 4.8.1 (Ubuntu/Linaro 4.8.1-10ubuntu9)
2014/02/25 11:16:15 [notice] 6173#0: OS: Linux 3.11.0-12-generic
2014/02/25 11:16:15 [notice] 6173#0: getrlimit(RLIMIT_NOFILE): 1024:4096
2014/02/25 11:16:15 [notice] 6174#0: start worker processes
2014/02/25 11:16:15 [notice] 6174#0: start worker process 6175
2014/02/25 11:16:15 [notice] 6174#0: start cache manager process 6176
2014/02/25 11:16:44 [info] 6175#0: *1 client connected '172.27.9.183'
2014/02/25 11:16:44 [info] 6175#0: *1 connect: app='tv' args='' flashver='FMLE/3.0 (compatible; FMSc/1.0)' swf_url='rtmp://stream.abcde.com.au/tv' tc_url='rtmp://stream.asi$
2014/02/25 11:16:44 [info] 6175#0: *1 createStream, client: 172.27.9.183, server: 0.0.0.0:1935
2014/02/25 11:16:44 [info] 6175#0: *1 publish: name='livestream' args='videoKeyframeFrequency=5&totalDatarate=20192' type=live silent=0, client: 172.27.9.183, server: 0.0.0$
2014/02/25 11:16:58 [info] 6175#0: *8 client connected '172.27.12.240'
2014/02/25 11:16:58 [info] 6175#0: *8 connect: app='tv' args='' flashver='WIN 12,0,0,70' swf_url='http://stream.abcde.com.au/player.swf' tc_url='rtmp://stream.asics.com.au/$
2014/02/25 11:16:58 [info] 6175#0: *8 createStream, client: 172.27.12.240, server: 0.0.0.0:1935
2014/02/25 11:16:58 [info] 6175#0: *8 play: name='livestream' args='' start=0 duration=0 reset=0 silent=0, client: 172.27.12.240, server: 0.0.0.0:1935
2014/02/25 11:17:07 [info] 6175#0: *3 client closed connection while waiting for request, client: 172.27.12.240, server: 0.0.0.0:80
2014/02/25 11:17:17 [info] 6175#0: *4 client closed connection while waiting for request, client: 172.27.12.240, server: 0.0.0.0:80
2014/02/25 11:17:18 [info] 6175#0: *6 client closed connection while waiting for request, client: 172.27.12.240, server: 0.0.0.0:80
2014/02/25 11:17:18 [info] 6175#0: *7 client closed connection while waiting for request, client: 172.27.12.240, server: 0.0.0.0:80
2014/02/25 12:51:30 [info] 6175#0: *1 recv() failed (104: Connection reset by peer), client: 172.27.9.183, server: 0.0.0.0:1935
2014/02/25 12:51:30 [info] 6175#0: *1 disconnect, client: 172.27.9.183, server: 0.0.0.0:1935
2014/02/25 12:51:30 [info] 6175#0: *1 deleteStream, client: 172.27.9.183, server: 0.0.0.0:1935
2014/02/25 12:51:30 [info] 6175#0: *12 client connected '172.27.9.183'
2014/02/25 12:51:30 [info] 6175#0: *12 connect: app='tv' args='' flashver='FMLE/3.0 (compatible; FMSc/1.0)' swf_url='rtmp://stream.abcde.com.au/tv' tc_url='rtmp://stream.as$
2014/02/25 12:51:30 [info] 6175#0: *12 createStream, client: 172.27.9.183, server: 0.0.0.0:1935
2014/02/25 12:51:30 [info] 6175#0: *12 publish: name='livestream' args='videoKeyframeFrequency=5&totalDatarate=20192' type=live silent=0, client: 172.27.9.183, server: 0.0.$

appreciate and help if anyone can assist, thanks in advance.

D.

**Comment by kadirgecit** [comment]
this issue still persists. i have latest version rmtp-module with nginx 1.16.1 on :
4.15.0-91-generic #92~16.04.1-Ubuntu SMP Fri Feb 28 14:57:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

after 3.9GB publish stops for a minute.
