### ISSUE TITLE
screenshot support

### ISSUE THREAD

**Issue by benphelps** [arut/nginx-rtmp-module#356]
It would be wonderful if there was a reliable method to capture a screenshot or screen grab of the stream, perhaps on a timer.

I'm currently using this bit of ffmpeg to make an attempt at capturing a screenshot every 15 seconds, it really isn't reliable and seems to spawn a lot of ffmpeg processes (I guess they're orphaned).

``` bash
exec_push /usr/local/bin/ffmpeg -i rtmp://live.watchme.io/$app/$name -probesize 20M -analyzeduration 400000000 -f image2 -vf fps=fps=1/15 -y -updatefirst 1 /home/ubuntu/public_html/thumb/$name.png;
```

Having support for something like this would be amazing.

**Comment by SeoulTsai** [comment]
@arut 
 my setting
        recorder preview {
            record keyframes;
            record_path /tmp/hls;
            record_max_frames 10;
            record_interval 5s;
            exec_record_done ffmpeg -i rtmp://127.0.0.1:1935/hls/${name} -vcodec png -y /tmp/hls/$name.png;
        }
i got message: nginx: [emerg] "recorder" directive is not allowed here in /usr/local/nginx/conf/nginx.conf:200
the line is :  recorder preview {

can you help me?

**Comment by jaybkim1** [comment]
@SeoulTsai Can I see the whole rtmp server setup in your nginx.conf?

**Comment by tolew1** [comment]
FYI for anyone who gets this, it's because record is under the Application context. If it's outside, you will get that error. It should be.

```
application live {
    ...
        # make previews
        recorder preview {
                record keyframes;
                record_max_frames 4;
                record_path /data/preview;
                record_interval 30s;
                exec_record_done ffmpeg -i $path -vcodec png -vframes 1 -an -f rawvideo -s 320x240 -ss 00:00:01 -y /data/broadcast/$name.png;
         }
     ...
}#end application
```
