### ISSUE TITLE
Exec not working in master ?

### ISSUE THREAD

**Issue by kelexel** [arut/nginx-rtmp-module#37]
Here is my simple config for current master branch on FreeBSD 9.x :

I have tried to mimic the "big & small" setup but without luck.

> rtmp {
>    server {
>         listen 1.2.3.4:1935;
>         chunk_size 128;
>         publish_time_fix off;
>         application proxy {
>             live on;
>             exec /usr/local/bin/ffmpeg -re -i rtmp://1.2.3.4:1935/$app/$name -vcodec flv -acodec copy -s 32x32 -f flv rtmp://1.2.3.4:1935/720p/$name;
>             hls on;
>             hls_path /home/stream/hls;
>             hls_fragment 15s;
>         }
>         application 720p {
>                 live on;
>         }
>         application 480p {
>                 live on;
>         }
>         application 360p {
>                 live on;
>         }
>         application 240p {
>                 live on;
>         }
>     }
> }

If I run the following command outside nginx in a shell ..: 

> /usr/local/bin/ffmpeg -re -i rtmp://1.2.3.4:1935/proxy/test -vcodec flv -acodec copy -s 32x32 -f flv rtmp://1.2.3.4:1935/720p/test;

It works as expected

What would you advise checking ?
(Note HLS works fine)

**Comment by FingerRec** [comment]
I solved this problem by adding below in first line of nginx.conf.
user root
It's Ridha Ben Njima's answer.

https://stackoverflow.com/questions/42388727/ffmpeg-exec-command-not-running-in-nginx-rtmp/45880931#45880931
