### ISSUE TITLE
Add EXT-X-PROGRAM-DATE-TIME to HLS playlist

### ISSUE THREAD

**Issue by jbochi** [arut/nginx-rtmp-module#373]
It would be nice if the absolute time (either from server or from stream's timecode) were included in the playlist file.

See the specification: http://tools.ietf.org/html/draft-pantos-http-live-streaming-12#section-3.4.5

**Comment by che-effe** [comment]
Agreed, looking to expose #EXT-X-PROGRAM-DATE-TIME in HLS playback
