### ISSUE TITLE
Force pull

### ISSUE THREAD

**Issue by IronShaft** [arut/nginx-rtmp-module#38]
Hi,

how can I do to force pull? When I have no rtmp clients, hls clients can't watch also. If i have at least one rtmp client - all works fine.

**Comment by SHUFIL** [comment]
Hello, am also trying to pull steam from encoder device to enginx , i did not getting out put , am using this code only . any one help me about this please

rtmp {
    server {
            listen 1935;
            chunk_size 4096;

application show {
    live on;
    pull rtmp://10.10.12.5:1935/show/mediaone1 live=1; #10.10.12.5 encoder IP, mediaone1 steam name
    # to change the local stream name use this syntax: ... live=1 name=ch3;

    # other directives...
    # hls_...
}
}
}

Regards,
Shufil
