### ISSUE TITLE
Feature request: exec log output

### ISSUE THREAD

**Issue by ReubenM** [arut/nginx-rtmp-module#381]
When using exec to call external programs directly I am running into problems that do not manifest themselves when run from within a shell script wrapper.

Would it be possible to grab stderr (and optionally stdout) and redirect their output to the log files? That's the only way I can think of to figure out why a program fails when running as a direct child process from nginx without a shell.

**Comment by haydenm315** [comment]
Look at ngx_rtmp_exec_module.c around line 780.  stdout and stderr are closed and then assiged to /dev/null.  You can leave these file handles open and remove the calls to dup2 for stdout and stderr.
