### ISSUE TITLE
Stream redirection implementation may not be valid

### ISSUE THREAD

**Issue by ReubenM** [arut/nginx-rtmp-module#385]
The stream redirection feature is causing issues with ffmpeg. It is suggested that the feature, as currently implemented may result in invalid streams. Please advise in a bug discussion for ffmpeg: https://trac.ffmpeg.org/ticket/3553

**Comment by gregfr** [comment]
Do you have more info about this? I'm having this problem with nginx and ffmpeg, both compiled today...

**Comment by suuuehgi** [comment]
> Do you have more info about this? I'm having this problem with nginx and ffmpeg, both compiled today...

I just had the same issue. `-use_wallclock_as_timestamps 1 -fflags +genpts` did it for me.

**Comment by mkrn** [comment]
@suuuehgi are you using it while transcoding to hls optimised stream? Are you using -re, and/or -vsync options with it?
