### ISSUE TITLE
nginx: [emerg] unknown directive "rtmp" in /etc/nginx/conf.d/rtmp.conf:1

### ISSUE THREAD

**Issue by ddif** [arut/nginx-rtmp-module#4]
It gives error below: 

nginx: [emerg] unknown directive "rtmp" in /etc/nginx/conf.d/rtmp.conf:1
nginx: configuration file /etc/nginx/nginx.conf test failed

nginx version: nginx/1.2.0
built by gcc 4.1.2 20080704 (Red Hat 4.1.2-51)
TLS SNI support disabled
configure arguments: --add-module=/usr/local/src/arut-nginx-rtmp-module/ --prefix=/etc/nginx/ --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-mail --with-mail_ssl_module --with-cc-opt='-O2 -g -m64 -mtune=generic'

content of rtmp.conf 

rtmp {
server {

```
    listen 1935;

    chunk_size 4000;

    max_buf 1M;


  application fullhd {
        live on;

        # Pull all streams from remote machine
        # and play locally
        pull localhost:1934;
    }
```

}

http {

```
server {

    listen 8080;

    # This URL provides RTMP statistics in XML
    location /stat {
        rtmp_stat all;

        # Use this stylesheet to view XML as web page
        # in browser
        rtmp_stat_stylesheet stat.xsl;
    }

    location /stat.xsl {
        # XML stylesheet to view RTMP stats.
        # Copy stat.xsl wherever you want
        # and put the full directory path here
        root /home/film;
    }
}
```

}

**Comment by sidarayam** [comment]
Hi,
i have built nginx with rtmp module and created rtmp.conf file in "/etc/nginx/conf.d/". i included it in /etc/nginx/nginx.conf file outside http block, but still i am getting " nginx: [emerg] unknown directive "rtmp" in /etc/nginx/conf.d/rtmp.conf.

Can you help me in this.
attached my nginx.conf file.
[nginx.docx](https://github.com/arut/nginx-rtmp-module/files/1818011/nginx.docx)
