### ISSUE TITLE
RTMPT support

### ISSUE THREAD

**Issue by macklus** [arut/nginx-rtmp-module#413]
Hi:

is nginx-rtmpt-module support RTMPT protocol (same as RTMP but HTTP encapsulate)? 

I gess that its not, so, by now, i use it on 443 port, so i can avoid firewall problems.

is there any point on this ? 

Thanks in advance

**Comment by huglester** [comment]
@arut maybe rtmpt is somehow doable? I mean using rtmp and some other magic?
