### ISSUE TITLE
How to get the number of clients of HLS viewer?

### ISSUE THREAD

**Issue by aluminum711** [arut/nginx-rtmp-module#420]
The stat.xsl can not see the number of clients of HLS viewer.
So, how can i get this number?

**Comment by Cha0sgr** [comment]
@WL-hohoho did you make any progress with hls-watch? Any chances it will be merged with the official nginx rtmp module?

**Comment by scalhoun** [comment]
Interested in this as well to get a generic idea of hls viewers

**Comment by haakonnessjoen** [comment]
What about using javascript in the website to track hls viewers? I am doing this successfully with jwplayer, checking the player status of the player, to confirm that the stream is running.

**Comment by Cha0sgr** [comment]
That's how I do it currently, but I prefer to measure those stats serverside regardless of what player the user wants to use. By doing it clientside with javascript I will have to be restricted to whatever player I end up using. Also on Android devices loading the .m3u8 file directly by using the android's native player tends to be far more stable than through jwplayer or flowplayer, so javascript in that case is not an option.

**Comment by Cha0sgr** [comment]
@misiek08 I understand you cannot share your code. Could you at least describe a high level overview of how you are calculating HLS stats? I wouldn't mind implementing this as a lua script or something similar, as long as the statistics are calculated server-side and not client-side with javascript :) Thanks.

**Comment by misiek08** [comment]
I'm able to control most of websites using server so I give token to every
user. Then I use lua shared memory with on_abort and add users to array by
channel. Many connections from one user are reduced by token. .
29 sty 2015 15:16 "Cha0s" <notifications@github.com> napisał(a):

**Comment by misiek08** [comment]
I'm able to control most of websites using server so I give token to every
user. Then I use lua shared memory with on_abort and add users to array by
channel. Many connections from one user are reduced by token.
29 sty 2015 15:16 "Cha0s" <notifications@github.com> napisał(a):

**Comment by Cha0sgr** [comment]
Thank you for your reply. That was close to what I had in mind. I am looking for a solution that does not depend in anyway on the client. I was thinking maybe using sessions to differentiate the viewers (so they could load the .m3u8 index directly without any tokens). I am still researching. I'll update this post when I find a solution.

**Comment by misiek08** [comment]
Try cookies. Or reduce by IP, but it work bad for people sharing IP.
1 lut 2015 15:58 "Cha0s" <notifications@github.com> napisał(a):

**Comment by ebuildy** [comment]
Send access_log to elasticsearch (via Logstash, there are many tutorial on that).

**Comment by misiek08** [comment]
@ebuildy and? Just like any other basic databse he will need to reduce log entries by some value to get the number. 

@Cha0sgr Depending if your player supports 301 redirects for playlists you have 2 simplest ways here:
yes) You generate random token for user, put it into cookie, redirect it to url with token included. Then you can server playlist for .ts files with token included. Adding token to set in Redis allows you to do just SCARD and get viewer number.
no) You do same thing like above but with cookies. That's worse way because some HLS players don't save cookies (just discards them) so you get double count for same people if player forgots cookie.

If you have access to all websites serving your HLS stream you can add cookie and token at website side and you are 100% protected against any problem. Even if player won't tell you cookie you can point it to playlist_abcdef123.m3u8 and in playlist make .ts fragments with _abdefg123 suffix. Simple rewrites in code and you get counting without even single error.

**Comment by venukommu** [comment]
Hi All,
I'm glad to see that you people already did something for list of HLS views/viewers long ago. I just started a month ago to one of our clients. I was able to do all the setup and we are able to push the live to server using "arut/nginx-rtmp-module". Is there anything included in this module itself to get the views statistics. ?

Are there any ready made scripts to get the viewers statistics ?

It would be great if anybody can help us to move forward.
@WL-hohoho @aluminum711 @misiek08

**Comment by hackman** [comment]
lines_to_check has to be adjusted based on the amount of requests you receive for 1min. 
This also assumes this type of log format:
`81.102.165.233 - - [04/Feb/2022:21:57:38 +0100] "GET /mtest-20220204158391.ts HTTP/1.1" 200 423376 "https://widgets-fosdem.ems.host/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0"
`

```
#!/bin/bash
log=access.log
lines_to_check=20000
formats='ts|hls|dash'
date_prefix=$(date +'%d/%b/%Y:%H')
cur_min=$(date +'%M')
cur_min_decimal=${cur_min:0:1}
if [[ $cur_min_decimal == 0 ]]; then
    prev_min_decimal=5
else
    prev_min_decimal=$(($cur_min_decimal - 1))
fi
cur_minuted_date="${date_prefix}:${cur_min_decimal}"
prev_minuted_date="${date_prefix}:${prev_min_decimal}"
 
tail -n $lines_to_check $log \
	| grep -E "(${cur_minuted_date}|${prev_minuted_date}).*GET \/.*\.($formats)" \
	| awk '{print $7}'|sort|uniq|wc -l

```

**Comment by Reupireup** [comment]
@hackman 

there is a bug in time operation when cur_min_decimal is 0
for example :
if current time is 12:38 prev_minuted_date will be 12:28 (which is fine)
if current time is 12:08 prev_minuted_date will be 12:58 (which is not fine)

instead you can do :
```
...
prev_minuted_date=$(date +'%d/%b/%Y:%H:%M' -d '-10 minutes')
cur_minuted_date=$(date +'%d/%b/%Y:%H:%M')
...
```
