### ISSUE TITLE
RTMP Play Subfolder doesn't work.

### ISSUE THREAD

**Issue by warlof** [arut/nginx-rtmp-module#439]
Hi,

I'm attempting to set up a nginx+rtmp server. I'm currently use basic settings and when i want to play movie at the top level of my rtmp directory, everything works well.

Test with : 

```
ffplay -r rtmp://myhost/vod/mymovie.mp4
```

But, when i use subfolder, nothing work =/

Test with : 

```
ffplay rtmp://myhost/vod/myfolder/mymovie.mp4
```

```
ffplay rtmp://myhost/vod//myfolder/mymovie.mp4
```

Nginx error log :

```
2014/07/19 13:31:05 [info] 8656#0: *4 connect: app='vod/mysubfolder' args='' flashver='' swf_url='' tc_url='rtmp://myhost/vod/mysubfolder' page_url='' acodecs=3191 vcodecs=252 object_encoding=0, client: 93.1.38.170, server: 0.0.0.0:1935
2014/07/19 13:31:05 [info] 8656#0: *4 connect: application not found: 'vod/mysubfolder', client: 127.0.0.1, server: 0.0.0.0:1935
```

(It's same with vod//mysubfolder)

Both return not found file and in debug nginx log, /vod/myfolder is in the application part and not split into application and path

Here is my nginx.conf :

```
rtmp {
        server {
                listen 1935;
                chunk_size 4000;
                application vod {
                       play /srv/vod;
                }
        }
}
```

I'm sure it's because i'm a noob with nginx :D
Any idea ? =/

**Comment by yurevich1** [comment]
rtmp://host:1935/vod/flv:a/flv.flv and rtmp://host:1935/vod//a.flv doesn't work for video.js !!!! how to fix it?

**Comment by erald** [comment]
@yurevich1 did you ever find a solution? I am running into the same problems with video.js
