### ISSUE TITLE
"set" directive is not allowed here

### ISSUE THREAD

**Issue by BarneyOldman** [arut/nginx-rtmp-module#475]
Hi,

I trie to set a variable inside of application but I get the error
nginx: [emerg] "set" directive is not allowed here in /etc/nginx/nginx.conf:18
# user  nobody;

worker_processes  1;

error_log  logs/error.log;
# pid        logs/nginx.pid;

events {
    worker_connections  1024;
}

rtmp {
        server {
                listen 1935;
                chunk_size 4096;
                application live {
                        set $foo bar ;
                        live on;
                        record off;
                        #push rtmp://XXX;
                        #push rtmp://XXX;
                }
        }
}

**Comment by Abhivendra** [comment]
I am inside writing inside http scope only
