### ISSUE TITLE
on_publish  Connection refused

### ISSUE THREAD

**Issue by jjbier** [arut/nginx-rtmp-module#483]
if put the on_publish  I have this error : 2014/10/02 10:21:40 [error] 5312#0: recv() failed (111: Connection refused)

Can help me? 
This is my config file:

https://gist.github.com/jjbier/329fe1e10ca28353e231#file-rtmp-conf

**Comment by isener** [comment]
Hi, could you post some example of it? I know it's a bit old but I have a web API on IIS like localhost:5000, but it does not request to my endpoint which is not hosted by that nginx?
