### ISSUE TITLE
Playback does not work

### ISSUE THREAD

**Issue by dennisjac** [arut/nginx-rtmp-module#5]
I'm trying to get a basic setup working and so far it seems the publishing side is ok. I can stream to the server and I see the publishing stream in the stats. When I try to connect with players though I just get error after a timeout.
ffplay says this:

ffplay -i "rtmp://192.168.2.25/live/myStream live=1"

RTMP_ReadPacket, failed to read RTMP packet header
rtmp://192.168.2.25/live/myStream live=1: Invalid data found when processing input

The config is fairly straightforward:

<pre>
rtmp {
    server {
        listen 1935;
        chunk_size 4000;

        application live {
            live on;
            allow publish all;
            allow play all;
        }
    }
}
</pre>

**Comment by dodolzg** [comment]
same problem, it works well when I set "worker_processes  1"

**Comment by gregorykau** [comment]
> same problem, it works well when I set "worker_processes 1"

I also experienced the same problem on Ubuntu 22.10 Desktop, this change also resolved it for me... Bizarre.
