### ISSUE TITLE
ngx_rtmp_relay_play issue

### ISSUE THREAD

**Issue by cccaochao** [arut/nginx-rtmp-module#529]
Hi:
in  ngx_rtmp_relay_play function:
 739         if (ngx_rtmp_relay_pull(s, &name, target) == NGX_OK) {
 740             continue;
 741         }

I can't understand why is continue when ngx_rtmp_relay_pull() return NGX_OK,I think this is  goto next would be better , beacuse next ngx_rtmp_relay_pull will all failed.Could tell me why?Thank You Very Much.  
My English is Poor,I'm sorry.

**Comment by harlanc** [comment]
hello,have you figured out the problem?
