### ISSUE TITLE
Missing MPD@publishTime attribute

### ISSUE THREAD

**Issue by shankardevy** [arut/nginx-rtmp-module#548]
Below is the mpd file generated using nginx-rtmp. It misses the mandatory MPD@publishTime attribute as described in 5.3.1.2 of  [DASH specification (ISO/IEC 23009-1)](http://standards.iso.org/ittf/PubliclyAvailableStandards/c065274_ISO_IEC_23009-1_2014.zip)

```
<MPD
    type="dynamic"
    xmlns="urn:mpeg:dash:schema:mpd:2011"
    availabilityStartTime="2014-12-22T06:00:43-05:00"
    availabilityEndTime="2014-12-22T06:00:58-05:00"
    minimumUpdatePeriod="PT5S"
    minBufferTime="PT5S"
    timeShiftBufferDepth="PT0H0M0.00S"
    suggestedPresentationDelay="PT10S"
    profiles="urn:hbbtv:dash:profile:isoff-live:2012,urn:mpeg:dash:profile:isoff-live:2011"
    xmlns:xsi="http://www.w3.org/2011/XMLSchema-instance"
    xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 DASH-MPD.xsd">
```

**Comment by perohu** [comment]
I found this probrem too in my MPD file with dashif.org's validator. Maybe this is the reason why Jwplayer7 does not play my Dash stream?
Is there a solution for this?
Thankyou!

**Comment by hufman** [comment]
I found that version 1.2.1 includes this attribute, and it worked for DASH streaming in my test case.
