### ISSUE TITLE
Validate stream keys issued to users?

### ISSUE THREAD

**Issue by gigablox** [arut/nginx-rtmp-module#552]
Let's say upon registering for a stream service you are issued a `streamkey` by some NodeJS API that handles all things user management.

My RTMP server - separate from this NodeJS app has a couple endpoints as well:

Valid user can stream to:
`rtmp://streamservice.com/to/user/streamkey`

Where a client app would consume from:
`rtmp://streamservice.com/from/user`

I want to check that `streamkey` is valid by using the NodeJS API before allowing this user to start publishing his stream live.

I have no idea what that server config would look like for passing the `streamkey` value to the back-end service like this.

Any ideas on ways to go about this dynamically?...Obviously I can't add additional configurations to an nginx server every time a new user joins... 

Some similar discussion in a Google group here:
https://groups.google.com/d/msg/nginx-rtmp/I-h1d_ytXTA/kR4hm2AQJxoJ
https://groups.google.com/d/msg/nginx-rtmp/5Ak3AdZmEqw/2qm71l1QrnoJ

**Comment by maweis1981** [comment]
How to ??

**Comment by yverbin** [comment]
Use on_publish module callback and rtmp url like rtmp://server/app/streamname?sharedkey=authkey.
