### ISSUE TITLE
Nginx Stalls between RTMP Streams

### ISSUE THREAD

**Issue by churchmf** [arut/nginx-rtmp-module#561]
Hey NGINX folks,

I'm experiencing some troubles using NGINX as a RTMP media server. I wish to present a continuous video as a live stream (with up to 60 second latency). However, due to some hardware constraints, I am unable to stream directly from the device. Instead, I can save out X amount of seconds from the device's buffer as an MP4. My solution has been to save X seconds of video from the device then stream that X seconds, rise and repeat. This has been working mostly well, except for stalls (~20 seconds) in the stream between calls.

I have searched far and wide for a solution to this however most of the people experiencing this problem have the collection of videos before starting the stream and can simply concatenate them. 

My running theory is that when a stream finishes, it does an unpublish event in NGINX followed by a timeout period. This prevents the NGINX server from receiving the next publish until the timeout period has expired. I have tried adjusting nginx.config values related to timeouts, respawns, restarts, and publish, but to no avail. 

Pseudocode:
while true
-> capture X seconds of video to "output.mp4" (this takes less than 300ms)
-> stream the MP4 with FFMPEG (takes ~X seconds using -re)

FFMPEG call:
ffmpeg -re -i "output.mp4" -vcodec libx264 -preset veryfast -maxrate 2000k -bufsize 4000k -g 60 -acodec libmp3lame -b:a 128k -ac 2 -ar 44100 -f flv rtmp:/MYSERVER/live/output

I am using JWPlayer client side to watch the video stream, however I experience similar issues using VLC.

I have been trying to figure this out for a few days and I would appreciate any insight an expert to video streaming and NGINX can give. Thank you!

**Comment by yverbin** [comment]
second and subsequent publish events in same stream works correctly. Can you read from your device using pipes ?

**Comment by churchmf** [comment]
unfortunately not to my knowledge. 

Could you elaborate more regarding subsequent publish events working correctly? If I were to stream from ffmpeg to a given rtmp key, then follow that stream with another, I should notice the stream continue with minimal breakage between the two videos? 

Can you recommend any nginx settings that may affect the period of time between when a stream ends and when it can receive frames from a new stream?

Thanks!

**Comment by yverbin** [comment]
in general, you can try the simple experiment in your environment: run streaming from fmle or ffmpeg, connect to server using vlc as rtmp client and measure  time intervals between restreams and that it shows in vlc

**Comment by churchmf** [comment]
I had tried this previously and here are the results I noted:

Connecting to the rtmp server with VLC, I occasionally get the following error: "VLC does not support the audio or video format undf. Unfortunately there is no way for you to fix this." However if I keep trying eventually I can connect.

I notice that VLC stalls in a different fashion than JWPlayer. The stream will play for X amount of seconds until shortly after the ffmpeg call finishes, then the stream will freeze indefinitely even while subsequent ffmpegs run. It seems to be having difficulty handling the recommencement of streaming after the initial publish finishes.

**Comment by churchmf** [comment]
Another thing that may be worth mentioning:

when ffmpeg finishes streaming I receive the following message:
"flv Failed to update header with correct duration."

Additionally, it appears the VLC is receiving some data but the image is still not updating. Here are the statistics:
![image](https://cloud.githubusercontent.com/assets/645987/5747713/73128d00-9bf7-11e4-8c1d-691a48a5c2cb.png)

**Comment by mknwebsolutions** [comment]
I'm unaware from the VLC standpoint, but I know there are timeout directives that can be adjusted that may do the trick @ https://github.com/arut/nginx-rtmp-module/wiki/Directives#timeout

**Comment by mknwebsolutions** [comment]
In fact, this may be what you're looking for -- https://github.com/arut/nginx-rtmp-module/wiki/Directives#drop_idle_publisher

Maybe set this to something high so it expects idle for X time.

**Comment by churchmf** [comment]
Unfortunately I have tried a combination of different options with drop_idle_publishers and timeout directives without any luck. Thanks for the suggestions!

**Comment by pggit7** [comment]
Hi churchmf, were you able to solve your continous streaming issue?

**Comment by churchmf** [comment]
Unfortunately not, and I have since moved on to other projects. Thank you for your support

**Comment by pggit7** [comment]
Have you tried ffmpeg concat muxer to stream to server? It is supposed to stream one video after another.  If it is not of interest to you now, forget it.
