### ISSUE TITLE
Question: Does the directive rtmp_auto_push also distributes the work of HLS creation?

### ISSUE THREAD

**Issue by leandromoreira** [arut/nginx-rtmp-module#570]
We're planing to use this for multiple live streams and `rtmp_auto_push` seems to fit our purpose. My question is the hls creation work is also distributed among the workers? 

`rtmp_auto_push`
Multi-worker live streaming is implemented through pushing stream to *remaining nginx workers*.

**Comment by cccaochao** [comment]
HLS create only at the publish worker.

**Comment by leandromoreira** [comment]
thanks @cccaochao
