### ISSUE TITLE
Accurate fragment splitting

### ISSUE THREAD

**Issue by dusterio** [arut/nginx-rtmp-module#590]
Hello!

Is it possible to force/guarantee fragment duration? As far as I understand from the past issues, hls_fragment option doesn't actually guarantee anything. Eg., in my case the setting is 5 seconds, but fragments come anywhere between 5 and 20 seconds. I tried -force_key_frame option with ffmpeg – it improved the situation somewhat but 50% of fragments are still of wrong length.

Look forward to hearing from you!

**Comment by shaharmor** [comment]
Any update here?

**Comment by arut** [comment]
If you want to force fragment splitting at specific duration, use ``hls_max_fragment`` for this. Normally, fragments are split at keyframes.
