### ISSUE TITLE
availabilityStartTime not constant for dash streaming

### ISSUE THREAD

**Issue by mediocregopher** [arut/nginx-rtmp-module#614]
I initially thought this was a client-side issue, so I opened up https://github.com/Dash-Industry-Forum/dash.js/issues/497, but from that thread I'm lead to believe the issue is on the server-side.

Essentially they client is able to successfully stream a dash stream up until a certain point when the mpd files start having increasing availabilityStartTimes, at which point the client starts repeating the last few parts it received. According to that thread the availabilityStartTime is supposed to be constant. Is that true? And if so is this a bug on the module's end?

**Comment by codenoise** [comment]
I am having the same problem. I made a fork here: https://github.com/codenoise/nginx-rtmp-module.
I am still having the same problem described, but less so. Now the timeshiftBufferDepth is 30 seconds and the availabilityStartTime is constant through the session. Can you test and see if it changes your results? If not, perhaps the dash.js issue needs to be reopened.

**Comment by mediocregopher** [comment]
Thanks so much for the help! :) unfortunately your fork didn't work for me, the dash.js player plays for a few seconds then starts looping over the same spot over and over. I noticed that the startAvailabilityTime starts increasing after a bit still, even with your fork, so maybe that could be a reason? A kind of agree though, I feel like this issue is on dash.js, it doesn't make sense to me that availabilityStartTime shouldn't shift, it seems to me like that value describes the time range for which there is available "footage", and that will change over time as nginx cleans up old parts.

**Comment by codenoise** [comment]
Interesting. How much time passes before the startAvailabilityTime changes? I have a 10 minute stream that I play, and it stays constant for me. I agree with you that it would seem the startAvailabilityTime should change to match the window of availability for the chunks in the manifest.

**Comment by mediocregopher** [comment]
I would guess no more than 10-15 seconds. I'll double check when I get
home. I'm doing an "endless" desktop stream using obs, if that effects
anything.

**Comment by relrix** [comment]
I am also facing the same issue with Dash.js player. The stream will stop after 5-10 seconds and it won't play after that. As #mediocregopher  mentioned - I thought it was a client side issue (dash.js) too ; as stream was playing fine on bitdash player. But I came to know from dash forum that it's because of the "availabilityStartTime". I thought to look for available solution before I start digging the code to create a patch, so ended up on the forum. 

Let us know if we have a patch in progress for the issue, else I am planning to write a patch not to update the "availabilityStartTime". 

Cheers,
Shishir

**Comment by mattpepin** [comment]
Any progress with this issue? I'm having the same problem.

**Comment by mattpepin** [comment]
I decided to try to fix it myself. I created a patch that freezes availabilityStartTime and adjusts timeShiftBufferDepth. It seems to fix the problem for live streams in my case. Feel free to test and use it.

https://github.com/mattpepin/nginx-rtmp-module/commit/c078a7c3e08b5b2cbe74f4694e48e5a1ff372fb3

**Comment by uvbeenzaned** [comment]
@mattpepin That is a great commit! Thanks for doing that! It solved our streaming problem.

**Comment by mediocregopher** [comment]
I'll go ahead and close this, sounds like the problem has been solved. Thanks mattpepin!
