### ISSUE TITLE
exec_pull not working (most likely misconfigured)

### ISSUE THREAD

**Issue by DavidVentura** [arut/nginx-rtmp-module#621]
Hi
I have a local server that runs nginx-rtmp and I'd like to pull it over the internet (so I can record locally and then broadcast).
The local server is working; the remote server can run ffmpeg and view the stream (ran the command manually).

This is the relevant part of my config. Note that I want it to start pulling into /xorg/movie, from remote when the first client connects to /xorg/movie

is this the right way to do it? 
```
        application xorg {
                live on;
                exec_pull ffmpeg -i rtmp://THEHOST:1935/THEAPP/movie -c copy -f flv rtmp://localhost:1935/xorg/movie;
                recorder rec0 {
                        record all;
                        record_path /var/videos/;
                        record_unique on;
                }
                hls on;
                hls_path /tmp/hls;
                hls_fragment 15s;

                dash on;
                dash_path /tmp/dash;
                dash_fragment 15s;
        }
```

**Comment by phongdaohp** [comment]
It working with me, make sure that you have ffmpeg and lib add-on

application stream {
            live on;

            # On every pusblished stream run this command (ffmpeg)
            # with substitutions: $app/${app}, $name/${name} for application & stream name.
            #
            # This ffmpeg call receives stream from this application &
            # reduces the resolution down to 32x32. The stream is the published to
            # 'small' application (see below) under the same name.
            #
            # ffmpeg can do anything with the stream like video/audio
            # transcoding, resizing, altering container/codec params etc
            #
            # Multiple exec lines can be specified.

	    exec_pull ffmpeg -re -i rtmp://localhost:1935/$app/$name -c copy -f flv rtmp://localhost:1935/stream/${name};
            # exec ffmpeg -re -i rtmp://localhost:1935/$app/$name -vcodec flv -acodec copy -s 32x32 -f flv rtmp://localhost:1935/small/${name};
        }

**Comment by DavidVentura** [comment]
You are right. I had a small typo on my ffmpeg command. now it's working. what happens if ffmpeg tries to pull to a source that is not publishing? (We run our video-courses on a given time, but people try to connect before/after)

**Comment by phongdaohp** [comment]
I dont know because I have never try this.

Did you setup rtmp secure link?
