### ISSUE TITLE
Secure links nginx with rtmp not working

### ISSUE THREAD

**Issue by phongdaohp** [arut/nginx-rtmp-module#622]
Hello 

I want secure links nginx with rtmp but it not working.
In my nginx.config I configured as below

http:

 location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
			# set connection secure link
            secure_link $arg_md5,$arg_expires;
			secure_link_md5 "$secure_link_expires$uri$remote_addr hehehehe";

			if ($secure_link = "") {
				return 403;
			}

			if ($secure_link = "0") {
				return 410;
			}
        }

rtmp :
application vod {
            #play /usr/share/nginx/html/video;
			on_play http://localhost;
        }
		
When I play video at http://localhost/test.mp4?md5=YhOgKGEnwNBY3FuN81c7uw&expires=2147483647 It worked, but when I play video in rtmp://45.63.55.167:1935/vod/test.mp4?md5=YhOgKGEnwNBY3FuN81c7uw&expires=2147483647 It not working. 

How can I fix this problem. 

Thanks you all so much.

**Comment by xoceunder** [comment]
He managed to solve the problem

**Comment by phongdaohp** [comment]
I'm fixed

**Comment by misiek08** [comment]
Please tell us how, so following people with same problem can try your
solution.
23 lip 2015 03:53 "Phong Dao" <notifications@github.com> napisał(a):

**Comment by phongdaohp** [comment]
The problem was general token md5 for rtmp. 
rtmp {
    server {
        listen 1935;
        chunk_size 4000;
		notify_method get;
	
	application vod {
			live on;
            play /usr/share/nginx/html;
			on_play http://localhost:8080/; ========> secure_link_md5 "$secure_link_expires$uri$arg_addr secret"; ($uri param is '/' = > use "echo -n '2147483647/ secret' | openssl md5 -binary | openssl base64 | tr +/ -_ | tr -d ="    to general token)
        }
    }
}
http {

	log_format  compression  '$remote_addr - $arg_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for" "$gzip_ratio"'
					  '"Tham so o day: "$secure_link  - $arg_md5 - $arg_expires - $secure_link_expires - $uri';
                      # "GENARAL TOKEN MD5 FOR RTMP"
					  #echo -n '2147483647/ secret' | openssl md5 -binary | openssl base64 | tr +/ -_ | tr -d =
					  # "GENARAL TOKEN MD5 FOR HTTP"
                      #echo -n '2147483647/video.mp4 secret' | openssl md5 -binary | openssl base64 | tr +/ -_ | tr -d =

    server {
        listen 8080;
        server_name localhost;
		gzip on;
        access_log /usr/nginx-access-main.log compression;

        location / {
		
            # set connection secure link
			secure_link $arg_md5,$arg_expires;
			secure_link_md5 "$secure_link_expires$uri$arg_addr secret";

			if ($secure_link = "") {
				return 403;
			}

			if ($secure_link = "0") {
				return 410;
			}
            return 200;
        }


    }
}

If you all have any question, tell me I will help you all fix it.

**Comment by misiek08** [comment]
Thanks for sharing. It will make issues tracker clean in the future.
22 sie 2015 07:14 "Phong Dao" <notifications@github.com> napisał(a):

**Comment by MuhammadMuneeb76** [comment]
Can you figure out this problem?
http://stackoverflow.com/questions/40872880/nginxnode-js-secure-link-not-working
