### ISSUE TITLE
Continous stream

### ISSUE THREAD

**Issue by xCausxn** [arut/nginx-rtmp-module#628]
Hey all,

I was wondering if it was possible to make a continuous stream with changing ffmpeg sources.

Dont really know the best method of doing this or if it is even possible but i thought i would ask here as you allseem to know a lot about the subject of rtmp :P

Looking forward to relies
Kind Regards,
xCausxn

**Comment by misiek08** [comment]
Setup one ffmpeg to listen on udp port, then stream to it from antoher ffmpeg instance. Listening instance should have something like **-i udp://0.0.0.0** set in command line.

**Comment by lavvy** [comment]
On May 24, 2015 3:37 PM, "ministers" <notifications@github.com> wrote:
>
> Hey all,
>.
> I was wondering if it was possible to make a continuous stream with
changing ffmpeg sources.kk

> Dont really know the best . of doing this or if it is even possible butk
thought i would ask here as yo
allseem to know a lot about t suject of rtmp :

**Comment by lavvy** [comment]
Mm
On May 24, 2015 3:37 PM, "xCausxn" <notifications@github.com> wrote:
>
> Hey all,
>
> I was wondering if it was possible to make a continuous stream with
changing ffmpeg sources.
>
> Dont really know the best method of doing this or if it is even possible
k i thought i would ask here as you allseem to know a lot about the subject
of rtmp :P

**Comment by xCausxn** [comment]
@misiek08 How would i make it keep the rtmp output continous if there is no input coming in from the input ffmpeg ?

**Comment by misiek08** [comment]
The **proxy** will stream nothing waiting for input, so you have some time to switch source.

**Comment by xCausxn** [comment]
so FFMPEG > NGINX > FFMPEG > RTMP STREAM SERVER

**Comment by misiek08** [comment]
ffmpeg -> ffmpeg (listening on udp) -> nginx -> whatever/client

2015-05-26 21:01 GMT+02:00 xCausxn <notifications@github.com>:

**Comment by jamescauson** [comment]
Is there a way for it to stream nothing indefinetly :P

**Comment by sergey-dryabzhinsky** [comment]
You could try to:
1. Kill publisher (ffmpeg) with -9 (KILL) signal to prevent it send 'unpublish' status
2. Try to publish into old stream with new ffmpeg
