### ISSUE TITLE
SRS is an optional choice.

### ISSUE THREAD

**Issue by winlinvip** [arut/nginx-rtmp-module#633]
Performance data is [here](https://github.com/ossrs/srs#performance).

## RTMP `SRS = 3 * NginxRTMP`

The data for playing RTMP was benchmarked by [srs-bench](https://github.com/ossrs/srs-bench):

|   Update      |    SRS    |    Clients    |     Type      |    CPU    |  Memory   | Commit        |
| ------------- | --------- | ------------- | ------------- | --------- | --------  | ------------  |
|   2014-12-07  |   2.0.67  |   10k(10000)  |   players     |   95%     |   656MB   |   [code][p12] |
|   2014-12-05  |   2.0.57  |   9.0k(9000)  |   players     |   90%     |   468MB   |   [code][p11] |
|   2014-12-05  |   2.0.55  |   8.0k(8000)  |   players     |   89%     |   360MB   |   [code][p10] |
|   2014-11-22  |   2.0.30  |   7.5k(7500)  |   players     |   87%     |   320MB   |   [code][p9]  |
|   2014-11-13  |   2.0.15  |   6.0k(6000)  |   players     |   82%     |   203MB   |   [code][p8]  |
|   2014-11-12  |   2.0.14  |   3.5k(3500)  |   players     |   95%     |   78MB    |   [code][p7]  |
|   2014-11-12  |   2.0.14  |   2.7k(2700)  |   players     |   69%     |   59MB    |   -           |
|   2014-11-11  |   2.0.12  |   2.7k(2700)  |   players     |   85%     |   66MB    |   -           |
|   2014-11-11  |   1.0.5   |   2.7k(2700)  |   players     |   85%     |   66MB    |   -           |
|   2014-07-12  |   0.9.156 |   2.7k(2700)  |   players     |   89%     |   61MB    |   [code][p6]  |
|   2014-07-12  |   0.9.156 |   1.8k(1800)  |   players     |   68%     |   38MB    |   -           |
|   2013-11-28  |   0.5.0   |   1.8k(1800)  |   players     |   90%     |   41M     |   -           |

## RTC `SRS = 2.5 * Janus`

The RTC benchmark data, by [srs-bench](https://github.com/ossrs/srs-bench/tree/feature/rtc#usage):

|   Update      |    Server     | Clients |    Type  |   CPU    | Memory   | Threads | Commit |
| ------------- | ------------  | ----- | ---------- | -------- | -------- | ----- | --------- |
|   2021-04-07  |   SRS/5.0.3   | 10000 | publishers | ~90% x 32 |  28GB  | 33   | [#2188](https://github.com/ossrs/srs/issues/2188) |
|   2021-04-07  |   SRS/5.0.3   | 3400  | publishers | ~95% x 8 |  6.3GB  | 12   | [#2188](https://github.com/ossrs/srs/issues/2188) |
|   2021-04-07  | Janus/0.10.10 | 1100  | publishers | ~55% x 8 |  169MB  | 1120  | [Crashed](https://github.com/meetecho/janus-gateway/issues/2626) |
|   2021-04-07  |   SRS/5.0.3   | 2000  | publishers | ~95% x 4 |  4.1GB  | 8    | [#2188](https://github.com/ossrs/srs/issues/2188) |
|   2021-03-31  |   SRS/5.0.2   | 1400  | publishers | ~90% x 4 |  3.1GB  | 6    | [#2188](https://github.com/ossrs/srs/issues/2188) |
|   2021-03-31  |   SRS/5.0.2   | 1400  | players    | ~93% x 4 |  1.0GB  | 6    | [#2188](https://github.com/ossrs/srs/issues/2188) |
|   2021-03-31  | Janus/0.10.10 | 700   | publishers | ~80% x 4 |  142MB  | 720  | |
|   2021-03-31  | Janus/0.10.10 | 700   | players    | ~82% x 4 |  283MB  | 720  | |
|   2021-03-31  |   SRS/4.0.87  | 550   | publishers | ~86% x 1 |  1.3GB  | 1    | |
|   2021-03-31  |   SRS/4.0.87  | 800   | players    | ~94% x 1 |  444MB  | 1    | |

> Note: The benchmark tool for Janus is [srs-bench](https://github.com/ossrs/srs-bench/tree/feature/rtc#janus), and startup script by [janus-docker](https://github.com/winlinvip/janus-docker#usage).

## Features

|   Feature     |   SRS     |   NGINX   | CRTMPD    | AMS       |   WOWZA   |    Janus  |
|   ----------- |   ------- |   -----   | --------- | --------  |   ------  |   ------  |
|   RTMP        |   Stable  |   Stable  |   Stable  |   Stable  |   Stable  |   X       |
|   WebRTC      |Experiment |   X       |   X       |   X       |   X       |   Stable  |
|   HLS         |   Stable  |   Stable  |   X       |   Stable  |   Stable  |   X       |
|   HTTP FLV    |   Stable  |   X       |   X       |   X       |   X       |   X       |
|   HLS(aonly)  |   Stable  |   X       |   X       |   Stable  |   Stable  |   X       |
|   HDS         | Experiment|   X       |   X       |   Stable  |   Stable  |   X       |
|   MPEG-DASH   | Experiment|   X       |   X       |   X       |   X       |   X       |
|   SRT         | Experiment|   X       |   X       |   X       |   Stable  |   X       |
|   HTTP Server |   Stable  |   Stable  |   X       |   X       |   Stable  |   X       |
|   GB28181     | Experiment|   X       |   X       |   X       |   X       |   X       |

**Comment by winlinvip** [comment]
My Skype: winterserver

**Comment by level123** [comment]
nginx-rtmp also support multi processes.

**Comment by winlinvip** [comment]
Yep, nginx-rtmp is a great media server, absolutely.
I love this ningx-rtmp, and I refer to nginx-rtmp lots of code to implments SRS.
Nginx-RTMP is a great project, I agree!

I start the SRS and srs-dolphin for some reasons:

1. I want to focus on live streaming, smaller problem domain, smaller problem.
1. I want to use coroutine which can simplify the epoll async callback. SRS 2.0 implements with 80k lines of code, but provides twice features to nginx-rtmp, for example, HDS, Vhost, Edge, HSTRS, HTTP FLV, Ingest, RTSP, Tracable log.....
1. I already work on the live streaming server from 2012, 3years now, and I always maintain the SRS. There is 2986 commits for SRS2, and SRS3 or SRS4 is planing.
1. I want to simplify the process arch, SRS use single process, and SRS-DOLPHIN is a multiple process containser for SRS. This arch only takes 1.7k lines of code to implements the multiple processes, and I belive that this is more easy to maintain.

## Why SRS?

1. Completely rewrite HLS following m3u8/ts spec, and HLS support h.264+aac/mp3.
1. High efficient RTMP deliverying support 7k+ concurrency, vhost based, both origin and edge.
1. Embeded simplified media HTTP server for HLS, api and HTTP flv/ts/mp3/aac streaming.
1. Variety input: RTMP, pull by ingest file or stream(HTTP/RTMP/RTSP), push by stream caster 
RTSP/MPEGTS-over-UDP.
1. Popular internet delivery: RTMP/HDS for flash, HLS for mobile(IOS/IPad/MAC/Android), HTTP 
flv/ts/mp3/aac streaming for user prefered.
1. Enhanced DVR and hstrs: segment/session/append plan, customer path and HTTP callback.
the hstrs(http stream trigger rtmp source) enable the http-flv stream standby util encoder 
start publish, similar to rtmp, which will trigger edge to fetch from origin.
1. Multiple feature: transcode, forward, ingest, http hooks, dvr, hls, rtsp, http streaming, 
http api, refer, log, bandwith test and srs-librtmp.
1. Best maintainess: simple arch over state-threads(coroutine), single thread, single process 
and for linux/osx platform, common server x86-64/i386/arm/mips cpus, rich comments, strictly 
follows RTMP/HLS/RTSP spec.
1. Easy to use: both English and Chinese wiki, typically config files in trunk/conf, traceable 
and session based log, linux service script and install script.
1. MIT license, open source with product management and evolution.

Enjoy it!
