### ISSUE TITLE
Cannot get <video> tag to work. (Dash & HLS)

### ISSUE THREAD

**Issue by leon-wbr** [arut/nginx-rtmp-module#643]
I've tried everything, but the only way I could get my livestream to work was using dash.js, but it's only smooth for the first 30 seconds, then it gets really choppy.

    rtmp_auto_push on;
    
    events { 
    	worker_connections 1024; 
    }

    rtmp {
        server {
                listen 1935;
                chunk_size 4096;

                application live {
                        live on;
                        record off;
                }
    
    	application hls {
                live on;
                hls on;
                hls_path /tmp/hls;
            }
    
    	application dash {
                live on;
                dash on;
                dash_path /tmp/dash;
            }
        }    
        }
    
    http {
        server {
        	listen 8080;
    
        	location /hls {
                # Serve HLS fragments
                types {
		    application/vnd.apple.mpegurl m3u8;
                }
                root /tmp;
                add_header Cache-Control no-cache;
            }
    
        location /dash {
                # Serve DASH fragments
                root /tmp;
                add_header Cache-Control no-cache;
        }
    
    	location /stat {
                rtmp_stat all;

                # Use this stylesheet to view XML as web page
                # in browser
                rtmp_stat_stylesheet stat.xsl;
            }

            location /stat.xsl {
                # XML stylesheet to view RTMP stats.
                # Copy stat.xsl wherever you want
                # and put the full directory path here
                root stat.xsl/;
            }
        }
    }

Stat page also doesn't work.

**Comment by sergey-dryabzhinsky** [comment]
If you are pushing streams into 'live' app then you should put hls and dash options into 'live' app section.

Root path in location '/stat.xsl' should point to directory which contains 'stat.xsl' file.

**Comment by bobgle** [comment]
I got most of the features to work by now, but my streams aren't HTML5, they're flash. Can I use HTML5?

**Comment by sergey-dryabzhinsky** [comment]
Probably for dash you need to merge to your fork/branch this: https://github.com/arut/nginx-rtmp-module/pull/463
HLS supported only by Apple browsers, imho.

**Comment by bobgle** [comment]
I tried it out. I actually compiled my nginx with your fork now - Livestreaming itself is working, I'm using videojs with the dash.js wrapper, etc. - but it's stuttering. Heavily. It's more of a slideshow than anything. Any idea what causes this?

**Comment by sergey-dryabzhinsky** [comment]
What parameters has stream which you try to play via DASH?
Video codec, BPS, frame rate, Audio codec,..
You can also copy some generated files (while pushing) from ```/path/to/tmp/dash``` and check them with ffprobe or mediainfo. And post here some summary info.

**Comment by bobgle** [comment]
The problem was probably with videojs. Works perfectly with bitdash's
player.
