### ISSUE TITLE
Trailing slash for notify module should not be required

### ISSUE THREAD

**Issue by kyleparisi** [arut/nginx-rtmp-module#646]
I was trying to use the on_publish directive and found that it only works if there is trailing slash on a root url.  For example `auth` and `http://auth.vagrant.dev` won't work.  But `auth/` and `http://auth.vagrant.dev/` will work.  Here is the log info using an ip address:

    2015/07/04 14:24:09 [info] 19144#0: *1 notify: publish '172.28.128.4', client: 172.28.128.1, server: 0.0.0.0:1935
    2015/07/04 14:24:09 [info] 19144#0: *1 notify: empty or broken HTTP response, client: 172.28.128.1, server: 0.0.0.0:1935 

working:
 
    2015/07/04 14:33:15 [info] 19560#0: *3 notify: publish '172.28.128.4/', client: 172.28.128.1, server: 0.0.0.0:1935

curling either IP address gets a 200 response.

**Comment by sergey-dryabzhinsky** [comment]
That's because URL from parameter converted inside of nginx into: URL&call=publish&type=xxx
So "auth" becomes "auth&call=publish&type=xxx". Not looking like url, yes? Nginx think so too.

Trailing slash needed by nginx. And full scheme URL too: http(s)://domain/(path/to/something)

**Comment by kyleparisi** [comment]
alrighty
