### ISSUE TITLE
jwplayer sometime cannot connect to nginx-rtmp

### ISSUE THREAD

**Issue by lethanhtrong** [arut/nginx-rtmp-module#65]
Hi arut,
I'm having problem when publish a stream using ffmpeg,playe,publish working fine,however when i refresh page,sometime player cannot connect to nginx-rtmp,test here http://x.x.x.x/player/nginx/www/cam.html.
have any idea?
Thanks.

**Comment by cybermurz** [comment]
Hi arut!
I encountered the same error, after upgrading the operating system while rebuilding the nginx with the module does not give a positive result

nginx version: nginx/1.10.3 (Ubuntu)
OS version: Ubuntu 16.04.6 LTS (Xenial Xerus)
NGINX_RTMP_VERSION  "1.1.4"
