### ISSUE TITLE
ffmpeg freeze 

### ISSUE THREAD

**Issue by jimying** [arut/nginx-rtmp-module#659]
I want to use ffmpeg pull rtsp stream  to nginx hls.
I do long time test,  the ffmpeg freeze,  can't  pull stream any more

the ffmpeg command:
for((;;));do
ffmpeg -rtsp_flags prefer_tcp -i rtsp://myipcame-rtsp-url  \ 
       -vcodec copy -an -f flv rtmp://127.0.0.1/hls/cam;
current_date=`date "+%Y-%m-%d %H:%M:%S"`
echo "=======================================>$current_date stream disconnect, reconnect it....."
sleep 1; 
done

=====
ffmpeg freeze, the process never stop,  If can stop,  my shell script can create a new one to pull stream.

Any one  has the problem?

**Comment by jimying** [comment]
Nobody face this problem?   I think it easy to produce again.
I find this bug  using exec_static  firstly.
Then I use shell command line reproduct it.

**Comment by sergey-dryabzhinsky** [comment]
Can you try to stream some image to check that is no network lag?
```
ffmpeg -re -loop 1 -i ./target/target_image.png -r 24 -vcodec libx264 -f flv "rtmp://127.0.0.1/hls/cam live=1 timeout=0 buffer=0"
```
And wait for freeze.

**Comment by jimying** [comment]
Use this command line,  Not freeze.
But  pull rtsp streaming (tcp),  will freeze

**Comment by jimying** [comment]
OK, I think this is a ffmpeg bug.  I  find a simple way to fix ffmpeg, make
sure that if no stream data for 5 seconds, exit ffmpeg.

Now my shell script work fine.

**Comment by sergey-dryabzhinsky** [comment]
Maybe ip-cam just stop streaming? Like motion detection triggered.
Issue closed?

**Comment by jimying** [comment]
I think change ffmpeg code can meet my need
(pull ip-cam streaming,  when the network problem,  reconnect it ).
So i think i can close this issue.
Anyway, thanks for your reply.
