### ISSUE TITLE
Event when a chunk is recorded

### ISSUE THREAD

**Issue by trongr** [arut/nginx-rtmp-module#664]
So we have the exec_publish / on_publish and exec_publish_done / on_publish_done events when a stream starts and ends. Is there a similar event for when a .ts chunk gets recorded? (I see exec_push / on_update fire periodically and I can set the interval, but is there one that fires precisely when the chunks finished recording?)

**Comment by Classsic** [comment]
I think you can use exec_record_done...https://github.com/arut/nginx-rtmp-module/wiki/Directives#exec_record_done.

**Comment by sergey-dryabzhinsky** [comment]
Yes, ```on_record_done``` / ```exec_record_done``` triggers on every recorded ```.ts``` chunk.
And you need to apply #648 to get ```record_interval``` work.

**Comment by trongr** [comment]
Awesome. Thank you!
