### ISSUE TITLE
Dynamically push/replicate to other servers

### ISSUE THREAD

**Issue by KCastiglione** [arut/nginx-rtmp-module#666]
What is the best way to dynamically replicate a rtmp stream that is getting published, to a different server?

For example when hitting the bandwidth bottleneck for current server, how can we replicate the stream to next nginx-rtmp server so subsequent clients can connect to the next server?

Thanks for a great server!

**Comment by misiek08** [comment]
You setup edge server with pull and point clients to edge's rtmp address.
That's easiest.

2015-08-12 3:17 GMT+02:00 KCastiglione <notifications@github.com>:

**Comment by KCastiglione** [comment]
what is an edge server? can you please give some more details? is it just another rtmp server? thanks!

**Comment by noname007** [comment]
a server mirror @KCastiglione

**Comment by misiek08** [comment]
Just another server with pull directive.

**Comment by KCastiglione** [comment]
thanks @misiek08
