### ISSUE TITLE
How to push streams using their own names

### ISSUE THREAD

**Issue by trongr** [arut/nginx-rtmp-module#672]
If I do:
```
push rtmp://123.12.12.23:1935/live/$name;
```
on origin, then on edge I get a stream called "$name.flv" with the literal dollar sign. How do I make it so that no matter what stream name comes into origin, the same stream name gets pushed to edge?

Thanks!

**Comment by trongr** [comment]
Ah found it. Should've read the sample nginx.conf :)

Doing this:
```
push 123.12.12.23;
```
will push it to the same app and name on edge as origin.

**Comment by noname007** [comment]
if with query param how to do?

**Comment by frangeris** [comment]
@trongr It works like a charm!

This should be added to documentation here https://github.com/arut/nginx-rtmp-module/wiki/Directives#push
