### ISSUE TITLE
Stream "play" only works for some short time

### ISSUE THREAD

**Issue by huglester** [arut/nginx-rtmp-module#679]
Hello everybody.

I start the streaming with: 
```bash
ffmpeg -re -i /home/9hours.m4a -vn -c:a copy -ar 44100 -ac 1 -f flv rtmp://host/live/test1
```

I listen to it with:
```bash
./ffplay -ar 16000 "rtmp://host/live/test1"
```

But when I stop the ffplay and start it again, I sometimes doesn't work anymore.. Sometimes I stop it 2-3 times and I just can't continue. This pc is Debian box, on VPS.

(logs show, that there are multi play requests, but they have no more sound:( ):
pc1 [13/Sep/2015:08:22:03 +0000] PUBLISH "live" "test1" "" - 497076 529 "" "FMLE/3.0 (compatible; Lavf56.25" (15s)
pc2 [13/Sep/2015:08:28:57 +0000] PLAY "live" "test1" "" - 417 13348411 "" "LNX 9,0,124,2" (6m 56s)
pc2 [13/Sep/2015:08:30:18 +0000] PLAY "live" "test1" "" - 373 436 "" "LNX 9,0,124,2" (1m 19s)
pc2 [13/Sep/2015:08:30:43 +0000] PLAY "live" "test1" "" - 373 436 "" "LNX 9,0,124,2" (24s)

Could this be a vps issue? What is the best way to debug this issue?

RTMP config:
```bash
rtmp {
    server {
            listen 1935;
            chunk_size 4096;

            application live {
                    live on;
                    record off;
            }

   }
}
```

nginx was compiled from source, v .1.7.11 (since master branch shows this version as compatible), parameters: `./configure --with-http_ssl_module --add-module=../nginx-rtmp-module-master --with-debug
`

Any ideas where I should dig?

Thanks!

**Comment by sergey-dryabzhinsky** [comment]
You should try set option ```worker_processes 1;```.

**Comment by huglester** [comment]
Hello @sergey-dryabzhinsky , this one works! thanks/spasibo!
