### ISSUE TITLE
Nested mode for recorder?

### ISSUE THREAD

**Issue by Lokki7** [arut/nginx-rtmp-module#680]
Is it possible to save records in subdirectories? Like '/tmp/rec/myStream/24-Apr-13-18-23-38.flv'

**Comment by sergey-dryabzhinsky** [comment]
No.

**Comment by GuillaumeCisco** [comment]
Is it a work in progress ?

**Comment by sergey-dryabzhinsky** [comment]
No.

**Comment by kenjikato** [comment]
@Lokki7 I don't know if this will help you, but you could set up unique recorders that direct your recordings to specific sub directories.

'''
application {
    live on;

    # default recorder
    record all manual;
    record_path /var/rec;
    record_notify on;

    recorder path_1_rec {
        record all manual;
        record_path /var/rec/path_1;
        record_notify on;
    }

    recorder path_2_rec {
        record all manual;
        record_path /var/rec/path_2;
        record_notify on;
    }
}
'''

Then you would call each recorder manually with the specific recorder that places the recording in the sub directory you want.

'''
http://localhost:8080/control/record/start?app=myapp&name=mystream&rec=path_1_rec
'''

**Comment by GuillaumeCisco** [comment]
Doesn't help because we'd like to have the `rec_path` dynamically. Know a way to achieve it?

**Comment by sergey-dryabzhinsky** [comment]
Unfortunately there is no way to do that. By design.

**Comment by sergey-dryabzhinsky** [comment]
You can catch notify on record chuck write end (on_record_done) and move fragment where you like.
