### ISSUE TITLE
RTMP live issue with a Haivision Makito encoder

### ISSUE THREAD

**Issue by akovacs123** [arut/nginx-rtmp-module#681]
I experience issues with a Haivision Makito live encoder connecting to NGINX RTMP. Configurationwise everything seems alright, but the encoder is not able to connect.

Tested with NGINX 1.8.0 (latest stable) RTMP module current git repo. Also tested with nginx 1.7.10 plus latest repo.

Configuration:

```
worker_processes 4;
worker_rlimit_nofile 8192;

user www-data;
pid /var/run/nginx.pid;
error_log /var/log/nginx/error.log debug; # +" debug";

events {
  multi_accept on;
  worker_connections 1024;
}

http {
  include mime.types;
  include /etc/nginx/conf.d/*.http.conf;

  map_hash_bucket_size 128;
  default_type application/octet-stream;

  sendfile on;
  tcp_nopush on;
  keepalive_timeout 65;
  gzip off;

  ## Logs
  ...

  # Include site configuration files
  include /etc/nginx/sites-enabled/*;

} # http

# Multi worker streaming
rtmp_auto_push on;
rtmp_auto_push_reconnect 1s;
rtmp_socket_dir /tmp;

rtmp {

  server {

    listen <ip-address>:1935;
    listen localhost:1935;
    chunk_size 4096;
    notify_method get;

    # Max connections to RTMP engine
    max_connections 200;

    wait_video on;

    # Live test
    application live {
      live on;
      record off;
      allow publish <ip-address>;
      deny publish all;
      allow play all;
    }
      
} # server

} # rtmp
```

With other RTMP encoders, such as Wirecast I am able to connect with no issues.

For Haivision, debug log shows this:

```
2015/09/14 12:16:53 [info] 6492#0: *74 client connected '62.112.213.214'
2015/09/14 12:16:53 [info] 6492#0: *74 connect: app='live' args='' flashver='LNX 10,0,32,18' swf_url='' tc_url='rtmp://<snip>:1935/live' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 62.112.213.214, server: 91.120.59.238:1935
2015/09/14 12:16:54 [info] 6492#0: *74 createStream, client: 62.112.213.214, server: 91.120.59.238:1935
2015/09/14 12:17:08 [info] 6492#0: *74 deleteStream, client: 62.112.213.214, server: 91.120.59.238:1935
2015/09/14 12:17:08 [info] 6492#0: *74 disconnect, client: 62.112.213.214, server: 91.120.59.238:1935
2015/09/14 12:17:08 [info] 6492#0: *74 deleteStream, client: 62.112.213.214, server: 91.120.59.238:1935 ...
```

I can see no publish() call here.

The same for Wirecast (as a working example):

```
2015/09/14 12:49:54 [info] 6492#0: *75 client connected '62.112.213.214'
2015/09/14 12:49:54 [info] 6492#0: *75 connect: app='live' args='' flashver='Wirecast/FM 1.0 (compatible; FM' swf_url='' tc_url='rtmp://<snip>:1935/live' page_url='' acodecs=1026 vcodecs=128 object_encoding=0, client: 62.112.213.214, server: 91.120.59.238:1935
2015/09/14 12:49:54 [info] 6492#0: *75 createStream, client: 62.112.213.214, server: 91.120.59.238:1935
2015/09/14 12:49:54 [info] 6492#0: *75 publish: name='222222' args='' type=LIVE silent=0, client: 62.112.213.214, server: 91.120.59.238:1935
...
```

I made captures for both encoders:

https://dl.dropboxusercontent.com/u/28051694/nginx-rtmp_captures.zip

First a successful NetConnection.Connect.Success is achieved by both encoders. The difference is that Wirecast starts off with ReleaseStream(), FCPublish() and createStream() calls in a single RTMP packet. In contrast, Haivision starts with a createStream() then an FCPublish() follows in the next packet, then an FCUnPublish() occurs immediately.

Thanks.

**Comment by sergey-dryabzhinsky** [comment]
Try ```worker_processes 1;``` first.

**Comment by dbussert** [comment]
I have the same problem with the Makito X, logs below.  We ended up setting the Makito to MPEG-TS and using ffmpeg to publish via RTMP.

Makito X with no publish
```
2015/06/09 10:03:18 [info] 14577#0: *10 client connected '10.70.5.50'
2015/06/09 10:03:18 [info] 14577#0: *10 connect: app='myapp' args='' flashver='LNX 10,0,32,18' swf_url='' tc_url='rtmp
://XX.XX.XX.XX:1935/myapp' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 10.70.5.50, server: 0.0.0.0:1935
2015/06/09 10:03:19 [info] 14577#0: *10 createStream, client: 10.70.5.50, server: 0.0.0.0:1935
2015/06/09 10:03:35 [info] 14577#0: *10 deleteStream, client: 10.70.5.50, server: 0.0.0.0:1935
```

ffmpeg with a publish
```
2015/06/09 09:39:21 [info] 14577#0: *6 client connected '10.70.6.130'
2015/06/09 09:39:21 [info] 14577#0: *6 connect: app='myapp' args='' flashver='FMLE/3.0 (compatible; Lavf56.25' swf_url
='' tc_url='rtmp://XX.XX.XX.XX:1935/myapp' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 10.70.6.130, ser
ver: 0.0.0.0:1935
2015/06/09 09:39:21 [info] 14577#0: *6 createStream, client: 10.70.6.130, server: 0.0.0.0:1935
2015/06/09 09:39:21 [info] 14577#0: *6 publish: name='mystream' args='' type=live silent=0, client: 10.70.6.130, serve
r: 0.0.0.0:1935
```

**Comment by sergey-dryabzhinsky** [comment]
It's because there is no FCPublish/FCUnpublish handlers.
Which usualy sends 'NetStream.Publish.Start' / 'NetStream.Unpublish.Success' response.
After that - encoders will send publish / unpublish commands.

**Comment by akovacs123** [comment]
Sergey. I gave it a try, does not work either. Same effect.

However, I tried with the product of the same company called Kulabyte, which has maybe more complete RTMP implementation, and it worked fine.

Sergey, can you tell me, that in this situation:
- Haivision Makito does something wrong. If yes, I can try to have it fixed with the vendor.
- NGINX lacks something. In this case, any chance to improve the module on the NGINX side?

Thank a lot.

**Comment by sergey-dryabzhinsky** [comment]
Haivision just doing streaming with strict rules. Probably following some Adobe recomendations.
But FC(un)Publish commands not required for publishing - FMLE working without hanblers in nginx-rtmp.

If you want to try - in my fork I have created that handlers. You are not alone: https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/issues/38

**Comment by akovacs123** [comment]
Sergey, great, thanks. I tried to compile it with Nginx 1.8.0, but it fails:

```
/home/akovacs/temp/nginx-1.8.0/nginx-rtmp-module-fcpublish//ngx_rtmp_send.c: In function ‘ngx_rtmp_create_fi’:
/home/akovacs/temp/nginx-1.8.0/nginx-rtmp-module-fcpublish//ngx_rtmp_send.c:932:5: error: pointer targets in passing argument 1 of ‘sprintf’ differ in signedness [-Werror=pointer-sign]
In file included from src/os/unix/ngx_linux_config.h:23:0,
                 from src/core/ngx_config.h:26,
                 from /home/akovacs/temp/nginx-1.8.0/nginx-rtmp-module-fcpublish//ngx_rtmp_send.c:8:
/usr/include/stdio.h:361:12: note: expected ‘char * __restrict__’ but argument is of type ‘u_char *’
/home/akovacs/temp/nginx-1.8.0/nginx-rtmp-module-fcpublish//ngx_rtmp_send.c:934:5: error: pointer targets in passing argument 1 of ‘sprintf’ differ in signedness [-Werror=pointer-sign]
In file included from src/os/unix/ngx_linux_config.h:23:0,
                 from src/core/ngx_config.h:26,
                 from /home/akovacs/temp/nginx-1.8.0/nginx-rtmp-module-fcpublish//ngx_rtmp_send.c:8:
/usr/include/stdio.h:361:12: note: expected ‘char * __restrict__’ but argument is of type ‘u_char *’
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/nginx-rtmp-module-fcpublish/ngx_rtmp_send.o] Error 1
make[1]: Leaving directory `/home/akovacs/temp/nginx-1.8.0/nginx-1.8.0'
make: *** [build] Error 2
```

**Comment by akovacs123** [comment]
Sergey, your fix works as expected. Makito live streaming works out-of-the-box. Thank you very much.

Any chance that this fork will be part of the RTMP module mainline? Thanks indeed!

**Comment by sergey-dryabzhinsky** [comment]
Yeah, I'll fix type conversion.

About my fork - don't know. @arut seems like not have much time for code review.

**Comment by akovacs123** [comment]
Thanks. I close the issue.

**Comment by emersonian** [comment]
I have a docker image with this patch up at https://hub.docker.com/r/emersonian/nginx-rtmp-haivision which has been stable for over six months in a production environment with Haivision encoders.

Thank you again to @sergey-dryabzhinsky for this fix!
