### ISSUE TITLE
Is there an API to CRUD pull stream?

### ISSUE THREAD

**Issue by sidneyvav** [arut/nginx-rtmp-module#689]
I'm trying to be able to add a stream to the pull list, but I can't restart the service everytime it's done.

I know I'm able to start/stop recording via HTTP.

Is there an API to CRUD pull stream?

**Comment by misiek08** [comment]
There's not such feature. You can make yourself service that will run ffmpeg processes to pull stream and stream to nginx.

**Comment by sidneyvav** [comment]
I'll give it a try!

If I get it, I'll make a pull request

**Comment by misiek08** [comment]
If you wonna make a pull request then make CRUD using internal functions of this module. Without calling ffmpeg directly.
