### ISSUE TITLE
I have a big Problem with the Stats Page!!!

### ISSUE THREAD

**Issue by Pc3ooT** [arut/nginx-rtmp-module#692]
So my Config is on Nginx 1.9.4 whith Secure und Rtmp Module built Sep 21 2015 22:58:14 gcc 4.7.2 (Debian 4.7.2-5) 
rtmp_auto_push on;
rtmp {
    server {
        listen 1935; 
		idle_streams off;
		access_log  off;
		notify_method get;
        application live {
			allow play all;
			deny play all;
		    live on;
			allow publish all;
			deny publish all;
			on_play http://localhost:8880/securecheck;
			on_publish http://XXXXXXXXXXXX/auth.php;
}
}
}

and the stats page shows after 1 min so bei 15 live Streams
Accepted: 3059305 <-- confuse
http://prntscr.com/8ksqdf

What is the Problem?

**Comment by deluxor** [comment]
How many workers do ou have on your nginx.conf ?

**Comment by Pc3ooT** [comment]
i have 
worker_processes  8;
and 
events{
worker_connections  1024;
#accept_mutex off;
}

**Comment by Pc3ooT** [comment]
What can i do?
this is criticat i can not corectly check the statistik from rtmp

**Comment by campones** [comment]
could you share with us the content of your on_play security nginx rules?

thanks

**Comment by Pc3ooT** [comment]
what has the on_play security feature to do with my problem?

**Comment by campones** [comment]
nothing in fact, I was just asking, it could interest me.

about your problem, I have the same.. everytime you refresh the stat's page, you see a single worker, and therefore not all the streams.. but well, I can live with this.  
Note that for rtmp streams, it is a real problem as you might need to refresh the player page to actually grab the streams you expect. If you hit the wrong worker.. then black screen.

**Comment by campones** [comment]
thx for sharing ;)

**Comment by misiek08** [comment]
You should use single worker and maybe origin-edge setup (even on single machine). Then you need to merge stats from those instances.

Multi_worker won't work good, because nginx's approach to worker stack wasn't made for streaming solutions with shared stats page like here. It was http server at the beginning :)

**Comment by sergey-dryabzhinsky** [comment]
Try ```worker_processes 1;```. It should help.

**Comment by Pc3ooT** [comment]
Thx it works now
