### ISSUE TITLE
exec issue

### ISSUE THREAD

**Issue by christophe-bernard** [arut/nginx-rtmp-module#693]
Hi,

I'm trying to execute exec for transcoding, first with long commands, then I tried with very basics ones, as my itinital try failed :

...
application big {  
    live on;  
    exec_push /usr/bin/ffmpeg -re -i rtmp://localhost:1935/$app/$name -vcodec flv -acodec copy -s 32x32 -f flv rtmp://localhost:1935/small/${name} 2>>/var/log/ffmpeg/${name}.log;
}  
application small {  
    live on;
    hls on;
    hls_path /var/www/hls;
}
...

I tried :
- env PATH;
- full path for ffmpeg
- echoing the command : exec_publish bash -c "echo ..command.. >> /tmp/command";

The commands runs successfully manually, but nothing happens : no transcoded files, nor logs (/var/log/ffmpeg).

Can you advise ?
Thanks,
Chris

**Comment by christophe-bernard** [comment]
Actually, it was related to a ffmpeg linking issue (dependencies)

**Comment by soufrk** [comment]
Not opening the issue, but a question to @christophe-bernard , tried doing the same. Works fine except that there is no video displayed, but it shows being buffered in player. I guess there is some alterations need to be made in ffmpeg command. Can you suggest anything?

**Comment by christophe-bernard** [comment]
It looks like you have an issue with the video track.
Activate the record directive, and analyse the recorded file.
You can also use another codec (H264) :

**Comment by soufrk** [comment]
No, the source files were not the issue. I tweaked the ```-vcodec``` option in ```exec_push```, and it is working fine now.
