### ISSUE TITLE
Is this alive and safe?

### ISSUE THREAD

**Issue by Tralapo** [arut/nginx-rtmp-module#699]
I started to use nginx-rtmp on a development server these days and I'm quite happy with it. But I don't know if it is save to go public with this?

It feels like this module is left alone in the dark. The project blog hasn't been updated in over a year and commits aren't very common either.

I do see issues being closed, but never by @arut. Is this module still being maintained and would it be safe to use in a live environment, or is it slowly dying? That would be a shame.

**Comment by campones** [comment]
it works extremely fine but yes, the owner isn't very active at the moment

**Comment by Tralapo** [comment]
@campones Thanks for helping out. I indeed do find the current release acting very stable and working OK. But it would be a shame if I ditch the (very pricy) Wowza license en start using this in the production environment, to only find out this will break when a new Nginx version is arriving.

How likely would that be?

**Comment by campones** [comment]
everytime i reinstalla new server, i use the last nginx mainline version, not the stable one. Didn't meet issues yet (ubuntu14)
