### ISSUE TITLE
FMLE multistream

### ISSUE THREAD

**Issue by ashum81** [arut/nginx-rtmp-module#71]
Не получается настроить работу мульти-битрейтового потока. Использую Flash Media Live Encoder 3.2. Создаю два потока на адрес rtmp://x.x.x.x/live с именем livestream%i
В логе FMLE:
Mon Sep 17 2012 17:42:14 : Primary - Reconnected to FMS/3,0,1,123
Mon Sep 17 2012 17:42:17 : Primary - Stream[livestream1] Status: Success
Mon Sep 17 2012 17:42:17 : Primary - Stream[livestream1] Status: NetStream.Publish.Start
Mon Sep 17 2012 17:42:17 : Primary - Stream[livestream2] Status: Success
Mon Sep 17 2012 17:42:17 : Primary - Stream[livestream2] Status: NetStream.Publish.Start
Mon Sep 17 2012 17:42:17 : Session Started
Mon Sep 17 2012 17:42:18 : Audio Encoding Started 
Mon Sep 17 2012 17:42:18 : Video Encoding Started 
В статистике на сервере вижу только поток livestream1.
И подключиться плейером могу только к первому потоку (при этом звук идет ненормальный, булькающий). На втором потоке flowplayer крутит колесом.
Так было в конфигурации с одним потоком nginx.

Пробовал включать многопоточную конфигурацию с параметром  rtmp_auto_push on;
При этом лог ошибок nginx:
2012/09/17 18:27:44 [error] 22255#0: *4071 auto_push: connect failed: slot=1 pid=21403 socket='unix:/tmp/nginx-rtmp.1'url='unix:/tmp/nginx-rtmp.1' name='livestream2', client: 212.49.102.22, server: 0.0.0.0:1935
2012/09/17 18:27:44 [error] 22255#0: *4071 auto_push: connect failed: slot=2 pid=21404 socket='unix:/tmp/nginx-rtmp.2'url='unix:/tmp/nginx-rtmp.2' name='livestream2', client: 212.49.102.22, server: 0.0.0.0:1935
2012/09/17 18:27:44 [error] 22255#0: *4071 auto_push: connect failed: slot=3 pid=22334 socket='unix:/tmp/nginx-rtmp.3'url='unix:/tmp/nginx-rtmp.3' name='livestream2', client: 212.49.102.22, server: 0.0.0.0:1935
2012/09/17 18:27:44 [error] 22255#0: *4071 auto_push: connect failed: slot=1 pid=21403 socket='unix:/tmp/nginx-rtmp.1'url='unix:/tmp/nginx-rtmp.1' name='livestream2', client: 212.49.102.22, server: 0.0.0.0:1935
2012/09/17 18:27:44 [error] 22255#0: *4071 auto_push: connect failed: slot=2 pid=21404 socket='unix:/tmp/nginx-rtmp.2'url='unix:/tmp/nginx-rtmp.2' name='livestream2', client: 212.49.102.22, server: 0.0.0.0:1935
2012/09/17 18:27:44 [error] 22255#0: *4071 auto_push: connect failed: slot=3 pid=22334 socket='unix:/tmp/nginx-rtmp.3'url='unix:/tmp/nginx-rtmp.3' name='livestream2', client: 212.49.102.22, server: 0.0.0.0:1935

**Comment by nesale** [comment]
И еще 2 года прошло. Поддерживаю, очень важная функциональность. Также готов осуществлять все стороннее тестирование.

**Comment by ashum81** [comment]
Я вышел из ситуации трансляцией одного потока в максимальном качестве, а весь транскодинг в меньшие битрейты делаю уже на сервере через ffmpeg. Это, конечно, увеличивает нагрузку на сервер и дорого масштабируется из-за стоимости серверных мощностей. Кодировать на стороне клиента мне было бы дешевле.
