### ISSUE TITLE
a play problem with multi work

### ISSUE THREAD

**Issue by noname007** [arut/nginx-rtmp-module#714]
hi this is my nginx conf 

https://gist.github.com/noname007/7d9c98efd9c4b51c1488

i push a stream use obs, and i found it was handled by the worker which pid is the 28883 by the ngx log.

when i play this steam by ffplay ,if the connection was handled by the same pid  with the push ,it could work normally ,otherwise ,i will recive the resulte : 

![rtmp-1](https://cloud.githubusercontent.com/assets/8514816/10875356/9bb8895c-816c-11e5-8d23-2e433aa66a16.png)

buf if use the Directive `rtmp_auto_push on;` nothing will happen,and ervething will work well.

i want to kown why this will happen?

sorry to my weak english！

**Comment by cccaochao** [comment]
看日志,这路流是否通过auto_push成功推到其他进程.

**Comment by noname007** [comment]
@cccaochao rtmp_auto_push on; 使用这个命令后，就没有问题了，不使用这个命令就这个问题。但是这个命令不是只是用来提升服务器性能的吗？

**Comment by cccaochao** [comment]
不是的，这个命令是用来在多进程之间转发流的，因为推流只会推到某一个进程，但是其他进程没有，所以要auto_push

**Comment by noname007** [comment]
@cccaochao 那就是说多个进程之间是无法共享到视频流信息的，或者说，其他的进程不会自动的去拉这个流，如果有多个worker 就必须启用这个命令，不然就会出现这个问题?


the worker group could not share the stream info ,or the other worker could not automatic pull the stream from the workder building the connection with push side ,so when the worker more than one ,i have to add this
`rtmp_auto_push on;`
directive to avoid  the above problem?

**Comment by cccaochao** [comment]
you are right.

**Comment by noname007** [comment]
@cccaochao thks
