### ISSUE TITLE
VOD MpegDASH & HLS adaptive bitrate streaming

### ISSUE THREAD

**Issue by DavidGrahambell** [arut/nginx-rtmp-module#715]
Hi,

How can I perform adaptive bitrate streaming with nginx-rtmp-module for VOD HLS & MpegDASH format?

R.

**Comment by rjbaker** [comment]
Not tried this, but currently investigating: http://nginx-rtmp.blogspot.co.uk/2013/07/hls-variant-playlist.html Monitor bandwidth on the client and switch streams dynamically.

**Comment by DavidGrahambell** [comment]
Yes. I saw it as well but I think it's only for live streaming.. I need it for VOD streaming..

**Comment by sergey-dryabzhinsky** [comment]
It's not the job for nginx-rtmp. Not VOD.
You need to recode source video to several formats, make chunks, playlists.
Or just play prepared mp4/flv via nginx http modules.

**Comment by DavidGrahambell** [comment]
Thanks. I do not mean making chunks. It's about calculating user's bw speed and adjusting bitrate. Yeah it seems to be an extra job since many important developments have been still waiting..

**Comment by rjbaker** [comment]
HLS VOD appears to be a premium feature of Nginx+. Arut (owner of this repo) developed it for them, so don't expect to see it here any time soon :-1: https://www.nginx.com/products/streaming-media-delivery/
