### ISSUE TITLE
When pull implemented no streaming occurs

### ISSUE THREAD

**Issue by ryanpager** [arut/nginx-rtmp-module#716]
So im having a weird issue, and I cant seem to figure it out. I have 2 servers behind a load balancer on AWS EC2 & ELB respectively. Both servers are set up with the same config, but with different pulls as follows:

```
worker_processes  1;
user        root;
#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;
#pid        logs/nginx.pid;

events {
  worker_connections  1024;
}

# Http Server
http {
  include             mime.types;
  default_type        application/octet-stream;
  sendfile            on;
  keepalive_timeout   65;

  server {
    listen    80;
    server_name localhost;

    location /stat {
      rtmp_stat all;
      rtmp_stat_stylesheet recording-stats.xsl;
    }

    location /recording-stats.xsl {
      root /var/www/recording-stats;
    }
  }
}

# RTMP Server
rtmp {
  server {
    listen 1935;
    chunk_size 8192;

    application live {
      live on;
      meta copy;
      sync 10ms;
      wait_video on;
      publish_notify on;

      # pull from other server
      # pull rtmp://<server_ip>:1935/live;

      # default recorder
      record all;
      record_path /tmp/recordings;
      record_suffix .flv;
      record_unique off;
      record_append on;
    }
  }
}
```

The idea is as a new stream come in one 1 server, it is rebroadcast to the other server...and vice versa.

###### Issue 1

I got this working using "push" but it was causing an infinite loop of streams going between the 2 servers. If there is a way to not rebroadcast the stream if its been pushed from an external server, that fixes this whole thing.

###### Issue 2

When I use "pull" instead of "push", all the streams show up in /stats...however they never have any bitrate (no broadcasting). The second I remove the pull, everything is perfect on that 1 server.

Any ideas on this -- im pretty stumped.

**Comment by cccaochao** [comment]
you could get working with two application.like this,
 A SERVER:
application live{
      on_publish http://127.0.0.1;
}
 then,you could setup  http rewrite that   judge by the client addr,if the addr is your annother server,your http server return 200,otherwise,rewrite to your server ip。

**Comment by sergey-dryabzhinsky** [comment]
I think you need to rethink idea.
Usually system builds like:
- one server for incoming publishers, recording, and it's a node1 for pulling by everyone
- many balancers - node[2-N], pulls from node1 and stream to everyone

**Comment by ryanpager** [comment]
@sergey-dryabzhinsky Great idea -- this is essentially what I did, and it works great now. Thanks a bunch!

**Comment by sergey-dryabzhinsky** [comment]
Good to know.
Please close this ticket if problem is resolved.

**Comment by ryanpager** [comment]
@sergey-dryabzhinsky Thanks again! Closed.
