### ISSUE TITLE
Nginx-rtmp play live stream will be dropped frames with 4G network

### ISSUE THREAD

**Issue by chenpx718** [arut/nginx-rtmp-module#718]
Server on Windows 7, play RTMP protocol live stream will be dropped frames with 4G network，but play HLS is ok.
Server on Ubuntu，not have this problem.

my nginx.conf

        rtmp {
                server {
                        listen 1937;
                        chunk_size 4096;
                        application hls {
                            live on;

                            # sample HLS
                            hls on;
                            hls_path ./tmp/hls;
                            hls_sync 100ms;
                            hls_fragment 1500ms;
                            hls_playlist_length 10s;
                          }
            }
        }

error.log

        2015/11/06 14:23:26 [debug] 8572#3448: *5 live: rel video packet delta=12
        2015/11/06 14:23:26 [debug] 8572#3448: *5 RTMP drop message bufs=129, priority=2

**Comment by cccaochao** [comment]
try increase out_queue value to decline  drop messages.

**Comment by chanpx** [comment]
hello @cccaochao 
when I increase the out_queue value to 1024*1024, there is no frame dropping, but playback RTMP with 4G network is not smooth.
In the same environment, I use FMS as server, playback RTMP with 4G network is smooth.

**Comment by cccaochao** [comment]
Try set ack_window and chunk_size again.

**Comment by chanpx** [comment]
@cccaochao  
I set ack_window and chunk_size to another value, but the problems play RTMP with 4G network is no smooth still exist.

**Comment by sergey-dryabzhinsky** [comment]
Try to disable IPv6 on Windows 7 in network adapter settings.

**Comment by chanpx** [comment]
@sergey-dryabzhinsky  

I disabled ipv6, but the problem still exists.
