### ISSUE TITLE
Select stream to push

### ISSUE THREAD

**Issue by Tralapo** [arut/nginx-rtmp-module#731]
I have several different incoming streams, is it possible to select which of them are pushed to, for example, YouTube with the push directive?

I tought maybe I have to create several applications (live1, live2), but that doesn't seem to work either, because nginx won't allow me to use /tmp/hls for all of them at the same time to stream hls.

**Comment by Tralapo** [comment]
Such a shame this repo is left out alone in the dark..

**Comment by SEAPUNK** [comment]
@Tralapo There's a newer, more maintained fork where you can post the issue: https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/

**Comment by SEAPUNK** [comment]
Sergey sometimes comments on issues here too, though.

**Comment by Tralapo** [comment]
Wow, looks nice. Will take a look at that.

**Comment by losywee** [comment]
Awesome.
