### ISSUE TITLE
Screenshot support under multi workers

### ISSUE THREAD

**Issue by Bingnan** [arut/nginx-rtmp-module#736]
Hi, @arut 
First, thanks for your great work on nginx-rtmp module!

My question is:

I want to use the HTTP『control module』to send command to nginx-rtmp server to capture a screenshot:

my nginx.conf:

recorder snapshot {
    record keyframes manual;
    record_max_frames 1;
    record_path /tmp/snapshot;

    exec_record_done /usr/local/ffmpeg/2.8/bin/ffmpeg -i /tmp/snapshot/$name.flv -vframes 1 -an -f rawvideo -ss 00:00:00 -y -f image2 /tmp/snapshot/$name.jpg;
}

then I will send HTTP request to capture a screenshot:

curl "http://127.0.0.1:8080/control/record/start?app=myapp&name=mystream&rec=snapshot"

it works great under one worker model, but under multi workers model, it failed often, maybe in 10 times  just success one time(when I set 4 workers).

is there any suggestion? Thanks in advance!

Regards!
Bingnan

**Comment by misiek08** [comment]
Using multiple workers produces many bugs and it's not recommended.
Maybe you can setup master nginx with single worker and make screenshot on
it and setup second nginx pulling from master and set multiple workers on
it?

**Comment by Bingnan** [comment]
Thank you @misiek08  seems the HTTP 『control module』don't support multi worker very well, I will not  use it this way then. and thanks for your good suggestion~
