### ISSUE TITLE
stop/remove all publisher when new one connects

### ISSUE THREAD

**Issue by huglester** [arut/nginx-rtmp-module#749]
Hello!

Is there any way to remove all publishers (if any) when new one connects?

I have some protected entries, when user can publish  a stream.
But sometimes some stuff timeouts and user then re-publishes the stream and it is told that 'Already publishing', which timeouts very slowly.

Any ideas?

Thank you

**Comment by oferh** [comment]
Hi @huglester  can you specify how did you solve it?

**Comment by huglester** [comment]
I moved from that project for a while. But what I last found that there is a 'controls' thing. You could send post a request there before publishing
