### ISSUE TITLE
Cannot configure nginx with rtmp module

### ISSUE THREAD

**Issue by nitsuj102284** [arut/nginx-rtmp-module#752]
I have installed nginx with the rtmp module a few times, but now I try to setup a new server, and I am unable to install it. I am using Ubuntu 14.04 with these steps: https://www.vultr.com/docs/setup-nginx-on-ubuntu-to-stream-live-hls-video. These are the same steps that I successfully have used before.

When I run 'make', I receive a stream of errors, such as:
	
-o objs/src/core/ngx_string.o \
		src/core/ngx_string.c
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -I../nginx-rtmp-module -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs \

When I run make install, I receive this output:
make -f objs/Makefile install
make[1]: Entering directory `/home/dhc-user/working/nginx-1.8.0'
test -d '/etc/nginx/' || mkdir -p '/etc/nginx/'
test -d '/usr/sbin' 		|| mkdir -p '/usr/sbin'
test ! -f '/usr/sbin/nginx' 		|| mv '/usr/sbin/nginx' 		'/usr/sbin/nginx.old'
cp objs/nginx '/usr/sbin/nginx'
test -d '/etc/nginx' 		|| mkdir -p '/etc/nginx'
cp conf/koi-win '/etc/nginx'
cp conf/koi-utf '/etc/nginx'
cp conf/win-utf '/etc/nginx'
test -f '/etc/nginx/mime.types' 		|| cp conf/mime.types '/etc/nginx'
cp conf/mime.types '/etc/nginx/mime.types.default'
test -f '/etc/nginx/fastcgi_params' 		|| cp conf/fastcgi_params '/etc/nginx'
cp conf/fastcgi_params 		'/etc/nginx/fastcgi_params.default'
test -f '/etc/nginx/fastcgi.conf' 		|| cp conf/fastcgi.conf '/etc/nginx'
cp conf/fastcgi.conf '/etc/nginx/fastcgi.conf.default'
test -f '/etc/nginx/uwsgi_params' 		|| cp conf/uwsgi_params '/etc/nginx'
cp conf/uwsgi_params 		'/etc/nginx/uwsgi_params.default'
test -f '/etc/nginx/scgi_params' 		|| cp conf/scgi_params '/etc/nginx'
cp conf/scgi_params 		'/etc/nginx/scgi_params.default'
test -f '/etc/nginx/nginx.conf' 		|| cp conf/nginx.conf '/etc/nginx/nginx.conf'
cp conf/nginx.conf '/etc/nginx/nginx.conf.default'
test -d '/var/run' 		|| mkdir -p '/var/run'
test -d '/var/log/nginx' || 		mkdir -p '/var/log/nginx'
test -d '/etc/nginx//html' 		|| cp -R html '/etc/nginx/'
test -d '/var/log/nginx' || 		mkdir -p '/var/log/nginx'
make[1]: Leaving directory `/home/dhc-user/working/nginx-1.8.0'

**Comment by macstr1k3r** [comment]
you haven't pasted anything of value here. The "errors" are not errors but just a single half copied line of the compiler doing its job.

**Comment by nitsuj102284** [comment]
This is not an error?
cc -c -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -I../nginx-rtmp-module -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs \

That is when running the 'make' command. As I said, I get a whole string of errors like these with the 'make' command.

**Comment by macstr1k3r** [comment]
That is not and error.

That is the C compiler (cc) being configured to compile some files with the -Werror compilation flag.

What should actually happen is make should output a bunch of lines like that one and compile everything that should be compiled.

make install should make all the needed folders and copy all the compiled binary files, the demo config files etc...

try typing nginx and see what happens

**Comment by nitsuj102284** [comment]
Yes, that is what I try after every attempt. It always said something to the affect of using apt-get to install nginx.

**Comment by AlexRevin** [comment]
On Ubuntu your default user is not root and you cannot run sbin commands with it.
Try ```sudo nginx```

**Comment by nitsuj102284** [comment]
I was using sudo. And I have used 'sudo -i' to login as root to install. Each time, unable to install.

**Comment by nitsuj102284** [comment]
This is the error that I receive when I type in 'nginx' after running the configure, make and make install.
[emerg] getpwnam("nginx") failed


I do not know why I have this problem on multiple servers/multiple attempts. I was able to install this without incident only two weeks ago.

**Comment by AlexRevin** [comment]
Did you try setting user to nobody in nginx conf?

**Comment by nitsuj102284** [comment]
Yes. Still does not work. 'apt-get install nginx' works, but not compiling it from source.

**Comment by nitsuj102284** [comment]
I am not sure what happened, but a clean install of Ubuntu, and it works.
