### ISSUE TITLE
Rewind live stream

### ISSUE THREAD

**Issue by AlexRevin** [arut/nginx-rtmp-module#756]
Hello guys

Such an idea came on my mind: is it possible to rewind a live hls/dash stream and continue watching from some point in the past?

I see it is possible to turn .ts segments cleanup off, so that past ones can be accessed. But how to handle .m3u8 playlist?

Should it be programmatically generated for each request using the timestamp? Any examples? Any forks implementing that?

It does not seem like a hard thing to do, just wanted to get your feedback or maybe ideas.

**Comment by misiek08** [comment]
For such purpose and multi-bitrate HLS I've implememted own m3u8 generator
and it's possible. You should make your own handler too, because at some
point you will need a feature that is not available and instead of C code
you will have to write something easier in your favorite language.
25 sty 2016 11:09 "Alex" <notifications@github.com> napisał(a):

**Comment by AlexRevin** [comment]
AFAIK multi-bitrate is supported in this module.

There's also @sergey-dryabzhinsky fork, which implements http callbacks on each m3u8 regeneration. So writing custom m3u8 does not seem fairly complicated.

I am more interested in how rewinding organized: should re-winded stream be updated with newer segments on the fly as-well? How to determine to what exact segment the user have rewinded in live stream (time shift)? Well, maybe any other gotchas?

**Comment by misiek08** [comment]
Built in solution is very fixed, not really flexible and I had some weird
playlist generated (missing segments). IIRC you can add segments in front
of playlist, so user can go live at any moment. Player will just continue
to play at its own peace at timestamp.

**Comment by AlexRevin** [comment]
Looks like it's already implemented with "event" playlist type.
Thanks for your feedback!
