### ISSUE TITLE
If the publisher connection flaps, nginx rtmp needs a reboot to work well

### ISSUE THREAD

**Issue by ghost** [arut/nginx-rtmp-module#77]
How to try to reproduce: 
- Publish to the stream with Adobe Flash Live Media Encoder with the default auto-reconnect mode enabled
- Turn off for 10 seconds the wifi or eth of the encoder machine in order to simulate a little network flap
- Issue comes here: Adobe FLME will reconnect to nginx rtmp, but no data packet will be streamed (accepted by nginx) anymore until a nginx reboot.

Please try because maybe is just a problem of mine not a bug, but i need help to understand what happens to try to fix it.

Description of my case:

I'm sending audio stream to nginx rtmp via Adobe Flash Media Live Encoder situed in a machine with DLS connection. The DLS connection is a little unstable these days:  it goes down for few seconds two times a day, but i realized that when a publisher connection in not properly closed my nginx rtmp instance becomes unstable, and useless: i've to reboot nginx! Adoble Flash Media Live Encoder succesfull reconnects to nginx rtmp, and it says that is going but no data packet is streamed anymore: i see the encoder connected in stats.xls I have a

``` sh
<publishing/>
```

like the working situation, but

``` sh
<avsync>
number
</avsync>
```

remains at the last numeric value before the flap until a reboot (of course also real playback don't works anymore) and nginx debug log says following:

`````` sh

2012/09/29 18:23:51 [debug] 19350#0: *88 RTMP recv audio (8) csid=4 timestamp=487506 mlen=262 msid=1 nbufs=1
2012/09/29 18:23:51 [debug] 19350#0: *88 nhandlers: 4
2012/09/29 18:23:51 [debug] 19350#0: *88 calling handler 0
2012/09/29 18:23:51 [debug] 19350#0: *88 record: day frame: mlen=262
2012/09/29 18:23:51 [debug] 19350#0: *88 write: 25, 00007FFFF77A2FA0, 11, 985856
2012/09/29 18:23:51 [debug] 19350#0: *88 write: 25, 0000000000D17974, 262, 985867
2012/09/29 18:23:51 [debug] 19350#0: *88 write: 25, 00007FFFF77A2FA0, 4, 986129
2012/09/29 18:23:51 [debug] 19350#0: *88 record: hour frame: mlen=262
2012/09/29 18:23:51 [debug] 19350#0: *88 write: 26, 00007FFFF77A2FA0, 11, 985856
2012/09/29 18:23:51 [debug] 19350#0: *88 write: 26, 0000000000D17974, 262, 985867
2012/09/29 18:23:51 [debug] 19350#0: *88 write: 26, 00007FFFF77A2FA0, 4, 986129
2012/09/29 18:23:51 [debug] 19350#0: *88 record: five frame: mlen=262
2012/09/29 18:23:51 [debug] 19350#0: *88 write: 27, 00007FFFF77A2FA0, 11, 985856
2012/09/29 18:23:51 [debug] 19350#0: *88 write: 27, 0000000000D17974, 262, 985867
2012/09/29 18:23:51 [debug] 19350#0: *88 write: 27, 00007FFFF77A2FA0, 4, 986129
2012/09/29 18:23:51 [debug] 19350#0: *88 record: min frame: mlen=262
2012/09/29 18:23:51 [debug] 19350#0: *88 write: 11, 00007FFFF77A2FA0, 11, 349587
2012/09/29 18:23:51 [debug] 19350#0: *88 write: 11, 0000000000D17974, 262, 349598
2012/09/29 18:23:51 [debug] 19350#0: *88 write: 11, 00007FFFF77A2FA0, 4, 349860
2012/09/29 18:23:51 [debug] 19350#0: *88 record: default frame: mlen=262
2012/09/29 18:23:51 [debug] 19350#0: *88 write: 29, 00007FFFF77A2FA0, 11, 985856
2012/09/29 18:23:51 [debug] 19350#0: *88 write: 29, 0000000000D17974, 262, 985867
2012/09/29 18:23:51 [debug] 19350#0: *88 write: 29, 00007FFFF77A2FA0, 4, 986129
2012/09/29 18:23:51 [debug] 19350#0: *88 calling handler 1
2012/09/29 18:23:51 [debug] 19350#0: *88 calling handler 2
2012/09/29 18:23:51 [debug] 19350#0: *88 calling handler 3
2012/09/29 18:23:51 [debug] 19350#0: *88 recv: fd:18 -1 of 280
2012/09/29 18:23:51 [debug] 19350#0: *88 recv() not ready (11: Resource temporarily unavailable)
2012/09/29 18:23:51 [debug] 19350#0: timer delta: 5
2012/09/29 18:23:51 [debug] 19350#0: posted events 0000000000000000
2012/09/29 18:23:51 [debug] 19350#0: worker cycle
2012/09/29 18:23:51 [debug] 19350#0: epoll timer: -1
```sh
``````

**Comment by anas10s** [comment]
hello sir ,


when i restart my internet connection i lose connection to the server rtmp incomming and i will have to reset my ngnix server 
manually is what to fix this anomaly
my config

rtmp_auto_push on;
rtmp {
   server {
   
listen 8001;
push_reconnect 3s;
     interleave on;
     wait_video on;
     idle_streams off;
chunk_size 4096;
notify_method get;
     ping 10s;
     ping_timeout 600s;



thank you in advance for your help
