### ISSUE TITLE
/stat gives blank page

### ISSUE THREAD

**Issue by twister5800** [arut/nginx-rtmp-module#772]
When dooing localhost/stat i get a blank page in chrome, but Ie and FF shows this:
1.9.12
1.1.4
gcc 5.2.1 20151010 (Ubuntu 5.2.1-22ubuntu2) 
Mar  8 2016 15:52:57
1644
4373
4
414368
548786977
96
7888761

live

0

on ONE line.

stat.xsl is located in html folder, as written in config:

# rtmp stat
        location /stat {
            rtmp_stat all;
            rtmp_stat_stylesheet stat.xsl;
        }
        location /stat.xsl {
            # you can move stat.xsl to a different location
            root /usr/local/nginx/html;
        }
best regards
Martin

**Comment by misiek08** [comment]
Can you post source code of generated website (CTRL + U) on Windows/Linux
to see it.
If it's correct XML then xslt is not loading correctly because of some
reason.

**Comment by twister5800** [comment]
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="stat.xsl" ?>
<rtmp>
<nginx_version>1.9.12</nginx_version>
<nginx_rtmp_version>1.1.4</nginx_rtmp_version>
<compiler>gcc 5.2.1 20151010 (Ubuntu 5.2.1-22ubuntu2) </compiler>
<built>Mar  8 2016 15:52:57</built>
<pid>1693</pid>
<uptime>343684</uptime>
<naccepted>152</naccepted>
<bw_in>0</bw_in>
<bytes_in>1109290118</bytes_in>
<bw_out>0</bw_out>
<bytes_out>1501441028</bytes_out>
<server>
<application>
<name>live</name>
<live>
<nclients>0</nclients>
</live>
</application>
</server>
</rtmp>

**Comment by twister5800** [comment]
*bump* ? :)

**Comment by andrew-shulgin** [comment]
See the previous comment

**Comment by twister5800** [comment]
I do not understand what should be wrong with the file?

Is my posted Source code okay?

Br. Martin

Den 22. mar. 2016 kl. 18.46 skrev Andrew Shulgin <notifications@github.com<mailto:notifications@github.com>>:


See the previous comment

-

**Comment by andrew-shulgin** [comment]
Yes. `stat.xsl` is missing, has invalid permissions, etc. Try accessing it directly or make a glance at the Developer Console.

**Comment by twister5800** [comment]
Andrew,

I have followed this guide now:
http://www.helping-squad.com/nginx-rtmp-setup-rtmp-statistics/

Still no graphical output.

I have placed stat.xsl in the html folder and for testing set 777 persmissions on the file.

The developer console show a lot of error with the file:
http://imgur.com/tXvYGjX

can you assist a bit more? - I'm sorry for my bothering - I'm a NOOB at this :)

**Comment by twister5800** [comment]
I found the solution!

I deleted the stat.xsl file and downloaded it again from your page, now all is good - guess the other place I found it, was somehow corrupted!

Sorry for the trouble and thanks for a great module!

Best regards
Martin
