### ISSUE TITLE
Setting variables 

### ISSUE THREAD

**Issue by salemgolemugoo** [arut/nginx-rtmp-module#785]
I want to set some variables inside module configuration block, but getting error: 
`nginx: [emerg] "set" directive is not allowed here`

My config is like this:
```
rtmp {
    server {
        listen 1935;

        set $connect_url http://example.com/index.php;

        on_connect $connect_url;
        live on;
        record off;
    }
}
```

**Comment by RocFang** [comment]
"set" is a command implemented in ngx_http_rewrite_module.
nginx-rtmp is a core level module similar to http and it has not add "set" command yet.
So you could not use this command in rtmp block.

**Comment by salemgolemugoo** [comment]
Ok, thx.
