### ISSUE TITLE
where to set stream->next in ngx_rtmp_live_module

### ISSUE THREAD

**Issue by sfomp** [arut/nginx-rtmp-module#797]
hi all  , i can't find which place to set stream->next in ngx_rtmp_live_module.c when publish stream.

is the below sentence to set stream->next? the next stream is pointed to the new address?

 for (; *stream; stream = &(*stream)->next) {
    ....
*stream = ngx_palloc(lacf->pool, sizeof(ngx_rtmp_live_stream_t));

**Comment by sfomp** [comment]
the source code like this:
ngx_rtmp_live_stream_t    **stream;
lacf = ngx_rtmp_get_module_app_conf(s, ngx_rtmp_live_module);
stream = &lacf->streams[ngx_hash_key(name, len) % lacf->nbuckets];
*stream = ngx_palloc(lacf->pool, sizeof(ngx_rtmp_live_stream_t));

i found above source already set the streams.

**Comment by misiek08** [comment]
What do you want to achieve?

**Comment by sfomp** [comment]
@misiek08  hi , i want to stop a stream through external cmd, not http request, so i should iterate the stream, now i got it the next stream where to set. But, i'm left wondering about why ngx_rtmp_live_ctx_t has next pointer field(next).  How the ngx_rtmp_live_ctx_t can also contain next context, because ngx_rtmp_live_ctx_t contians *stream. we could find next stream  from ngx_rtmp_live_stream_t which contain next.
