### ISSUE TITLE
How to add 5min delay to a stream?

### ISSUE THREAD

**Issue by wzhhou** [arut/nginx-rtmp-module#800]
Hey, 

for some supervisor reason, I need to add 1~5min delay for a stream。 

Hown can I do it in rtmp-module?

Many thanks

**Comment by RocFang** [comment]
does not support currently.
To fulfill this,  you should add some code for caching.

**Comment by wzhhou** [comment]
thanks for helping.
Where should i add a cache?  Could you give some suggestion?
