### ISSUE TITLE
/stat not showing running streams

### ISSUE THREAD

**Issue by kraja** [arut/nginx-rtmp-module#813]
Hi, i trying to set rtmp_stat (i need list of actually exist channels, i mean this is what i want), but i see only traffic and no streams. Its here any bug, please?

Part of my nginx.conf:

```
        location /stat {
            rtmp_stat all;
        }

        location /control {
            rtmp_control all;
        }
```

But:
- /control say "404 not found"
- /stat say no streams, but here is running now some streams:

```
<?xml version="1.0" encoding="utf-8" ?>
<rtmp>
<nginx_version>1.7.3</nginx_version>
<nginx_rtmp_version>1.1.4</nginx_rtmp_version>
<compiler>gcc 4.7.2 (Debian 4.7.2-5) </compiler>
<built>Jul 14 2014 11:00:06</built>
<pid>26879</pid>
<uptime>1105</uptime>
<naccepted>167</naccepted>
<bw_in>2939840</bw_in>
<bytes_in>445939956</bytes_in>
<bw_out>20116088</bw_out>
<bytes_out>2328795967</bytes_out>
<server>
<application>
<name>stream</name>
<live>
<nclients>0</nclients>
</live>
</application>
<application>
<name>income</name>
<live>
<nclients>0</nclients>
</live>
</application>
</server>
</rtmp>
```

Can i doing anything badly?

Thanks

**Comment by misiek08** [comment]
What's you `worker_processes` value?

**Comment by kraja** [comment]
Part of my config:


user  www-data;
worker_processes  1;
worker_rlimit_nofile 200000;
#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
     worker_connections  102400;
}


Thanks!

**Comment by kraja** [comment]
from ps axuf

root     26878  0.0  0.0  38928  1216 ?        Ss   May19   0:00 nginx: master process ./nginx
www-data 26879  8.1  0.2 105752 71020 ?        S    May19 339:10  \_ nginx: worker process
www-data 26880  0.0  0.0  39264  3336 ?        S    May19   0:00  \_ nginx: cache manager process

**Comment by kraja** [comment]
@misiek08 @arut hmm, possible problem with nginx: cache manager process? 
i dont know what is this, i havent got it on base install of nginx...

**Comment by kraja** [comment]
FIXED! 

Really problem with cache manager process, and this process created by this part of configuration:

rtmp {
    server {
        access_log  logs/access.log;
        ping 2m;
        ping_timeout 10s;
        listen 1935;
        chunk_size 4000;
        application  stream {
        live on;
        exec ffmpeg -re -i rtmp://localhost:1935/$app/$name -vcodec libx264 -preset superfast   -acode$
                        -f flv rtmp://localhost:1935/income/${name};
                }
        application  income {
        live on;
        hls on;
        hls_path /tmp/hls;
        dash on;
        dash_path /tmp/dash;
                }
        }
}

-> hls/dash is incompatible with stats?

**Comment by misiek08** [comment]
Cache process shouldn't impact this module. It's getting weird with nginx, looks like arut gives tips to NGINX company to kill module :D

Anyway it's weird, because if I understood correctly cache manager is separate process not affecting any nginx requests handling.
