### ISSUE TITLE
Picture of stream

### ISSUE THREAD

**Issue by dominicusdev** [arut/nginx-rtmp-module#817]
How would I save a snapshot of the current stream?

**Comment by jstabenow** [comment]
not perfect, but it work:
https://github.com/datarhei/restreamer-edge/blob/master/snapshot.sh

**Comment by dominicusdev** [comment]
So in reality it's the ffmpeg?

**Comment by jstabenow** [comment]
japp, it is ffmpeg

**Comment by dominicusdev** [comment]
There has to be a better way. I'll have a look into this. Thanks!

**Comment by dominicusdev** [comment]
https://github.com/arut/nginx-rtmp-module/issues/356 so this is what I'm going to look into instead, but thanks anyways, @jstabenow

**Comment by jstabenow** [comment]
yes there are different ways. my solution was the resource-saving process for my case. but of course that is not always the case. have fun 👍
