### ISSUE TITLE
fail to run exec ffmpeg xxx when doing live streaming

### ISSUE THREAD

**Issue by andrewmabc** [arut/nginx-rtmp-module#837]
Hi,

The latest nginx-rtmp-module and nginx-1.10.1.tar.gz are used to make live streaming server. I use rtmp configuration from nginx-rtmp-module/README.md to setup server, as shown below:

rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        # Transcoding (ffmpeg needed)
        application big {
            live on;

             # On every pusblished stream run this command (ffmpeg)
             # with substitutions: $app/${app}, $name/${name} for application & stream name.
             #
             # This ffmpeg call receives stream from this application &
             # reduces the resolution down to 32x32. The stream is the published to
             # 'small' application (see below) under the same name.
             #
             # ffmpeg can do anything with the stream like video/audio
             # transcoding, resizing, altering container/codec params etc
             #
             # Multiple exec lines can be specified.

             exec ffmpeg -re -i rtmp://localhost:1935/$app/$name -vcodec flv -acodec copy -s 32x32 -f flv rtmp://localhost:1935/small/${name};
        }

        application small {
            live on;
            # Video with reduced resolution comes here from ffmpeg
        }
    }
}

one rtmp stream is sent to the nginx server by using 'ffmpeg.exe -re -i source-video-file.flv -codec copy -f flv rtmp://rtmp-server-ip:1935/big/abc'

Then, I succeed in play live stream in another pc by using one simple command, i.e. ffplay.exe rtmp://rtmp-server-ip:1935/big/abc.

But, I fail to play live stream by using the command, i.e. ffplay.exe rtmp://rtmp-server-ip:1935/small/abc.

I think ffmpeg have never been invoked. How to solve the problem?

Thanks

**Comment by andrewmabc** [comment]
error.log is shown as belown for reference:

2016/06/17 12:03:00 [info] 2836#0: *17 client connected '10.0.2.101'
2016/06/17 12:03:00 [info] 2836#0: *17 connect: app='live1' args='' flashver='' swf_url='' tc_url='rtmp://10.0.2.100:1935/live1' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 10.0.2.101, server: 0.0.0.0:1935
2016/06/17 12:03:00 [info] 2836#0: *17 createStream, client: 10.0.2.101, server: 0.0.0.0:1935
2016/06/17 12:03:00 [info] 2836#0: *17 publish: name='test' args='' type=live silent=0, client: 10.0.2.101, server: 0.0.0.0:1935
2016/06/17 12:03:00 [info] 2836#0: *17 exec: starting managed child '/usr/local/bin/ffmpeg', client: 10.0.2.101, server: 0.0.0.0:1935
2016/06/17 12:03:00 [info] 2836#0: *17 exec: child 2910 exited; ignoring, client: 10.0.2.101, server: 0.0.0.0:1935
2016/06/17 12:03:00 [info] 2836#0: *17 exec: terminating child 2910, client: 10.0.2.101, server: 0.0.0.0:1935
2016/06/17 12:03:00 [notice] 2836#0: signal 17 (SIGCHLD) received
2016/06/17 12:03:00 [notice] 2836#0: unknown process 2910 exited with code 127
2016/06/17 12:03:00 [info] 2836#0: epoll_wait() failed (4: Interrupted system call)
2016/06/17 12:03:05 [info] 2836#0: *17 exec: starting managed child '/usr/local/bin/ffmpeg', client: 10.0.2.101, server: 0.0.0.0:1935
2016/06/17 12:03:05 [notice] 2836#0: signal 17 (SIGCHLD) received
2016/06/17 12:03:05 [notice] 2836#0: unknown process 2911 exited with code 127
2016/06/17 12:03:05 [info] 2836#0: *17 exec: child 2911 exited; ignoring, client: 10.0.2.101, server: 0.0.0.0:1935
2016/06/17 12:03:05 [info] 2836#0: *17 exec: terminating child 2911, client: 10.0.2.101, server: 0.0.0.0:1935
2016/06/17 12:03:10 [info] 2836#0: *17 exec: starting managed child '/usr/local/bin/ffmpeg', client: 10.0.2.101, server: 0.0.0.0:1935
2016/06/17 12:03:10 [notice] 2836#0: signal 17 (SIGCHLD) received
2016/06/17 12:03:10 [notice] 2836#0: unknown process 2913 exited with code 127
2016/06/17 12:03:10 [info] 2836#0: *17 exec: child 2913 exited; ignoring, client: 10.0.2.101, server: 0.0.0.0:1935
2016/06/17 12:03:10 [info] 2836#0: *17 exec: terminating child 2913, client: 10.0.2.101, server: 0.0.0.0:1935
2016/06/17 12:03:15 [info] 2836#0: *17 exec: starting managed child '/usr/local/bin/ffmpeg', client: 10.0.2.101, server: 0.0.0.0:1935
2016/06/17 12:03:15 [notice] 2836#0: signal 17 (SIGCHLD) received
2016/06/17 12:03:15 [notice] 2836#0: unknown process 2914 exited with code 127
2016/06/17 12:03:15 [info] 2836#0: *17 exec: child 2914 exited; ignoring, client: 10.0.2.101, server: 0.0.0.0:1935
2016/06/17 12:03:15 [info] 2836#0: *17 exec: terminating child 2914, client: 10.0.2.101, server: 0.0.0.0:1935
2016/06/17 12:03:20 [info] 2836#0: *17 exec: starting managed child '/usr/local/bin/ffmpeg', client: 10.0.2.101, server: 0.0.0.0:1935
2016/06/17 12:03:20 [info] 2836#0: *17 exec: child 2915 exited; ignoring, client: 10.0.2.101, server: 0.0.0.0:1935
2016/06/17 12:03:20 [info] 2836#0: *17 exec: terminating child 2915, client: 10.0.2.101, server: 0.0.0.0:1935
2016/06/17 12:03:20 [notice] 2836#0: signal 17 (SIGCHLD) received
2016/06/17 12:03:20 [notice] 2836#0: unknown process 2915 exited with code 127
2016/06/17 12:03:20 [info] 2836#0: epoll_wait() failed (4: Interrupted system call)
2016/06/17 12:03:25 [info] 2836#0: *17 exec: starting managed child '/usr/local/bin/ffmpeg', client: 10.0.2.101, server: 0.0.0.0:1935
2016/06/17 12:03:25 [notice] 2836#0: signal 17 (SIGCHLD) received
2016/06/17 12:03:25 [notice] 2836#0: unknown process 2916 exited with code 127
2016/06/17 12:03:25 [info] 2836#0: *17 exec: child 2916 exited; ignoring, client: 10.0.2.101, server: 0.0.0.0:1935
2016/06/17 12:03:25 [info] 2836#0: *17 exec: terminating child 2916, client: 10.0.2.101, server: 0.0.0.0:1935
2016/06/17 12:03:30 [info] 2836#0: *17 exec: starting managed child '/usr/local/bin/ffmpeg', client: 10.0.2.101, server: 0.0.0.0:1935
2016/06/17 12:03:30 [notice] 2836#0: signal 17 (SIGCHLD) received
2016/06/17 12:03:30 [notice] 2836#0: unknown process 2917 exited with code 127
2016/06/17 12:03:30 [info] 2836#0: *17 exec: child 2917 exited; ignoring, client: 10.0.2.101, server: 0.0.0.0:1935
2016/06/17 12:03:30 [info] 2836#0: *17 exec: terminating child 2917, client: 10.0.2.101, server: 0.0.0.0:1935
2016/06/17 12:03:34 [info] 2836#0: *17 deleteStream, client: 10.0.2.101, server: 0.0.0.0:1935
2016/06/17 12:03:34 [info] 2836#0: *17 disconnect, client: 10.0.2.101, server: 0.0.0.0:1935
2016/06/17 12:03:34 [info] 2836#0: *17 deleteStream, client: 10.0.2.101, server: 0.0.0.0:1935

**Comment by Sea-Monster** [comment]
the same problem:
https://github.com/arut/nginx-rtmp-module/issues/1011

Do you know how to fix that please?
