### ISSUE TITLE
HLS AFTER 0 KBPS OBS

### ISSUE THREAD

**Issue by tolgatasci** [arut/nginx-rtmp-module#857]
START 3000KBPS

NEXT 10 MİNUTE LATEST

0 KBPS

`2016/07/28 17:00:40 [info] 30132#0: *600 client closed connection while waiting for request, client: 78.171.11.120, server: 0.0.0.0:80
2016/07/28 17:00:40 [info] 30132#0: *601 client closed connection while waiting for request, client: 78.171.11.120, server: 0.0.0.0:80
2016/07/28 17:00:40 [info] 30132#0: *603 client closed connection while waiting for request, client: 78.171.11.120, server: 0.0.0.0:80
2016/07/28 17:00:40 [info] 30132#0: *602 client closed connection while waiting for request, client: 78.171.11.120, server: 0.0.0.0:80
2016/07/28 17:01:09 [info] 30143#0: *412 disconnect, client: MY İP OBS, server: 0.0.0.0:1935
2016/07/28 17:01:09 [info] 30143#0: *412 deleteStream, client: MY İP OBS, server: 0.0.0.0:1935
2016/07/28 17:01:09 [info] 30143#0: *419 disconnect, client: unix:/tmp/nginx-rtmp.6, server: ngx-relay
2016/07/28 17:01:09 [info] 30143#0: *419 deleteStream, client: unix:/tmp/nginx-rtmp.6, server: ngx-relay
2016/07/28 17:01:09 [info] 30143#0: *464 disconnect, client: unix:/tmp/nginx-rtmp.13, server: ngx-relay
2016/07/28 17:01:09 [info] 30143#0: *464 deleteStream, client: unix:/tmp/nginx-rtmp.13, server: ngx-relay
2016/07/28 17:01:09 [info] 30136#0: *448 disconnect, client: , server: 0.0.0.0:1935
2016/07/28 17:01:09 [info] 30143#0: *469 disconnect, client: unix:/tmp/nginx-rtmp.2, server: ngx-relay
2016/07/28 17:01:09 [info] 30136#0: *448 deleteStream, client: , server: 0.0.0.0:1935
2016/07/28 17:01:09 [info] 30144#0: *466 disconnect, client: , server: 0.0.0.0:1935
2016/07/28 17:01:09 [info] 30143#0: *469 deleteStream, client: unix:/tmp/nginx-rtmp.2, server: ngx-relay
2016/07/28 17:01:09 [info] 30144#0: *466 deleteStream, client: , server: 0.0.0.0:1935
2016/07/28 17:01:09 [info] 30143#0: *488 disconnect, client: unix:/tmp/nginx-rtmp.9, server: ngx-relay
2016/07/28 17:01:09 [info] 30132#0: *480 disconnect, client: , server: 0.0.0.0:1935
2016/07/28 17:01:09 [info] 30143#0: *488 deleteStream, client: unix:/tmp/nginx-rtmp.9, server: ngx-relay
2016/07/28 17:01:09 [info] 30132#0: *480 deleteStream, client: , server: 0.0.0.0:1935
2016/07/28 17:01:09 [info] 30143#0: *530 disconnect, client: unix:/tmp/nginx-rtmp.7, server: ngx-relay
2016/07/28 17:01:09 [info] 30143#0: *530 deleteStream, client: unix:/tmp/nginx-rtmp.7, server: ngx-relay
2016/07/28 17:01:09 [info] 30140#0: *496 disconnect, client: , server: 0.0.0.0:1935
2016/07/28 17:01:09 [info] 30143#0: *582 disconnect, client: unix:/tmp/nginx-rtmp.0, server: ngx-relay
2016/07/28 17:01:09 [info] 30140#0: *496 deleteStream, client: , server: 0.0.0.0:1935
2016/07/28 17:01:09 [info] 30137#0: *569 disconnect, client: , server: 0.0.0.0:1935
2016/07/28 17:01:09 [info] 30143#0: *582 deleteStream, client: unix:/tmp/nginx-rtmp.0, server: ngx-relay
2016/07/28 17:01:09 [info] 30137#0: *569 deleteStream, client: , server: 0.0.0.0:1935
2016/07/28 17:01:09 [info] 30143#0: *583 disconnect, client: unix:/tmp/nginx-rtmp.1, server: ngx-relay
2016/07/28 17:01:09 [info] 30143#0: *583 deleteStream, client: unix:/tmp/nginx-rtmp.1, server: ngx-relay
2016/07/28 17:01:09 [info] 30143#0: *584 disconnect, client: unix:/tmp/nginx-rtmp.3, server: ngx-relay
2016/07/28 17:01:09 [info] 30143#0: *584 deleteStream, client: unix:/tmp/nginx-rtmp.3, server: ngx-relay
2016/07/28 17:01:09 [info] 30131#0: *599 disconnect, client: , server: 0.0.0.0:1935
2016/07/28 17:01:09 [info] 30143#0: *585 disconnect, client: unix:/tmp/nginx-rtmp.4, server: ngx-relay
2016/07/28 17:01:09 [info] 30131#0: *599 deleteStream, client: , server: 0.0.0.0:1935
2016/07/28 17:01:09 [info] 30143#0: *585 deleteStream, client: unix:/tmp/nginx-rtmp.4, server: ngx-relay
2016/07/28 17:01:09 [info] 30143#0: *586 disconnect, client: unix:/tmp/nginx-rtmp.5, server: ngx-relay
2016/07/28 17:01:09 [info] 30143#0: *586 deleteStream, client: unix:/tmp/nginx-rtmp.5, server: ngx-relay
2016/07/28 17:01:09 [info] 30143#0: *587 disconnect, client: unix:/tmp/nginx-rtmp.8, server: ngx-relay
2016/07/28 17:01:09 [info] 30143#0: *587 deleteStream, client: unix:/tmp/nginx-rtmp.8, server: ngx-relay
2016/07/28 17:01:09 [info] 30143#0: *588 disconnect, client: unix:/tmp/nginx-rtmp.10, server: ngx-relay
2016/07/28 17:01:09 [info] 30143#0: *588 deleteStream, client: unix:/tmp/nginx-rtmp.10, server: ngx-relay
2016/07/28 17:01:09 [info] 30143#0: *589 disconnect, client: unix:/tmp/nginx-rtmp.11, server: ngx-relay
2016/07/28 17:01:09 [info] 30143#0: *589 deleteStream, client: unix:/tmp/nginx-rtmp.11, server: ngx-relay`

`rtmp {
    server {
        respawn on;
     respawn_timeout 2s;
     chunk_size 4096;
     ping 20s;
     ping_timeout 10s;
     drop_idle_publisher 20s;
     publish_notify on;
     idle_streams off;
        listen 1935; # Listen on standard RTMP port

```
    # This application is to accept incoming stream
    application live {


        live on; 

        wait_key on;
         interleave off;
        push_reconnect 30s;

    }

    # This application is for splitting the stream into HLS fragments
    application show {

        live on; # Allows live input from above
        hls on; # Enable HTTP Live Streaming

        allow publish all;

        hls_playlist_length 10s; 
        wait_key on;


        hls_continuous on;
    hls_cleanup on;

        push_reconnect 15s;

        hls_fragment 5s;
        hls_path /home/oneprovider/www/hls/;

        # Instruct clients to adjust resolution according to bandwidth
        #hls_variant _low BANDWIDTH=288000; # Low bitrate, sub-SD resolution
        #hls_variant _mid BANDWIDTH=448000; # Medium bitrate, SD resolution
        #hls_variant _high BANDWIDTH=1152000; # High bitrate, higher-than-SD resolution
        #hls_variant _hd720 BANDWIDTH=2048000; # High bitrate, HD 720p resolution
        #hls_variant _src BANDWIDTH=4096000; # Source bitrate, source resolution
    }
}
```

}`

plase help ty

**Comment by djstava** [comment]
I have the same problem. I use ffmpeg command line to push live stream to nginx-rtmp,but  after hours the stream stops.Did you fixed it? My nginx.conf

`#user  nobody;
worker_processes  auto;

rtmp_auto_push on;
rtmp_auto_push_reconnect 1s;
rtmp_socket_dir /tmp;

#error_log  logs/error.log debug;
error_log  logs/error.log info;
error_log  logs/error.log error;

#pid        logs/nginx.pid;

events {
    worker_connections  1024;
#    accept_mutex on;
}

rtmp {

    publish_time_fix off;

    server {

        listen 1935;
        respawn on;
        respawn_timeout 2s;
        ping 20s;
        ping_timeout 10s;
        drop_idle_publisher 20s;
        publish_notify on;
        idle_streams off;

        chunk_size 4000;

        # TV mode: one publisher, many subscribers
        application mytv {

            # enable live streaming
            live on;

            # record first 1K of stream
            record all;
            record_path /tmp/av;
            record_max_size 1K;

            # append current timestamp to each flv
            record_unique on;

            # publish only from localhost
            allow publish 127.0.0.1;
            deny publish all;

            #allow play all;
        }

        # Transcoding (ffmpeg needed)
        #application big {
        #    live on;

            # On every pusblished stream run this command (ffmpeg)
            # with substitutions: $app/${app}, $name/${name} for application & stream name.
            #
            # This ffmpeg call receives stream from this application &
            # reduces the resolution down to 32x32. The stream is the published to
            # 'small' application (see below) under the same name.
            #
            # ffmpeg can do anything with the stream like video/audio
            # transcoding, resizing, altering container/codec params etc
            #
            # Multiple exec lines can be specified.

        #    exec ffmpeg -re -i rtmp://localhost:1935/$app/$name -vcodec flv -acodec copy -s 32x32
                        #-f flv rtmp://localhost:1935/small/${name};
        #}

        #application small {
        #    live on;
        #    # Video with reduced resolution comes here from ffmpeg
        #}

        #application webcam {
        #    live on;

            # Stream from local webcam
        #    exec_static ffmpeg -f video4linux2 -i /dev/video0 -c:v libx264 -an
                               #-f flv rtmp://localhost:1935/webcam/mystream;
        #}

        application mypush {
            live on;

            # Every stream published here
            # is automatically pushed to
            # these two machines
            #push rtmp1.example.com;
            #push rtmp2.example.com:1934;
        }

        application mypull {
            live on;

            # Pull all streams from remote machine
            # and play locally
            #pull rtmp://rtmp3.example.com pageUrl=www.example.com/index.html;
        }

        application mystaticpull {
            live on;

            # Static pull is started at nginx start
            #pull rtmp://rtmp4.example.com pageUrl=www.example.com/index.html name=mystream static;
        }

        # video on demand
        application vod {
            play /opt/www/vod;
        }

        application vod2 {
            play /var/mp4s;
        }

        # Many publishers, many subscribers
        # no checks, no recording
        application videochat {

            live on;

            # The following notifications receive all
            # the session variables as well as
            # particular call arguments in HTTP POST
            # request

            # Make HTTP request & use HTTP retcode
            # to decide whether to allow publishing
            # from this connection or not
            on_publish http://localhost:8080/publish;

            # Same with playing
            on_play http://localhost:8080/play;

            # Publish/play end (repeats on disconnect)
            on_done http://localhost:8080/done;

            # All above mentioned notifications receive
            # standard connect() arguments as well as
            # play/publish ones. If any arguments are sent
            # with GET-style syntax to play & publish
            # these are also included.
            # Example URL:
            #   rtmp://localhost/myapp/mystream?a=b&c=d

            # record 10 video keyframes (no audio) every 2 minutes
            record keyframes;
            record_path /tmp/vc;
            record_max_frames 10;
            record_interval 2m;

            # Async notify about an flv recorded
            on_record_done http://localhost:8080/record_done;

        }


        # HLS

        # For HLS to work please create a directory in tmpfs (/tmp/hls here)
        # for the fragments. The directory contents is served via HTTP (see
        # http{} section in config)
        #
        # Incoming stream must be in H264/AAC. For iPhones use baseline H264
        # profile (see ffmpeg example).
        # This example creates RTMP stream from movie ready for HLS:
        #
        # ffmpeg -loglevel verbose -re -i movie.avi  -vcodec libx264
        #    -vprofile baseline -acodec libmp3lame -ar 44100 -ac 1
        #    -f flv rtmp://localhost:1935/hls/movie
        #
        # If you need to transcode live stream use 'exec' feature.
        #
        application hls {
            live on;
            hls on;
            dash off;

            wait_key on;

            hls_path /opt/www/live;
            hls_fragment 10s;
            hls_cleanup on;
            hls_fragment_naming system;
            hls_fragment_naming_granularity 500;
            hls_type live;

            # hls_playlist_length 10m;
            hls_sync 100ms;
            hls_continuous on;
            #hls_base_url http://10.10.10.188:8081/live/;
            hls_nested on;

            #hls_keys on;
            #hls_key_path /opt/www/keys;
            #hls_key_url http://10.10.10.188:8081/keys/;
            #hls_fragments_per_key 10;


            # record
            recorder record {
                record all manual;
                record_suffix -%Y-%m-%m-%H_%M_%S.flv;
                record_unique on;
                record_path /opt/www/record;
            }
        }

        # MPEG-DASH is similar to HLS

        application dash {
            live on;
            dash on;
            dash_path /tmp/dash;
        }
    }
}

# HTTP can be used for accessing RTMP stats
http {

    keepalive_timeout  65;

    server {

        listen      8081;

        location / {
            root /opt/www/;
        }

        location /control {
            rtmp_control all;
        }

        # This URL provides RTMP statistics in XML
        location /stat {
            rtmp_stat all;

            # Use this stylesheet to view XML as web page
            # in browser
            rtmp_stat_stylesheet stat.xsl;
        }

        location /stat.xsl {
            # XML stylesheet to view RTMP stats.
            # Copy stat.xsl wherever you want
            # and put the full directory path here
            root /home/longjing/nginx-rtmp-module/;
        }

        location /hls {
            # Serve HLS fragments
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }

            root /opt/www/;
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *;
        }

        location /dash {
            # Serve DASH fragments
            root /tmp;
            add_header Cache-Control no-cache;
        }
    }
}`

**Comment by bf** [comment]
any update?

**Comment by malcm** [comment]
@tolgatasci is there any solution for this issue that you closed it?

**Comment by tolgatasci** [comment]
ubuntu problem beacause
sudo session out and kbps 0 
i dont know :(
