### ISSUE TITLE
compile with openssl v1.1

### ISSUE THREAD

**Issue by Cheedoong** [arut/nginx-rtmp-module#902]
Nginx has added support for OpenSSL since [1.10](https://nginx.org/en/CHANGES-1.10). 
However, it fails when compile rtmp module with Nginx 1.10 and OpenSSL 1.1. 
Do you have a plan to support OpenSSL v1.1?

**Comment by DeadSix27** [comment]
@Cheedoong did you have any luck making it work yourself?

**Comment by Cheedoong** [comment]
@DeadSix27  Unfortunately not. But Nginx has added support for openssl 1.1 since version 1.9.14. You may want to have a look at those commitments.

**Comment by DeadSix27** [comment]
@Cheedoong I know, but seems useless until someone patches nginx rtmp module to work with it.

**Comment by arut** [comment]
I've fixed compilation with OpenSSL 1.1
