### ISSUE TITLE
What nginx and rtmp module versions (branch) do you use for HLS live streaming

### ISSUE THREAD

**Issue by selimatmaca** [arut/nginx-rtmp-module#913]
Hi everyone,
I am trying to do live streaming using HLS and randomly my fragments and index file disappear (deletes itself) and stream ends. My setup is: IPCamera - OBS - Nginx (ffmpeg) - VideoJS. Stream sometimes end in 5 minutes and sometimes in 1 hour. 
First I had this problem with Nginx1.11.6 and arut's master. 
Then I tried Nginx1.11.6 and sergey-dryabzhinsky's latest -dev, and experienced the same problem.
Then I tried 1.9.10 with sergey's a couple of branches. I couldn't get rid of the problem. HLS index and fragments are deleted automatically. I tried many different ffmpeg commands that I could find on the internet.

My question is: I am sure there are some of you who can succesfully do live streaming by using HLS. Can you please tell me what version nginx and what version of rtmp module you are using. So I can try with them.

**Comment by Somosmultimedia** [comment]
Can you share the nginx.conf

**Comment by selimatmaca** [comment]
Sure, here it is:
user nginxuser;
worker_processes 1;
#error_log logs/error.log;
#error_log logs/error.log notice;
#error_log logs/error.log info;
#pid logs/nginx.pid;
events {
worker_connections 1024;
}
http {
include mime.types;
default_type application/octet-stream;

#log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
#                  '$status $body_bytes_sent "$http_referer" '
#                  '"$http_user_agent" "$http_x_forwarded_for"';

#access_log  logs/access.log  main;

sendfile        on;
#tcp_nopush     on;

#keepalive_timeout  0;
keepalive_timeout  65;

#gzip  on;

server {
    listen       80;
    server_name  10.20.5.238;

    #charset koi8-r;

    #access_log  logs/host.access.log  main;

        location /hls {
        # Serve HLS fragments
        types {
            application/vnd.apple.mpegurl m3u8;
            video/mp2t ts;                
        }
        root /tmp/;
        add_header Cache-Control no-cache;
        add_header 'Access-Control-Allow-Origin' '*';
          }





    location / {
       
        root   html;
        index  index.html index.htm;
        add_header 'Access-Control-Allow-Origin' '*';    

    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   html;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    #location ~ \.php$ {
    #    root           html;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #    include        fastcgi_params;
    #}

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}


# another virtual host using mix of IP-, name-, and port-based configuration
#
#server {
#    listen       8000;
#    listen       somename:8080;
#    server_name  somename  alias  another.alias;

#    location / {
#        root   html;
#        index  index.html index.htm;
#    }
#}


# HTTPS server
#
#server {
#    listen       443 ssl;
#    server_name  localhost;

#    ssl_certificate      cert.pem;
#    ssl_certificate_key  cert.key;

#    ssl_session_cache    shared:SSL:1m;
#    ssl_session_timeout  5m;

#    ssl_ciphers  HIGH:!aNULL:!MD5;
#    ssl_prefer_server_ciphers  on;

#    location / {
#        root   html;
#        index  index.html index.htm;
#    }
#}
}
}

rtmp {
server {
listen 1935;

    application live {
        live on;
exec ffmpeg -i rtmp://10.20.5.238/$app/$name -vcodec libx264 -vprofile
baseline -acodec aac -strict -2 -f flv rtmp://10.20.5.238/hls/$name;

}

application hls {
live on;
hls on;

        hls_path /tmp/hls/;
       
       }    

}
}

And My OBS Settings:
http://www.selimatmaca.com/images/OBS/obs5.png
http://www.selimatmaca.com/images/OBS/obs6.png

**Comment by selimatmaca** [comment]
I solved my problem. Thanks anyway. I was using OBS for windows and I tried it with OBS for Mac and hls started working just fine
