### ISSUE TITLE
simple RTMP bottlenecks 

### ISSUE THREAD

**Issue by massoudAfrashteh** [arut/nginx-rtmp-module#930]
I have a RTMP application that is realy simple I mean there is no encoding stuff on it:
```
application push {
    live on;
}
```
I think the only bottleneck will be network one yeah? Because I think it likes simple file serving in webservers (Nginx, Apache, or etc) then there will be no other limitation in push and play and if server has the enough network connection then can Publish and Play N numbers of videos on RTMP, Am I right?

**Comment by mattkenefick** [comment]
Why was this closed without a response? Did you find a solution to your question?
