### ISSUE TITLE
[QUESTION] Are there bitrate limits on recording?

### ISSUE THREAD

**Issue by Fladrif** [arut/nginx-rtmp-module#932]
I'm using this to record a stream from an rtmp streaming device that re-encodes the video. 
[nginx.txt](https://github.com/arut/nginx-rtmp-module/files/686016/nginx.txt)

The question I have is that is there a limit to the bitrate for nginx's recording? I find that if I go over 5Mbps, the resulting video is corrupted; the video length is usually twice as long and it has stutters that lose video. 

Thanks.

**Comment by UKNickyD** [comment]
If there is then I would think it's an issue with ffmpeg rather than this module... Did you ever solve this?
