### ISSUE TITLE
Manual recordings

### ISSUE THREAD

**Issue by Xavier-Coutinho** [arut/nginx-rtmp-module#946]
So, I'm quite new to this type of stuff, and I've been asked to set up a button to start and stop recordings from inside the webpage the livestream is beeing transmited on, I've done it but everytime I try to record I just get this error:

> 
> An error occurred.
> 
> Sorry, the page you are looking for is currently unavailable.
> Please try again later.
> 
> If you are the system administrator of this resource then you should check the error log for details.
> 
> Faithfully yours, nginx.

I've looked around in the error log and I can't find anything that can help me fix this.

I've attached my error.log and my conf file, I would be glad if someone could help me.

http://pastebin.com/EkX3XKnQ - nginx.conf

http://pastebin.com/gFzFt2tg - error.log

**Comment by danionescu2007** [comment]
works like a charm
check the docs here: [(https://github.com/arut/nginx-rtmp-module/wiki/Control-module)]
you need to specify the name of the stream to be recorded like this via a web call:
```
http://172.16.1.222/control/record/start?app=live&name=test1&rec=rec
http://172.16.1.222/control/record/stop?app=live&name=test1&rec=rec
```

It will return the name of the file being recorded to.

**Comment by waytvindia** [comment]
Iam new to this work pls help me
Thankyou
