### ISSUE TITLE
Pull from RTMP server origin when hls client connects

### ISSUE THREAD

**Issue by joyel24** [arut/nginx-rtmp-module#947]
When a client enter address of nginx server in rtmp you can read live video from other rtmp server (in conf : 'pull rtmp://ip_domain/app/') but when a client connects in hls, It don't work.

**Comment by rosswilson** [comment]
This is because with HLS, the client is requesting the segments via normal HTTP GET requests, rather than RTMP which uses a long-lived connection. The HLS segments are just being served as static files.

I don't know of any way to get the same `pull` behaviour with a client using HLS.

**Comment by timiil** [comment]
face the same problem , can we just send a http command just like 'http://xxx/control/pullondemand/start?app=live&name=mystream'  at first; that can mansual make the rtmp appilation start. 
alson we can make 'http://xxx/control/pullondemand/stop?app=live&name=mystream'  to stop this rtmp application.

**Comment by entonbiba** [comment]
You can do something like this with php but you'll need ffmpeg installed.

Start the stream
`/home/start.php`
```
if(empty(exec('pgrep ffmpeg'))){
    exec('ffmpeg -i rtmp://LIVERTMPFEED -c:v libx264 -c:a copy -f flv rtmp://localhost/live/live');
}
```

Stop the stream
`/home/stop.php`
```
exec('killall --ignore-case --signal SIGTERM  ffmpeg');
```

`nginx conf`
```
application live { 
        allow publish 127.0.0.1;
        allow publish 0.0.0.0;
        deny publish all;
        live on; 
        hls on; 
        hls_path /home/hls/; 
}
```

**Comment by joyel24** [comment]
I close the issue as I don't need RTMP server anymore and more than 3 years have passed...
