### ISSUE TITLE
RTMP Problem with streaming stop after start

### ISSUE THREAD

**Issue by janiel14** [arut/nginx-rtmp-module#953]
Guys, I've been working with this module for some time and noticed a strange problem in the live application. When I am transmitting normally, I then open 2 player and beauty are synchronized, but when I open a third it opens later in the video and after a few seconds it hangs and waits for the other players to arrive at or near the time of the video. This happens because the server does not have chunk files of the video so the last one to connect has to wait a few seconds to load. But I think the server should treat this and not the client just like Wowza. I do not know how to implement but it should have a server side buffer to keep the live streaming always a little behind so clients do not watch for a few seconds and then crash until the server loads new chunks files.

my configuration
`user  nginx;
worker_processes  auto;
worker_rlimit_nofile 66536;
#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

pid        /var/run/nginx.pid;

events {
    worker_connections 66536;
    use epoll;
    multi_accept on;
    accept_mutex on;
    accept_mutex_delay 500ms;
}

### CONFIG RTMP
rtmp {
      	# Logs
	access_log  /etc/nginx/rtmp/access.log;

        # Server
        server {
                listen 1935;
                chunk_size 4096;
                notify_method get;
                #on_connect http://localhost/auth;

                # Load applications
                include /etc/nginx/rtmp/applications/*.conf;
        }
}
`
#### APPLICATION
`application live {
        live on;
        hls on;
        hls_path /tmp/live;
        #hls_playlist_length 30m;

        # record first 1K of stream
        #recorder all {
        #        record all manual;
        #	record_path /home/records;
        #        record_max_size 500M;
        #        record_suffix _%y-%m-%d--%T.mp4;
        #	record_unique on;
        #        record_notify on;
        #}
}
`

### Exit

`        location /live {
            # Serve HLS fragments
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            root /tmp;
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin '*';
        }
`

please help

**Comment by monokrome** [comment]
@janiel14 what happened?
