### ISSUE TITLE
Dash Not Vaild

### ISSUE THREAD

**Issue by TheStripe** [arut/nginx-rtmp-module#955]
Hi. I have been testing with this and with the sergey-dryabzhinsky versions. This one works with HLS for me great but dash does not work at all. The sergey version has a working dash when i compiled but not a working HLS. I would rather use this branch for sure, is there a way to fix the .mpd dash so it is valid? here's the output i am getting 

git clone https://github.com/arut/nginx-rtmp-module.git
nginx version 1.11.10

validator
http://www-itec.uni-klu.ac.at/dash/?page_id=605

XSD for checking: DASH International Standard XSD

Start Schematron validation
===========================

<svrl:failed-assert test="if (@type = ‘dynamic’ and not(@publishTime)) then false() else true()"
location="/*[local-name()='MPD' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']">
<svrl:text>If MPD is of type "dynamic" publishTime shall be defined.</svrl:text>
</svrl:failed-assert>
<svrl:failed-assert test="if (exists(parent::dash:AdaptationSet/@par) and exists(@sar) and exists(@width) and exists(@height)) then if(abs((number(tokenize(parent::dash:AdaptationSet/@par,’:')[1]) div number(tokenize(parent::dash:AdaptationSet/@par,’:')[2])) – ((number(@width) * number(tokenize(@sar,’:')[1])) div (number(@height) * number(tokenize(@sar,’:')[2])))) &lt; 0.001) then true() else false() else if(not(parent::dash:AdaptationSet/@par) and @sar) then false() else if(exists(parent::dash:AdaptationSet/@par) and not(@sar)) then false() else true()"
location="/*[local-name()='MPD' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']/*[local-name()='Period' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']/*[local-name()='AdaptationSet' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][1]/*[local-name()='Representation' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']">
<svrl:text>If par is present in AdaptationSet, widh*sarx and height*sary shall have the same ratio.</svrl:text>
</svrl:failed-assert>
Schematron validation not successful – DASH is not valid!

Thanks,
Rob

**Comment by kenanchristian** [comment]
@TheStripe Hi, how do you solved this issue? Is the fork merged?

**Comment by codegastudio** [comment]
@TheStripe thx to share your solution please

**Comment by TheStripe** [comment]
Hi guys. I was using bitmovin client which was unforgiving of the errors. I since found a client that apparently is more forgiving and had a better buffer. I can get you the client I am using later today.
