### ISSUE TITLE
Issues when trying to use uri arguments

### ISSUE THREAD

**Issue by Valhadon** [arut/nginx-rtmp-module#994]
Hi,

I have stood up a local NGINX server using the nginx-rtmp-module and seem to be having issues when trying to use uri arguments. I have tried looking for solutions online and can't seem to find a solid answer for this. In my example below I am trying to use the "title" uri argument to create a directory to move my clips to.

I am running a sample stream using the following command:
```
ffmpeg -loglevel verbose -re -i sample.mp4 -c copy -f flv rtmp://localhost:1935/rec/sample?title=test -nostdin
```
And this is the RTMP configuration I am using:
```
# RTMP configuration.
rtmp{
    server{
        # Listen on standard RTMP port.
        listen 1935; 
        chunk_size 4096;
        
        # Main record application to record clips.
        application rec {
            live on;
            meta copy;
            
            recorder chunked {
                record all;
                record_interval 30s;
                record_unique on;
                record_path /home/tmp;
                
                # Move clip to stage.
                exec_record_done /bin/sh -c "mkdir -p home/stage/$args/$name && mv $path home/stage/$args/$name;
            }
        }
    }
}
```
I receive the following output which shows the "title" uri argument:
```
[30/Mar/2017:21:11:48 +0000] PUBLISH "rec" "sample" "title=test" - 22053613 529 "" "FMLE/3.0 (compatible; FMSc/1.0)" (1m 7s)
```
$args contains all the arguments sent and creates the folder "title=test" is there a way to parse out the value? Do I need to setup a local redirect using one of the callbacks (on_publish, etc..) and handle it on the http server? If so, how do I make this data available to the application afterwards? Any help is appreciated.

Thanks!

**Comment by Valhadon** [comment]
I have decided to just write a script to parse the $args and perform any actions I need.

**Comment by hoodsy** [comment]
@Valhadon what does your final solution look like? I'm having trouble running my bash script via `exec_record_done`

**Comment by Valhadon** [comment]
@hoodsy Your solution may vary as I am running this in an Alpine container, but here is how I invoke my script:

`
exec_publish_done /bin/sh -c "python /usr/local/bin/generate_done_data.py -n \"$name\"";
`
